// Dedicated per-breed structural and oracle-coverage tests.
// Runtime paper-pointer and anti-cheat behavior remains generated by ggen.

#[path = "breed_contracts/ltl_monitor.rs"]
mod ltl_monitor;

#[path = "breed_contracts/allen_temporal.rs"]
mod allen_temporal;

#[path = "breed_contracts/ctl_check.rs"]
mod ctl_check;

#[path = "breed_contracts/event_calculus.rs"]
mod event_calculus;

#[path = "breed_contracts/situation_calculus.rs"]
mod situation_calculus;

#[path = "breed_contracts/fuzzy_logic.rs"]
mod fuzzy_logic;

#[path = "breed_contracts/dempster_shafer.rs"]
mod dempster_shafer;

#[path = "breed_contracts/abductive_ibe.rs"]
mod abductive_ibe;

#[path = "breed_contracts/bayesian_network.rs"]
mod bayesian_network;

#[path = "breed_contracts/problog.rs"]
mod problog;

#[path = "breed_contracts/markov_logic.rs"]
mod markov_logic;

#[path = "breed_contracts/htn_planning.rs"]
mod htn_planning;

#[path = "breed_contracts/partial_order_plan.rs"]
mod partial_order_plan;

#[path = "breed_contracts/contingent_plan.rs"]
mod contingent_plan;

#[path = "breed_contracts/mdp.rs"]
mod mdp;

#[path = "breed_contracts/pomdp.rs"]
mod pomdp;

#[path = "breed_contracts/strips.rs"]
mod strips;

#[path = "breed_contracts/gps.rs"]
mod gps;

#[path = "breed_contracts/asp.rs"]
mod asp;

#[path = "breed_contracts/abductive_lp.rs"]
mod abductive_lp;

#[path = "breed_contracts/tableaux.rs"]
mod tableaux;

#[path = "breed_contracts/prolog.rs"]
mod prolog;

#[path = "breed_contracts/clp.rs"]
mod clp;

#[path = "breed_contracts/sat_cdcl.rs"]
mod sat_cdcl;

#[path = "breed_contracts/csp_ac3.rs"]
mod csp_ac3;

#[path = "breed_contracts/default_logic.rs"]
mod default_logic;

#[path = "breed_contracts/circumscription.rs"]
mod circumscription;

#[path = "breed_contracts/frames_inheritance.rs"]
mod frames_inheritance;

#[path = "breed_contracts/description_logic.rs"]
mod description_logic;

#[path = "breed_contracts/belief_merging.rs"]
mod belief_merging;

#[path = "breed_contracts/script_sam.rs"]
mod script_sam;

#[path = "breed_contracts/act_r.rs"]
mod act_r;

#[path = "breed_contracts/soar.rs"]
mod soar;

#[path = "breed_contracts/episodic_memory.rs"]
mod episodic_memory;

#[path = "breed_contracts/ebl.rs"]
mod ebl;

#[path = "breed_contracts/ilp.rs"]
mod ilp;

#[path = "breed_contracts/version_space.rs"]
mod version_space;

#[path = "breed_contracts/analogy_sme.rs"]
mod analogy_sme;

#[path = "breed_contracts/rl_symbolic.rs"]
mod rl_symbolic;

#[path = "breed_contracts/qualitative_reason.rs"]
mod qualitative_reason;

#[path = "breed_contracts/naive_physics.rs"]
mod naive_physics;

#[path = "breed_contracts/triz.rs"]
mod triz;

#[path = "breed_contracts/morphological.rs"]
mod morphological;

#[path = "breed_contracts/construction_grammar.rs"]
mod construction_grammar;

#[path = "breed_contracts/meta_reasoning.rs"]
mod meta_reasoning;

#[path = "breed_contracts/autoinstinct_learning.rs"]
mod autoinstinct_learning;

#[path = "breed_contracts/autoinstinct_neurosis.rs"]
mod autoinstinct_neurosis;

#[path = "breed_contracts/autoinstinct_semantics.rs"]
mod autoinstinct_semantics;

#[path = "breed_contracts/autoinstinct_vision.rs"]
mod autoinstinct_vision;

#[path = "breed_contracts/cbr.rs"]
mod cbr;

#[path = "breed_contracts/dendral.rs"]
mod dendral;

#[path = "breed_contracts/eliza.rs"]
mod eliza;

#[path = "breed_contracts/hearsay.rs"]
mod hearsay;

#[path = "breed_contracts/mycin.rs"]
mod mycin;

#[path = "breed_contracts/ocpm_route_discoverer.rs"]
mod ocpm_route_discoverer;

// ---------------------------------------------------------------------------
// Anti-vacuity falsifier: the breed contract pattern must FAIL on a violated
// contract (a check that cannot fail carries no bits). These tests run the
// same structural contract used by every breed module above against synthetic
// sources, proving both the refusal path and the acceptance path.
// ---------------------------------------------------------------------------

/// The structural contract every breed module asserts, as a total function
/// over (source, paper pointers, anti-cheat oracle). Empty = conformant.
fn breed_contract_violations(
    breed: &str,
    source: &str,
    paper_pointers: &str,
    anticheat: &str,
) -> Vec<String> {
    let mut v: Vec<String> = Vec::new();
    if !source.contains("impl CognitionBreed for ") {
        v.push(format!("{breed}: missing CognitionBreed implementation"));
    }
    if !source.contains("fn id(&self) -> BreedId") {
        v.push(format!("{breed}: missing stable BreedId"));
    }
    if !source.contains("fn run(&self") {
        v.push(format!("{breed}: missing runtime path"));
    }
    if !source.contains("fn preconditions(&self") {
        v.push(format!("{breed}: missing admission boundary"));
    }
    if !source.contains("fn postconditions(&self") {
        v.push(format!("{breed}: missing postcondition boundary"));
    }
    if source.contains("unimplemented!") {
        v.push(format!("{breed}: unimplemented macro present"));
    }
    if source.contains("todo!") {
        v.push(format!("{breed}: todo macro present"));
    }
    if !paper_pointers.contains(breed) {
        v.push(format!("{breed}: missing generated paper-pointer oracle"));
    }
    if !anticheat.contains(&format!("anticheat_{breed}_")) {
        v.push(format!("{breed}: missing generated anti-cheat oracle"));
    }
    v
}

const WELL_FORMED_SOURCE: &str = r#"pub struct Fake;
impl CognitionBreed for Fake {
    fn id(&self) -> BreedId { BreedId::Fake }
    fn run(&self, _input: &str) -> Result<String, String> { Ok(String::new()) }
    fn preconditions(&self) -> Vec<Precondition> { vec![] }
    fn postconditions(&self) -> Vec<Postcondition> { vec![] }
}"#;

#[test]
fn falsifier_violated_breed_contract_is_detected() {
    // FALSIFIER: feed a contract with every clause violated; the checker must
    // trip all nine. A surviving falsifier is a harness defect.
    let violated = breed_contract_violations(
        "fake_breed",
        "pub struct Broken; unimplemented!() todo!()",
        "PAPER_POINTERS without the breed name",
        "no anticheat entry here",
    );
    assert_eq!(
        violated.len(),
        9,
        "FALSIFIER SURVIVED: violated breed contract must trip all 9 clauses, got {violated:?}"
    );
    // Anti-anti-vacuity: the same checker must ACCEPT a well-formed source,
    // proving the refusal path is not always-firing.
    let clean = breed_contract_violations(
        "fake_breed",
        WELL_FORMED_SOURCE,
        "index contains fake_breed paper pointer",
        "anticheat_fake_breed_entry_1",
    );
    assert!(
        clean.is_empty(),
        "well-formed source must pass the same contract, got {clean:?}"
    );
}

#[test]
fn every_breed_module_declares_its_contract_test() {
    // The harness itself must remain total: the falsifier above must not be
    // achievable by silently dropping modules. Each breed module file on disk
    // must still be declared in this test binary.
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/breed_contracts");
    let mut undeclared: Vec<String> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&dir) {
        for e in entries.filter_map(|e| e.ok()) {
            let p = e.path();
            if p.extension().map(|x| x == "rs").unwrap_or(false) {
                let name = p.file_name().unwrap().to_string_lossy().to_string();
                let declared = std::fs::read_to_string(
                    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                        .join("tests/breed_contracts.rs"),
                )
                .map(|t| t.contains(&format!("breed_contracts/{name}")))
                .unwrap_or(false);
                if !declared {
                    undeclared.push(name);
                }
            }
        }
    }
    assert!(
        undeclared.is_empty(),
        "breed contract modules on disk but not declared in breed_contracts.rs: {undeclared:?}"
    );
}
