/**
 * wasm4pm tool catalog — 18 MCP tools derived from the O* surface ontology.
 *
 * Source of truth: ontology/core/wasm4pm_surface.ttl
 * Regenerate with: unrdf sync
 *
 * Do not edit this file by hand. Change the ontology, then re-sync.
 */

export const TOOL_COUNT = 18;

export const TOOL_IDS = [
  "analyze_statistics",
  "check_conformance",
  "compare_algorithms",
  "detect_bottlenecks",
  "detect_concept_drift",
  "discover_alpha_plus_plus",
  "discover_dfg",
  "discover_genetic_algorithm",
  "discover_ilp_optimization",
  "discover_oc_petri_net",
  "discover_ocel_dfg_per_type",
  "discover_variants",
  "encode_dfg_as_text",
  "encode_ocel_as_text",
  "extract_case_features",
  "flatten_ocel",
  "get_capability_registry",
  "load_ocel"
] as const;

export type ToolId = typeof TOOL_IDS[number];

export interface ToolSpec {
  label: string;
  tier: 'FastTier' | 'MediumTier' | 'SlowTier';
  inputFormat: string;
  outputFormat: string;
  supportsOCEL: boolean;
  requiresHandle: boolean;
  durationMs: number;
  endpoint: string;
}

export const TOOLS: Record<ToolId, ToolSpec> = {
  analyze_statistics: {
    label: "Analyze Statistics",
    tier: "FastTier",
    inputFormat: "handle",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: true,
    durationMs: 2,
    endpoint: "/mcp/tools/analyze_statistics",
  },
  check_conformance: {
    label: "Check Conformance",
    tier: "MediumTier",
    inputFormat: "xes",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: false,
    durationMs: 8,
    endpoint: "/mcp/tools/check_conformance",
  },
  compare_algorithms: {
    label: "Compare Algorithms",
    tier: "SlowTier",
    inputFormat: "xes",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: false,
    durationMs: 75,
    endpoint: "/mcp/tools/compare_algorithms",
  },
  detect_bottlenecks: {
    label: "Detect Bottlenecks",
    tier: "MediumTier",
    inputFormat: "handle",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: true,
    durationMs: 5,
    endpoint: "/mcp/tools/detect_bottlenecks",
  },
  detect_concept_drift: {
    label: "Detect Concept Drift",
    tier: "MediumTier",
    inputFormat: "handle",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: true,
    durationMs: 6,
    endpoint: "/mcp/tools/detect_concept_drift",
  },
  discover_alpha_plus_plus: {
    label: "Discover Alpha++",
    tier: "MediumTier",
    inputFormat: "xes",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: false,
    durationMs: 5,
    endpoint: "/mcp/tools/discover_alpha_plus_plus",
  },
  discover_dfg: {
    label: "Discover DFG",
    tier: "FastTier",
    inputFormat: "xes",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: false,
    durationMs: 0.5,
    endpoint: "/mcp/tools/discover_dfg",
  },
  discover_genetic_algorithm: {
    label: "Discover Genetic Algorithm",
    tier: "SlowTier",
    inputFormat: "xes",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: false,
    durationMs: 40,
    endpoint: "/mcp/tools/discover_genetic_algorithm",
  },
  discover_ilp_optimization: {
    label: "Discover ILP Optimization",
    tier: "SlowTier",
    inputFormat: "xes",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: false,
    durationMs: 20,
    endpoint: "/mcp/tools/discover_ilp_optimization",
  },
  discover_oc_petri_net: {
    label: "Discover OC Petri Net",
    tier: "SlowTier",
    inputFormat: "handle",
    outputFormat: "json",
    supportsOCEL: true,
    requiresHandle: true,
    durationMs: 50,
    endpoint: "/mcp/tools/discover_oc_petri_net",
  },
  discover_ocel_dfg_per_type: {
    label: "Discover OCEL DFG Per Type",
    tier: "MediumTier",
    inputFormat: "handle",
    outputFormat: "json",
    supportsOCEL: true,
    requiresHandle: true,
    durationMs: 4.5,
    endpoint: "/mcp/tools/discover_ocel_dfg_per_type",
  },
  discover_variants: {
    label: "Discover Variants",
    tier: "FastTier",
    inputFormat: "handle",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: true,
    durationMs: 1,
    endpoint: "/mcp/tools/discover_variants",
  },
  encode_dfg_as_text: {
    label: "Encode DFG as Text",
    tier: "FastTier",
    inputFormat: "handle",
    outputFormat: "text",
    supportsOCEL: false,
    requiresHandle: true,
    durationMs: 0.3,
    endpoint: "/mcp/tools/encode_dfg_as_text",
  },
  encode_ocel_as_text: {
    label: "Encode OCEL as Text",
    tier: "FastTier",
    inputFormat: "handle",
    outputFormat: "text",
    supportsOCEL: true,
    requiresHandle: true,
    durationMs: 0.8,
    endpoint: "/mcp/tools/encode_ocel_as_text",
  },
  extract_case_features: {
    label: "Extract Case Features",
    tier: "MediumTier",
    inputFormat: "handle",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: true,
    durationMs: 7,
    endpoint: "/mcp/tools/extract_case_features",
  },
  flatten_ocel: {
    label: "Flatten OCEL",
    tier: "MediumTier",
    inputFormat: "handle",
    outputFormat: "json",
    supportsOCEL: true,
    requiresHandle: true,
    durationMs: 3,
    endpoint: "/mcp/tools/flatten_ocel",
  },
  get_capability_registry: {
    label: "Get Capability Registry",
    tier: "FastTier",
    inputFormat: "none",
    outputFormat: "json",
    supportsOCEL: false,
    requiresHandle: false,
    durationMs: 0.1,
    endpoint: "/mcp/tools/get_capability_registry",
  },
  load_ocel: {
    label: "Load OCEL",
    tier: "FastTier",
    inputFormat: "ocel2",
    outputFormat: "handle",
    supportsOCEL: true,
    requiresHandle: false,
    durationMs: 1.5,
    endpoint: "/mcp/tools/load_ocel",
  }
};

/**
 * Returns all tools belonging to the given performance tier.
 */
export function getToolsByTier(tier: 'FastTier' | 'MediumTier' | 'SlowTier'): ToolSpec[] {
  return TOOL_IDS.filter((id) => TOOLS[id].tier === tier).map((id) => TOOLS[id]);
}

/**
 * Returns all tools that natively handle Object-Centric Event Logs (OCEL 2.0).
 */
export function getOCELTools(): ToolSpec[] {
  return TOOL_IDS.filter((id) => TOOLS[id].supportsOCEL).map((id) => TOOLS[id]);
}

/**
 * Returns all tools that require a pre-loaded in-process WASM handle.
 * Call load_ocel or discover_dfg first to obtain a handle.
 */
export function getHandleTools(): ToolSpec[] {
  return TOOL_IDS.filter((id) => TOOLS[id].requiresHandle).map((id) => TOOLS[id]);
}

export * from './algorithm-registry.js';
export * from './prediction-tasks.js';
