/**
 * wasm4pm kernel algorithm registry — 15 discovery algorithms.
 *
 * Source of truth: /Users/sac/ostar/plugins/wasm4pm/ontology/surface.ttl (KernelAlgorithm individuals)
 * Regenerate with: unrdf sync  (or: pnpm generate)
 *
 * DO NOT EDIT THIS FILE BY HAND. Change the ontology, then re-sync.
 */

export const ALGORITHM_IDS = [
  'process_skeleton',
  'dfg',
  'alpha_plus_plus',
  'heuristic_miner',
  'inductive_miner',
  'declare',
  'hill_climbing',
  'simulated_annealing',
  'a_star',
  'aco',
  'optimized_dfg',
  'pso',
  'genetic_algorithm',
  'ilp',
  // Wave 1 Discovery
  'transition_system',
  'log_to_trie',
  'causal_graph',
  'performance_spectrum',
  'batches',
  'correlation_miner',
  // Wave 1 Conformance & Quality
  'generalization',
  'petri_net_reduction',
  'etconformance_precision',
  'alignments',
  'complexity_metrics',
  // Wave 1 Import/Export
  'pnml_import',
  'bpmn_import',
  'powl_to_process_tree',
  'yawl_export',
  // Wave 1 Simulation
  'playout',
  'monte_carlo_simulation',
  // ML Analysis
  'ml_classify',
  'ml_cluster',
  'ml_forecast',
  'ml_anomaly',
  'ml_regress',
  'ml_pca',
] as const;

export type AlgorithmId = (typeof ALGORITHM_IDS)[number];

/** Maps kernel registry ID → planner PlanStepType string value */
export const ALGORITHM_ID_TO_STEP_TYPE: Record<string, string> = {
  process_skeleton: 'discover_process_skeleton',
  dfg: 'discover_dfg',
  alpha_plus_plus: 'discover_alpha_plus_plus',
  heuristic_miner: 'discover_heuristic',
  inductive_miner: 'discover_inductive',
  declare: 'discover_declare',
  hill_climbing: 'discover_hill_climbing',
  simulated_annealing: 'discover_simulated_annealing',
  a_star: 'discover_a_star',
  aco: 'discover_aco',
  optimized_dfg: 'discover_optimized_dfg',
  pso: 'discover_pso',
  genetic_algorithm: 'discover_genetic',
  ilp: 'discover_ilp',
  // Wave 1 Discovery
  transition_system: 'discover_transition_system',
  log_to_trie: 'discover_log_to_trie',
  causal_graph: 'discover_causal_graph',
  performance_spectrum: 'discover_performance_spectrum',
  batches: 'discover_batches',
  correlation_miner: 'discover_correlation_miner',
  // Wave 1 Conformance & Quality
  generalization: 'discover_generalization',
  petri_net_reduction: 'discover_petri_net_reduction',
  etconformance_precision: 'discover_etconformance_precision',
  alignment_fitness: 'discover_alignment_fitness',
  alignments: 'discover_alignment_fitness',
  complexity_metrics: 'discover_complexity_metrics',
  // Wave 1 Import/Export
  pnml_import: 'import_pnml',
  bpmn_import: 'import_bpmn',
  powl_to_process_tree: 'convert_powl_to_process_tree',
  yawl_export: 'export_yawl',
  // Wave 1 Simulation
  playout: 'simulate_playout',
  monte_carlo_simulation: 'simulate_monte_carlo',
  // ML Analysis
  ml_classify: 'ml_classify',
  ml_cluster: 'ml_cluster',
  ml_forecast: 'ml_forecast',
  ml_anomaly: 'ml_anomaly',
  ml_regress: 'ml_regress',
  ml_pca: 'ml_pca',
};

/** Maps kernel registry ID → output model type */
export const ALGORITHM_OUTPUT_TYPES: Record<string, string> = {
  process_skeleton: 'dfg',
  dfg: 'dfg',
  alpha_plus_plus: 'petrinet',
  heuristic_miner: 'dfg',
  inductive_miner: 'tree',
  declare: 'declare',
  hill_climbing: 'petrinet',
  simulated_annealing: 'petrinet',
  a_star: 'petrinet',
  aco: 'petrinet',
  optimized_dfg: 'dfg',
  pso: 'petrinet',
  genetic_algorithm: 'petrinet',
  ilp: 'petrinet',
  // Wave 1 Discovery
  transition_system: 'transition_system',
  log_to_trie: 'trie',
  causal_graph: 'causal_graph',
  performance_spectrum: 'performance_spectrum',
  batches: 'batch_report',
  correlation_miner: 'correlation_graph',
  // Wave 1 Conformance & Quality
  generalization: 'tree',
  petri_net_reduction: 'petrinet',
  etconformance_precision: 'conformance_report',
  alignment_fitness: 'alignment_report',
  alignments: 'alignment_report',
  complexity_metrics: 'complexity_report',
  // Wave 1 Import/Export
  pnml_import: 'petrinet',
  bpmn_import: 'process_tree',
  powl_to_process_tree: 'process_tree',
  yawl_export: 'yawl',
  // Wave 1 Simulation
  playout: 'event_log',
  monte_carlo_simulation: 'simulation_report',
  // ML Analysis
  ml_classify: 'ml_result',
  ml_cluster: 'ml_result',
  ml_forecast: 'ml_result',
  ml_anomaly: 'ml_result',
  ml_regress: 'ml_result',
  ml_pca: 'ml_result',
};

/** Maps kernel registry ID → CLI alias for pictl run/compare */
export const ALGORITHM_CLI_ALIASES: Record<string, string> = {
  process_skeleton: 'skeleton',
  dfg: 'dfg',
  alpha_plus_plus: 'alpha',
  heuristic_miner: 'heuristic',
  inductive_miner: 'inductive',
  declare: 'declare',
  hill_climbing: 'hill-climbing',
  simulated_annealing: 'simulated-annealing',
  a_star: 'astar',
  aco: 'ant-colony',
  optimized_dfg: 'dfg-optimized',
  pso: 'pso',
  genetic_algorithm: 'genetic',
  ilp: 'ilp',
  // Wave 1 Discovery
  transition_system: 'transition-system',
  log_to_trie: 'prefix-tree',
  causal_graph: 'causal-graph',
  performance_spectrum: 'perf-spectrum',
  batches: 'batches',
  correlation_miner: 'correlation',
  // Wave 1 Conformance & Quality
  generalization: 'generalization',
  petri_net_reduction: 'reduce-pn',
  etconformance_precision: 'etconformance',
  alignment_fitness: 'alignment',
  alignments: 'alignment',
  complexity_metrics: 'complexity',
  // Wave 1 Import/Export
  pnml_import: 'import-pnml',
  bpmn_import: 'import-bpmn',
  powl_to_process_tree: 'powl-to-tree',
  yawl_export: 'export-yawl',
  // Wave 1 Simulation
  playout: 'playout',
  monte_carlo_simulation: 'montecarlo',
  // ML Analysis
  ml_classify: 'ml-classify',
  ml_cluster: 'ml-cluster',
  ml_forecast: 'ml-forecast',
  ml_anomaly: 'ml-anomaly',
  ml_regress: 'ml-regress',
  ml_pca: 'ml-pca',
};

/** Maps kernel registry ID → display name (from ontology skos:prefLabel) */
export const ALGORITHM_DISPLAY_NAMES: Record<string, string> = {
  process_skeleton: 'Process Skeleton',
  dfg: 'DFG',
  alpha_plus_plus: 'Alpha++',
  heuristic_miner: 'Heuristic Miner',
  inductive_miner: 'Inductive Miner',
  declare: 'Declare',
  hill_climbing: 'Hill Climbing',
  simulated_annealing: 'Simulated Annealing',
  a_star: 'A* Search',
  aco: 'Ant Colony Optimization',
  optimized_dfg: 'Optimized DFG',
  pso: 'Particle Swarm Optimization',
  genetic_algorithm: 'Genetic Algorithm',
  ilp: 'ILP',
  // Wave 1 Discovery
  transition_system: 'Transition System',
  log_to_trie: 'Prefix Tree',
  causal_graph: 'Causal Graph',
  performance_spectrum: 'Performance Spectrum',
  batches: 'Batch Analysis',
  correlation_miner: 'Correlation Miner',
  // Wave 1 Conformance & Quality
  generalization: 'Generalization Metrics',
  petri_net_reduction: 'Petri Net Reduction',
  etconformance_precision: 'ETConformance Precision',
  alignment_fitness: 'Alignment Fitness',
  alignments: 'Alignment Fitness',
  complexity_metrics: 'Complexity Metrics',
  // Wave 1 Import/Export
  pnml_import: 'PNML Import',
  bpmn_import: 'BPMN Import',
  powl_to_process_tree: 'POWL to Process Tree',
  yawl_export: 'YAWL Export',
  // Wave 1 Simulation
  playout: 'Petri Net Playout',
  monte_carlo_simulation: 'Monte Carlo Simulation',
  // ML Analysis
  ml_classify: 'ML Classification',
  ml_cluster: 'ML Clustering',
  ml_forecast: 'ML Forecasting',
  ml_anomaly: 'ML Anomaly Detection',
  ml_regress: 'ML Regression',
  ml_pca: 'ML PCA',
};

/**
 * Returns the primary algorithm IDs for a given execution profile.
 * Profile → algorithm selection derived from wasm4pm:supportedIn ontology triples.
 */
export function getProfileAlgorithms(profile: string): string[] {
  const map: Record<string, string[]> = {
    fast: ['process_skeleton', 'dfg', 'transition_system', 'log_to_trie', 'causal_graph'],
    balanced: [
      'alpha_plus_plus',
      'heuristic_miner',
      'inductive_miner',
      'declare',
      'hill_climbing',
      'performance_spectrum',
      'batches',
      'generalization',
      'etconformance_precision',
    ],
    quality: [
      'simulated_annealing',
      'a_star',
      'aco',
      'optimized_dfg',
      'pso',
      'genetic_algorithm',
      'ilp',
      'alignments',
      'correlation_miner',
      'complexity_metrics',
      'petri_net_reduction',
      'monte_carlo_simulation',
      'playout',
    ],
    stream: ['dfg'],
    ensemble: ['dfg', 'heuristic_miner', 'inductive_miner', 'genetic_algorithm'],
    auto: ['dfg', 'heuristic_miner', 'inductive_miner', 'genetic_algorithm', 'ilp'],
    ml: ['ml_classify', 'ml_cluster', 'ml_forecast', 'ml_anomaly', 'ml_regress', 'ml_pca'],
  };
  return map[profile.toLowerCase()] ?? map['balanced']!;
}
