PREFIX mls: <http://www.w3.org/ns/mls#>
PREFIX schema: <https://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wpm: <urn:wasm4pm:>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?id ?name ?neg_case ?neg_code ?inv_case
WHERE {
  ?algo a mls:Algorithm ;
        rdfs:label ?name .
  FILTER(STRSTARTS(STR(?algo), "urn:wasm4pm:algo_"))
  
  BIND(REPLACE(STR(?algo), "urn:wasm4pm:algo_", "") AS ?id)
  
  OPTIONAL {
    ?algo schema:error ?negNode .
    ?negNode skos:prefLabel ?neg_code .
    BIND(REPLACE(STR(?negNode), "urn:uuid:failure-", "") AS ?neg_case)
  }
  
  OPTIONAL {
    ?algo schema:target ?invNode .
    BIND(REPLACE(STR(?invNode), "urn:uuid:invariant-", "") AS ?inv_case)
  }
}
ORDER BY ?id
