fn main() {
    println!("pub const fn compute_table() -> [[u16; 13]; 13] {{");
    println!("    let mut t = [[0u16; 13]; 13];");
    println!("    let mut x_s = 1; while x_s <= 6 {{");
    println!("    let mut x_e = x_s + 1; while x_e <= 6 {{");
    println!("    let mut y_s = 1; while y_s <= 6 {{");
    println!("    let mut y_e = y_s + 1; while y_e <= 6 {{");
    println!("    let mut z_s = 1; while z_s <= 6 {{");
    println!("    let mut z_e = z_s + 1; while z_e <= 6 {{");
    println!("        let r1 = rel(x_s, x_e, y_s, y_e);");
    println!("        let r2 = rel(y_s, y_e, z_s, z_e);");
    println!("        let r3 = rel(x_s, x_e, z_s, z_e);");
    println!("        t[r1][r2] |= (1 << r3);");
    println!("        z_e += 1; }} z_s += 1; }}");
    println!("        y_e += 1; }} y_s += 1; }}");
    println!("        x_e += 1; }} x_s += 1; }}");
    println!("    t");
    println!("}}");
    println!("const fn rel(s1: i32, e1: i32, s2: i32, e2: i32) -> usize {{");
    println!("    if e1 < s2 {{ 0 }} // p");
    println!("    else if e2 < s1 {{ 1 }} // pi");
    println!("    else if e1 == s2 {{ 2 }} // m");
    println!("    else if e2 == s1 {{ 3 }} // mi");
    println!("    else if s1 < s2 && e1 > s2 && e1 < e2 {{ 4 }} // o");
    println!("    else if s2 < s1 && e2 > s1 && e2 < e1 {{ 5 }} // oi");
    println!("    else if s1 > s2 && e1 < e2 {{ 6 }} // d");
    println!("    else if s1 < s2 && e1 > e2 {{ 7 }} // di");
    println!("    else if s1 == s2 && e1 < e2 {{ 8 }} // s");
    println!("    else if s1 == s2 && e1 > e2 {{ 9 }} // si");
    println!("    else if e1 == e2 && s1 > s2 {{ 10 }} // f");
    println!("    else if e1 == e2 && s1 < s2 {{ 11 }} // fi");
    println!("    else {{ 12 }} // eq");
    println!("}}");
}
