// GENERATED by ggen sync (TICKET-031). Do not hand-edit -- edit the ontology or this template.
export interface ConsolePanelProps {
  stdout: string;
  stderr: string;
  exitCode?: number;
}

export function ConsolePanel({ stdout, stderr, exitCode }: ConsolePanelProps) {
  return (
    <div aria-label="Console" data-testid="console-panel">
      <pre data-testid="console-stdout">{stdout}</pre>
      <pre data-testid="console-stderr">{stderr}</pre>
      {exitCode !== undefined && <p data-testid="console-exit-code">exit {exitCode}</p>}
    </div>
  );
}
