// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/30-capabilities.ttl
// via queries/editor-capabilities.rq (TICKET-031). Do not hand-edit -- edit the ontology.
//
// Generated PORT: 12 capability-derived callback props, one per
// capability/editor/* resource. The Monaco runtime adapter (TICKET-034) implements this
// interface -- this file defines only the typed contract, no Monaco-specific code.

export interface EditorShellProps {
  "editor/apply-deterministic-refactor": () => void; // apply deterministic refactor
  "editor/create-file": () => void; // create file
  "editor/delete-file": () => void; // delete file
  "editor/display-diagnostics": () => void; // display diagnostics
  "editor/display-diff": () => void; // display diff
  "editor/format-source": () => void; // format source
  "editor/inspect-definition": () => void; // inspect definition
  "editor/inspect-references": () => void; // inspect references
  "editor/modify-file": () => void; // modify file
  "editor/navigate-symbol": () => void; // navigate symbol
  "editor/open-file": () => void; // open file
  "editor/rename-file": () => void; // rename file
}

export const EDITOR_SHELL_PROP_COUNT = 12;

/** Non-Monaco chrome only -- the editor surface itself is out of scope (TICKET-034). */
export function EditorShell(props: EditorShellProps) {
  const keys = Object.keys(props);
  return (
    <div data-testid="editor-shell" data-capability-count={keys.length}>
      <div role="toolbar" aria-label="Editor actions">
        {keys.map((k) => (
          <button key={k} type="button" onClick={props[k as keyof EditorShellProps]} data-testid={`editor-action-${k}`}>
            {k}
          </button>
        ))}
      </div>
    </div>
  );
}
