// GENERATED by ggen sync (TICKET-030). Do not hand-edit -- edit the ontology or this template.
import type { TrackCandidate } from "../lib/domain/track-candidate";

export interface TrackCandidatePanelProps {
  candidates: TrackCandidate[];
}

/** Renders ranked track candidates, sourced entirely from typed props -- no candidate label or
 * ranking rule is hardcoded here. */
export function TrackCandidatePanel({ candidates }: TrackCandidatePanelProps) {
  const ranked = [...candidates].sort((a, b) => a.rank - b.rank);
  return (
    <ul aria-label="Track candidates" data-testid="track-candidate-panel">
      {ranked.map((c) => (
        <li key={c.id} data-testid={`track-candidate-${c.id}`}>
          #{c.rank} {c.id}
        </li>
      ))}
    </ul>
  );
}
