// Breed IDs — generated from wasm4pm-compat ontology. Source of truth for TypeScript consumers.
// import from this file; schemas.ts uses z.enum(BREED_IDS).

export const BREED_IDS = [
  "abductive_ibe",
  "abductive_lp",
  "act_r",
  "allen_temporal",
  "analogy_sme",
  "asp",
  "autoinstinct_learning",
  "autoinstinct_neurosis",
  "autoinstinct_semantics",
  "autoinstinct_vision",
  "bayesian_network",
  "belief_merging",
  "cbr",
  "circumscription",
  "clp",
  "construction_grammar",
  "contingent_plan",
  "csp_ac3",
  "ctl_check",
  "default_logic",
  "dempster_shafer",
  "dendral",
  "description_logic",
  "ebl",
  "eliza",
  "episodic_memory",
  "event_calculus",
  "frames_inheritance",
  "fuzzy_logic",
  "gps",
  "hearsay",
  "htn_planning",
  "ilp",
  "ltl_monitor",
  "markov_logic",
  "mdp",
  "meta_reasoning",
  "morphological",
  "mycin",
  "naive_physics",
  "ocpm_route_discoverer",
  "partial_order_plan",
  "pomdp",
  "problog",
  "prolog",
  "qualitative_reason",
  "rl_symbolic",
  "sat_cdcl",
  "script_sam",
  "situation_calculus",
  "soar",
  "strips",
  "tableaux",
  "triz",
  "version_space",
] as const;

export type BreedId = typeof BREED_IDS[number];

export const PARTIAL_ALIVE_BREED_IDS = [
  "abductive_ibe",
  "abductive_lp",
  "act_r",
  "allen_temporal",
  "analogy_sme",
  "asp",
  "autoinstinct_learning",
  "autoinstinct_neurosis",
  "autoinstinct_semantics",
  "autoinstinct_vision",
  "bayesian_network",
  "belief_merging",
  "cbr",
  "circumscription",
  "clp",
  "construction_grammar",
  "contingent_plan",
  "csp_ac3",
  "ctl_check",
  "default_logic",
  "dempster_shafer",
  "dendral",
  "description_logic",
  "ebl",
  "eliza",
  "episodic_memory",
  "event_calculus",
  "frames_inheritance",
  "fuzzy_logic",
  "gps",
  "hearsay",
  "htn_planning",
  "ilp",
  "ltl_monitor",
  "markov_logic",
  "mdp",
  "meta_reasoning",
  "morphological",
  "mycin",
  "naive_physics",
  "ocpm_route_discoverer",
  "partial_order_plan",
  "pomdp",
  "problog",
  "prolog",
  "qualitative_reason",
  "rl_symbolic",
  "sat_cdcl",
  "script_sam",
  "situation_calculus",
  "soar",
  "strips",
  "tableaux",
  "triz",
  "version_space",
] as const;

export type PartialAliveBreedId = typeof PARTIAL_ALIVE_BREED_IDS[number];