// Algorithm IDs — generated from wasm4pm pi ontology. Regenerate with: ggen sync

export const ALGORITHM_IDS = [
  "agentic_pipeline",
  "alignments",
  "complexity_metrics",
  "etconformance_precision",
  "generalization",
  "a_star",
  "aco",
  "alpha_plus_plus",
  "declare",
  "dfg",
  "genetic_algorithm",
  "heuristic_miner",
  "hierarchical_dfg",
  "hill_climbing",
  "ilp",
  "inductive_miner",
  "log_to_trie",
  "optimized_dfg",
  "process_skeleton",
  "pso",
  "simd_streaming_dfg",
  "simulated_annealing",
  "smart_engine",
  "streaming_log",
  "transition_system",
  "analyze_process_speedup",
  "analyze_variant_complexity",
  "batches",
  "causal_graph",
  "compute_activity_transition_matrix",
  "compute_trace_similarity_matrix",
  "correlation_miner",
  "handover_network",
  "performance_spectrum",
  "working_together_network",
  "bpmn_import",
  "pnml_import",
  "powl_to_process_tree",
  "yawl_export",
  "automl_classify",
  "automl_forecast",
  "ml_anomaly",
  "ml_classify",
  "ml_cluster",
  "ml_forecast",
  "ml_pca",
  "ml_regress",
  "ocel_dfg",
  "ocel_dfg_per_type",
  "ocel_encode",
  "ocel_oc_declare",
  "ocel_ocla",
  "ocel_petri_net",
  "compute_ewma",
  "detect_drift",
  "predict_next_activity",
  "predict_outcome",
  "predict_remaining_time",
  "monte_carlo_simulation",
  "playout",
] as const;

export type AlgorithmId = typeof ALGORITHM_IDS[number];

export const CERTIFIED_ALGORITHM_IDS = [
  "agentic_pipeline",
  "alignments",
  "complexity_metrics",
  "etconformance_precision",
  "generalization",
  "a_star",
  "aco",
  "alpha_plus_plus",
  "declare",
  "dfg",
  "genetic_algorithm",
  "heuristic_miner",
  "hierarchical_dfg",
  "hill_climbing",
  "ilp",
  "inductive_miner",
  "log_to_trie",
  "optimized_dfg",
  "process_skeleton",
  "pso",
  "simd_streaming_dfg",
  "simulated_annealing",
  "smart_engine",
  "streaming_log",
  "transition_system",
  "analyze_process_speedup",
  "analyze_variant_complexity",
  "batches",
  "causal_graph",
  "compute_activity_transition_matrix",
  "compute_trace_similarity_matrix",
  "correlation_miner",
  "handover_network",
  "performance_spectrum",
  "working_together_network",
  "bpmn_import",
  "pnml_import",
  "powl_to_process_tree",
  "yawl_export",
  "automl_classify",
  "automl_forecast",
  "ml_anomaly",
  "ml_classify",
  "ml_cluster",
  "ml_forecast",
  "ml_pca",
  "ml_regress",
  "ocel_dfg",
  "ocel_dfg_per_type",
  "ocel_encode",
  "ocel_oc_declare",
  "ocel_ocla",
  "ocel_petri_net",
  "compute_ewma",
  "detect_drift",
  "predict_next_activity",
  "predict_outcome",
  "predict_remaining_time",
  "monte_carlo_simulation",
  "playout",
] as const;

export type CertifiedAlgorithmId = typeof CERTIFIED_ALGORITHM_IDS[number];

// WASM export function names — generated from pi:wasmExport
export const ALGORITHM_WASM_EXPORTS: Record<AlgorithmId, string> = {
  "agentic_pipeline": "run_agentic_pipeline",
  "alignments": "compute_alignments",
  "complexity_metrics": "compute_complexity_metrics",
  "etconformance_precision": "compute_align_etconformance_precision",
  "generalization": "generalization",
  "a_star": "discover_a_star",
  "aco": "discover_aco",
  "alpha_plus_plus": "discover_alpha_plus_plus",
  "declare": "discover_declare",
  "dfg": "discover_dfg",
  "genetic_algorithm": "discover_genetic_algorithm",
  "heuristic_miner": "discover_heuristic_miner",
  "hierarchical_dfg": "discover_hierarchical_dfg",
  "hill_climbing": "discover_hill_climbing",
  "ilp": "discover_ilp_petri_net",
  "inductive_miner": "discover_inductive_miner",
  "log_to_trie": "discover_log_to_trie",
  "optimized_dfg": "discover_dfg",
  "process_skeleton": "discover_process_skeleton",
  "pso": "discover_pso",
  "simd_streaming_dfg": "discover_dfg_simd",
  "simulated_annealing": "discover_simulated_annealing",
  "smart_engine": "discover_smart_engine",
  "streaming_log": "discover_dfg",
  "transition_system": "discover_transition_system",
  "analyze_process_speedup": "analyze_process_speedup",
  "analyze_variant_complexity": "analyze_variant_complexity",
  "batches": "analyze_batches",
  "causal_graph": "compute_causal_graph",
  "compute_activity_transition_matrix": "compute_activity_transition_matrix",
  "compute_trace_similarity_matrix": "compute_trace_similarity_matrix",
  "correlation_miner": "compute_correlation_miner",
  "handover_network": "compute_handover_network",
  "performance_spectrum": "compute_performance_spectrum",
  "working_together_network": "compute_working_together_network",
  "bpmn_import": "read_bpmn",
  "pnml_import": "from_pnml_wasm",
  "powl_to_process_tree": "convert_powl_to_process_tree",
  "yawl_export": "export_yawl",
  "automl_classify": "automl_classify",
  "automl_forecast": "automl_forecast",
  "ml_anomaly": "ml_anomaly",
  "ml_classify": "ml_classify",
  "ml_cluster": "ml_cluster",
  "ml_forecast": "ml_forecast",
  "ml_pca": "ml_pca",
  "ml_regress": "ml_regress",
  "ocel_dfg": "discover_ocel_dfg",
  "ocel_dfg_per_type": "discover_ocel_dfg_per_type",
  "ocel_encode": "encode_ocel",
  "ocel_oc_declare": "discover_ocel_oc_declare",
  "ocel_ocla": "discover_ocel_ocla",
  "ocel_petri_net": "discover_ocel_petri_net",
  "compute_ewma": "compute_ewma",
  "detect_drift": "detect_drift",
  "predict_next_activity": "predict_next_activity",
  "predict_outcome": "predict_outcome",
  "predict_remaining_time": "predict_case_duration",
  "monte_carlo_simulation": "monte_carlo_simulation",
  "playout": "petri_net_playout",
};

// CLI aliases — generated from pi:cliAlias
export const ALGORITHM_CLI_ALIASES: Partial<Record<string, AlgorithmId>> = {
  "alignment": "alignments",
  "complexity": "complexity_metrics",
  "etconformance": "etconformance_precision",
  "generalization": "generalization",
  "astar": "a_star",
  "ant-colony": "aco",
  "alpha": "alpha_plus_plus",
  "declare": "declare",
  "dfg": "dfg",
  "genetic": "genetic_algorithm",
  "heuristic": "heuristic_miner",
  "hill-climbing": "hill_climbing",
  "ilp": "ilp",
  "inductive": "inductive_miner",
  "prefix-tree": "log_to_trie",
  "dfg-optimized": "optimized_dfg",
  "skeleton": "process_skeleton",
  "pso": "pso",
  "simd-dfg": "simd_streaming_dfg",
  "simulated-annealing": "simulated_annealing",
  "transition-system": "transition_system",
  "batches": "batches",
  "causal-graph": "causal_graph",
  "correlation": "correlation_miner",
  "perf-spectrum": "performance_spectrum",
  "import-bpmn": "bpmn_import",
  "import-pnml": "pnml_import",
  "powl-to-tree": "powl_to_process_tree",
  "export-yawl": "yawl_export",
  "ml-anomaly": "ml_anomaly",
  "ml-classify": "ml_classify",
  "ml-cluster": "ml_cluster",
  "ml-forecast": "ml_forecast",
  "ml-pca": "ml_pca",
  "ml-regress": "ml_regress",
  "montecarlo": "monte_carlo_simulation",
  "playout": "playout",
};