// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/50-policy.ttl
// via queries/authority-actions.rq (TICKET-019). Do not hand-edit -- edit the ontology.

export interface AuthorityState {
  "admit"?: boolean; // admit
  "communicate"?: boolean; // communicate
  "execute-code"?: boolean; // execute_code
  "export"?: boolean; // export
  "observe"?: boolean; // observe
  "project"?: boolean; // project
  "record"?: boolean; // record
  "retain"?: boolean; // retain
}

export const AUTHORITY_STATE_FIELD_COUNT = 8;
