// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/30-capabilities.ttl
// via queries/capabilities.rq (TICKET-026). Do not hand-edit -- edit the ontology.

/** 98-member union of every capability/* schema:Action resource. */
export type CapabilityId =
  | "capability/accessibility/augmentative-communication-projection"
  | "capability/accessibility/braille-display-output"
  | "capability/accessibility/caption-driven-operation"
  | "capability/accessibility/configurable-information-density"
  | "capability/accessibility/controllable-audio-retention"
  | "capability/accessibility/controllable-transcript-retention"
  | "capability/accessibility/extended-processing-time-mode"
  | "capability/accessibility/high-contrast-projection"
  | "capability/accessibility/keyboard-only-operation"
  | "capability/accessibility/magnified-single-cue-projection"
  | "capability/accessibility/non-color-dependent-status"
  | "capability/accessibility/reduced-motion-mode"
  | "capability/accessibility/screen-reader-semantic-regions"
  | "capability/accessibility/stable-layout-mode"
  | "capability/accessibility/text-to-speech-projection"
  | "capability/accessibility/zero-motor-input-operation"
  | "capability/cognition/abstain-under-insufficient-evidence"
  | "capability/cognition/classify-question-family"
  | "capability/cognition/construct-answer-scaffold"
  | "capability/cognition/detect-missing-explanation"
  | "capability/cognition/detect-speech-act"
  | "capability/cognition/detect-topic-transition"
  | "capability/cognition/infer-current-debugging-state"
  | "capability/cognition/maintain-parallel-hypotheses"
  | "capability/cognition/mark-concept-covered"
  | "capability/cognition/predict-likely-follow-up"
  | "capability/cognition/preserve-unresolved-residue"
  | "capability/cognition/rank-solution-families"
  | "capability/cognition/retrieve-candidate-evidence"
  | "capability/editor/apply-deterministic-refactor"
  | "capability/editor/create-file"
  | "capability/editor/delete-file"
  | "capability/editor/display-diagnostics"
  | "capability/editor/display-diff"
  | "capability/editor/format-source"
  | "capability/editor/inspect-definition"
  | "capability/editor/inspect-references"
  | "capability/editor/modify-file"
  | "capability/editor/navigate-symbol"
  | "capability/editor/open-file"
  | "capability/editor/rename-file"
  | "capability/governance/authorize-recording"
  | "capability/governance/authorize-retention"
  | "capability/governance/declare-allowed-knowledge-sources"
  | "capability/governance/declare-allowed-sensors"
  | "capability/governance/declare-assistance-policy"
  | "capability/governance/declare-permitted-projections"
  | "capability/governance/declare-prohibited-actions"
  | "capability/governance/produce-policy-receipt"
  | "capability/governance/produce-session-receipt"
  | "capability/governance/revoke-authority"
  | "capability/problem/apply-requirement-delta"
  | "capability/problem/extract-constraints"
  | "capability/problem/identify-input-format"
  | "capability/problem/identify-output-format"
  | "capability/problem/identify-performance-target"
  | "capability/problem/identify-prohibited-operations"
  | "capability/problem/identify-required-function-signature"
  | "capability/problem/load-problem-statement"
  | "capability/problem/parse-examples"
  | "capability/problem/reveal-clarification"
  | "capability/problem/reveal-hidden-condition"
  | "capability/runtime/capture-exit-status"
  | "capability/runtime/capture-standard-error"
  | "capability/runtime/capture-standard-output"
  | "capability/runtime/compile"
  | "capability/runtime/enforce-memory-limit"
  | "capability/runtime/enforce-timeout"
  | "capability/runtime/execute"
  | "capability/runtime/isolate-filesystem"
  | "capability/runtime/isolate-network"
  | "capability/runtime/provide-standard-input"
  | "capability/runtime/reset-environment"
  | "capability/runtime/select-language"
  | "capability/runtime/select-language-version"
  | "capability/runtime/terminate-process"
  | "capability/session/create-session"
  | "capability/session/end-interview"
  | "capability/session/identify-participant-roles"
  | "capability/session/join-session"
  | "capability/session/manage-interview-phases"
  | "capability/session/pause-interview"
  | "capability/session/record-event-provenance"
  | "capability/session/replay-session"
  | "capability/session/start-interview"
  | "capability/verification/calculate-complexity-evidence"
  | "capability/verification/calculate-coverage"
  | "capability/verification/compare-implementations"
  | "capability/verification/detect-nondeterminism"
  | "capability/verification/generate-candidate-test"
  | "capability/verification/generate-property"
  | "capability/verification/mutate-implementation"
  | "capability/verification/replay-execution"
  | "capability/verification/run-complete-test-suite"
  | "capability/verification/run-example"
  | "capability/verification/run-focused-test"
  | "capability/verification/run-hidden-test"
  | "capability/verification/run-visible-test"
;

export const CAPABILITY_IDS: readonly CapabilityId[] = [
  "capability/accessibility/augmentative-communication-projection",
  "capability/accessibility/braille-display-output",
  "capability/accessibility/caption-driven-operation",
  "capability/accessibility/configurable-information-density",
  "capability/accessibility/controllable-audio-retention",
  "capability/accessibility/controllable-transcript-retention",
  "capability/accessibility/extended-processing-time-mode",
  "capability/accessibility/high-contrast-projection",
  "capability/accessibility/keyboard-only-operation",
  "capability/accessibility/magnified-single-cue-projection",
  "capability/accessibility/non-color-dependent-status",
  "capability/accessibility/reduced-motion-mode",
  "capability/accessibility/screen-reader-semantic-regions",
  "capability/accessibility/stable-layout-mode",
  "capability/accessibility/text-to-speech-projection",
  "capability/accessibility/zero-motor-input-operation",
  "capability/cognition/abstain-under-insufficient-evidence",
  "capability/cognition/classify-question-family",
  "capability/cognition/construct-answer-scaffold",
  "capability/cognition/detect-missing-explanation",
  "capability/cognition/detect-speech-act",
  "capability/cognition/detect-topic-transition",
  "capability/cognition/infer-current-debugging-state",
  "capability/cognition/maintain-parallel-hypotheses",
  "capability/cognition/mark-concept-covered",
  "capability/cognition/predict-likely-follow-up",
  "capability/cognition/preserve-unresolved-residue",
  "capability/cognition/rank-solution-families",
  "capability/cognition/retrieve-candidate-evidence",
  "capability/editor/apply-deterministic-refactor",
  "capability/editor/create-file",
  "capability/editor/delete-file",
  "capability/editor/display-diagnostics",
  "capability/editor/display-diff",
  "capability/editor/format-source",
  "capability/editor/inspect-definition",
  "capability/editor/inspect-references",
  "capability/editor/modify-file",
  "capability/editor/navigate-symbol",
  "capability/editor/open-file",
  "capability/editor/rename-file",
  "capability/governance/authorize-recording",
  "capability/governance/authorize-retention",
  "capability/governance/declare-allowed-knowledge-sources",
  "capability/governance/declare-allowed-sensors",
  "capability/governance/declare-assistance-policy",
  "capability/governance/declare-permitted-projections",
  "capability/governance/declare-prohibited-actions",
  "capability/governance/produce-policy-receipt",
  "capability/governance/produce-session-receipt",
  "capability/governance/revoke-authority",
  "capability/problem/apply-requirement-delta",
  "capability/problem/extract-constraints",
  "capability/problem/identify-input-format",
  "capability/problem/identify-output-format",
  "capability/problem/identify-performance-target",
  "capability/problem/identify-prohibited-operations",
  "capability/problem/identify-required-function-signature",
  "capability/problem/load-problem-statement",
  "capability/problem/parse-examples",
  "capability/problem/reveal-clarification",
  "capability/problem/reveal-hidden-condition",
  "capability/runtime/capture-exit-status",
  "capability/runtime/capture-standard-error",
  "capability/runtime/capture-standard-output",
  "capability/runtime/compile",
  "capability/runtime/enforce-memory-limit",
  "capability/runtime/enforce-timeout",
  "capability/runtime/execute",
  "capability/runtime/isolate-filesystem",
  "capability/runtime/isolate-network",
  "capability/runtime/provide-standard-input",
  "capability/runtime/reset-environment",
  "capability/runtime/select-language",
  "capability/runtime/select-language-version",
  "capability/runtime/terminate-process",
  "capability/session/create-session",
  "capability/session/end-interview",
  "capability/session/identify-participant-roles",
  "capability/session/join-session",
  "capability/session/manage-interview-phases",
  "capability/session/pause-interview",
  "capability/session/record-event-provenance",
  "capability/session/replay-session",
  "capability/session/start-interview",
  "capability/verification/calculate-complexity-evidence",
  "capability/verification/calculate-coverage",
  "capability/verification/compare-implementations",
  "capability/verification/detect-nondeterminism",
  "capability/verification/generate-candidate-test",
  "capability/verification/generate-property",
  "capability/verification/mutate-implementation",
  "capability/verification/replay-execution",
  "capability/verification/run-complete-test-suite",
  "capability/verification/run-example",
  "capability/verification/run-focused-test",
  "capability/verification/run-hidden-test",
  "capability/verification/run-visible-test",
] as const;

export const CAPABILITY_COUNT = 98;

/** Minimal per-capability request/response payload convention. */
export interface CapabilityRequest<C extends CapabilityId = CapabilityId> {
  capabilityId: C;
  payload?: Record<string, unknown>;
}

export interface CapabilityResponse<R = unknown> {
  result?: R;
  refusal?: string;
}

export const CAPABILITY_NAMES: Record<CapabilityId, string> = {
  "capability/accessibility/augmentative-communication-projection": "augmentative communication projection",
  "capability/accessibility/braille-display-output": "Braille-display output",
  "capability/accessibility/caption-driven-operation": "caption-driven operation",
  "capability/accessibility/configurable-information-density": "configurable information density",
  "capability/accessibility/controllable-audio-retention": "controllable audio retention",
  "capability/accessibility/controllable-transcript-retention": "controllable transcript retention",
  "capability/accessibility/extended-processing-time-mode": "extended processing-time mode",
  "capability/accessibility/high-contrast-projection": "high-contrast projection",
  "capability/accessibility/keyboard-only-operation": "keyboard-only operation",
  "capability/accessibility/magnified-single-cue-projection": "magnified single-cue projection",
  "capability/accessibility/non-color-dependent-status": "non-color-dependent status",
  "capability/accessibility/reduced-motion-mode": "reduced-motion mode",
  "capability/accessibility/screen-reader-semantic-regions": "screen-reader semantic regions",
  "capability/accessibility/stable-layout-mode": "stable-layout mode",
  "capability/accessibility/text-to-speech-projection": "text-to-speech projection",
  "capability/accessibility/zero-motor-input-operation": "zero-motor-input operation",
  "capability/cognition/abstain-under-insufficient-evidence": "abstain under insufficient evidence",
  "capability/cognition/classify-question-family": "classify question family",
  "capability/cognition/construct-answer-scaffold": "construct answer scaffold",
  "capability/cognition/detect-missing-explanation": "detect missing explanation",
  "capability/cognition/detect-speech-act": "detect speech act",
  "capability/cognition/detect-topic-transition": "detect topic transition",
  "capability/cognition/infer-current-debugging-state": "infer current debugging state",
  "capability/cognition/maintain-parallel-hypotheses": "maintain parallel hypotheses",
  "capability/cognition/mark-concept-covered": "mark concept covered",
  "capability/cognition/predict-likely-follow-up": "predict likely follow-up",
  "capability/cognition/preserve-unresolved-residue": "preserve unresolved residue",
  "capability/cognition/rank-solution-families": "rank solution families",
  "capability/cognition/retrieve-candidate-evidence": "retrieve candidate evidence",
  "capability/editor/apply-deterministic-refactor": "apply deterministic refactor",
  "capability/editor/create-file": "create file",
  "capability/editor/delete-file": "delete file",
  "capability/editor/display-diagnostics": "display diagnostics",
  "capability/editor/display-diff": "display diff",
  "capability/editor/format-source": "format source",
  "capability/editor/inspect-definition": "inspect definition",
  "capability/editor/inspect-references": "inspect references",
  "capability/editor/modify-file": "modify file",
  "capability/editor/navigate-symbol": "navigate symbol",
  "capability/editor/open-file": "open file",
  "capability/editor/rename-file": "rename file",
  "capability/governance/authorize-recording": "authorize recording",
  "capability/governance/authorize-retention": "authorize retention",
  "capability/governance/declare-allowed-knowledge-sources": "declare allowed knowledge sources",
  "capability/governance/declare-allowed-sensors": "declare allowed sensors",
  "capability/governance/declare-assistance-policy": "declare assistance policy",
  "capability/governance/declare-permitted-projections": "declare permitted projections",
  "capability/governance/declare-prohibited-actions": "declare prohibited actions",
  "capability/governance/produce-policy-receipt": "produce policy receipt",
  "capability/governance/produce-session-receipt": "produce session receipt",
  "capability/governance/revoke-authority": "revoke authority",
  "capability/problem/apply-requirement-delta": "apply requirement delta",
  "capability/problem/extract-constraints": "extract constraints",
  "capability/problem/identify-input-format": "identify input format",
  "capability/problem/identify-output-format": "identify output format",
  "capability/problem/identify-performance-target": "identify performance target",
  "capability/problem/identify-prohibited-operations": "identify prohibited operations",
  "capability/problem/identify-required-function-signature": "identify required function signature",
  "capability/problem/load-problem-statement": "load problem statement",
  "capability/problem/parse-examples": "parse examples",
  "capability/problem/reveal-clarification": "reveal clarification",
  "capability/problem/reveal-hidden-condition": "reveal hidden condition",
  "capability/runtime/capture-exit-status": "capture exit status",
  "capability/runtime/capture-standard-error": "capture standard error",
  "capability/runtime/capture-standard-output": "capture standard output",
  "capability/runtime/compile": "compile",
  "capability/runtime/enforce-memory-limit": "enforce memory limit",
  "capability/runtime/enforce-timeout": "enforce timeout",
  "capability/runtime/execute": "execute",
  "capability/runtime/isolate-filesystem": "isolate filesystem",
  "capability/runtime/isolate-network": "isolate network",
  "capability/runtime/provide-standard-input": "provide standard input",
  "capability/runtime/reset-environment": "reset environment",
  "capability/runtime/select-language": "select language",
  "capability/runtime/select-language-version": "select language version",
  "capability/runtime/terminate-process": "terminate process",
  "capability/session/create-session": "create session",
  "capability/session/end-interview": "end interview",
  "capability/session/identify-participant-roles": "identify participant roles",
  "capability/session/join-session": "join session",
  "capability/session/manage-interview-phases": "manage interview phases",
  "capability/session/pause-interview": "pause interview",
  "capability/session/record-event-provenance": "record event provenance",
  "capability/session/replay-session": "replay session",
  "capability/session/start-interview": "start interview",
  "capability/verification/calculate-complexity-evidence": "calculate complexity evidence",
  "capability/verification/calculate-coverage": "calculate coverage",
  "capability/verification/compare-implementations": "compare implementations",
  "capability/verification/detect-nondeterminism": "detect nondeterminism",
  "capability/verification/generate-candidate-test": "generate candidate test",
  "capability/verification/generate-property": "generate property",
  "capability/verification/mutate-implementation": "mutate implementation",
  "capability/verification/replay-execution": "replay execution",
  "capability/verification/run-complete-test-suite": "run complete test suite",
  "capability/verification/run-example": "run example",
  "capability/verification/run-focused-test": "run focused test",
  "capability/verification/run-hidden-test": "run hidden test",
  "capability/verification/run-visible-test": "run visible test",
};
