// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/90-cognition-bridge.ttl
// (Part B) via queries/cognition-pattern-rules.rq. Do not hand-edit -- edit the ontology.
//
// These are the real wasm4pm-cognition Rule{id,premise,conclusion,certainty} objects fed into
// BreedInput.rules for a real cognition_run(breed="eliza") call. Empirically verified this pass
// (see 90-cognition-bridge.ttl's cognition-bridge/empty-rules-fallback and
// cognition-bridge/no-keyword-match-fails-closed): Eliza's real run() only produces an
// interview-relevant response when a non-empty rules array is supplied; an intent matching none
// of these keywords throws a real fail-closed error the caller must catch, not a silent fallback.

/** Mirrors the real wasm4pm-cognition Rust `Rule` struct
 * (crates/wasm4pm-cognition/src/breeds/mod.rs:228-239). `premise` is
 * [KEYWORD, decompPattern] -- see cognition-bridge/rule-contract in the ontology. */
export interface CognitionRule {
  id: string;
  premise: [string, string];
  conclusion: string;
  certainty: number;
}

export const COGNITION_RULES: readonly CognitionRule[] = [
  { id: "two-sum-array", premise: ["ARRAY", "(0)"], conclusion: "Is this a Two Sum-style problem -- finding two values in an array whose sum equals a target?", certainty: 0.8 },
  { id: "two-sum-indices", premise: ["INDICES", "(0)"], conclusion: "Do you need to return the positions (indices) of the two matching numbers?", certainty: 0.7 },
  { id: "two-sum-sum", premise: ["SUM", "(0)"], conclusion: "Is this about finding pairs of numbers whose sum matches a given value?", certainty: 0.7 },
  { id: "two-sum-target", premise: ["TARGET", "(0)"], conclusion: "Are you looking for two numbers that add up to a target value?", certainty: 0.8 },
  { id: "valid-parentheses-balanced", premise: ["BALANCED", "(0)"], conclusion: "Is the goal to determine whether the sequence of brackets is balanced?", certainty: 0.7 },
  { id: "valid-parentheses-brackets", premise: ["BRACKETS", "(0)"], conclusion: "Are you working with matching opening and closing brackets, like (), [], and {}?", certainty: 0.8 },
  { id: "valid-parentheses-parentheses", premise: ["PARENTHESES", "(0)"], conclusion: "Is this about checking whether a string of parentheses is validly matched and nested?", certainty: 0.8 },
  { id: "valid-parentheses-stack", premise: ["STACK", "(0)"], conclusion: "Would a stack -- pushing on an open bracket, popping on a matching close -- fit how you'd solve this?", certainty: 0.7 },
] as const;

export const COGNITION_RULE_COUNT = 8;

/** Every track id this vertical-slice rule set can confirm, one entry per distinct
 * targetTrackId in the query results above. Extend this (and the ontology's Part B) when
 * adding more tracks -- do not special-case additional tracks in TypeScript. */
export const COGNITION_TARGET_TRACKS: readonly string[] = [
  "two-sum",
  "valid-parentheses",
] as const;
