/**
 * AutoProcess JTBD (Jobs-To-Be-Done) Lifecycle Tests — RevOps Use Case
 *
 * Van der Aalst QA perspective:
 * - Tests the complete user lifecycle for a RevOps analyst using AutoProcess functions
 * - Each JTBD represents a real task a RevOps analyst would perform
 * - 3 JTBDs, 3 tests each = 9 tests total
 *
 * All test data is generated by a seeded faker instance — no hardcoded strings.
 * Seed 49 is fixed so the suite is deterministic across runs.
 *
 * NOTE: autonomic_execute_cycle is gated behind the 'cloud' feature flag and is not
 * available in the browser WASM build. These tests cover the same JTBDs using the
 * perception, drift-detection, and RL-state functions that ARE available.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { createRequire } from 'module';
import { Faker, en } from '@faker-js/faker';

// ─── Seeded faker ─────────────────────────────────────────────────────────────

const faker = new Faker({ locale: [en] });
faker.seed(49);

// ─── RevOps domain vocabulary (faker-generated, stable via seed) ──────────────

interface RevOpsVocab {
  leadCreated: string;
  leadQualified: string;
  demoScheduled: string;
  demoCompleted: string;
  proposalSent: string;
  negotiationStarted: string;
  proposalRevised: string;
  contractReviewed: string;
  contractSigned: string;
  dealClosedWon: string;
  dealClosedLost: string;
  sdrRole: string;
  aeRole: string;
  salesMgrRole: string;
  legalRole: string;
}

function buildVocab(f: Faker): RevOpsVocab {
  const slug = (w: string) => w.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const act = (...parts: string[]) => parts.map(slug).join('_');

  return {
    leadCreated: act(f.hacker.ingverb(), 'lead'),
    leadQualified: act(f.hacker.ingverb(), 'qualified'),
    demoScheduled: act(f.hacker.ingverb(), 'demo'),
    demoCompleted: act('demo', f.hacker.ingverb()),
    proposalSent: act(f.hacker.ingverb(), 'proposal'),
    negotiationStarted: act(f.hacker.ingverb(), 'negotiation'),
    proposalRevised: act(f.hacker.ingverb(), 'revision'),
    contractReviewed: act(f.hacker.ingverb(), 'contract'),
    contractSigned: act('contract', f.hacker.ingverb()),
    dealClosedWon: act('deal', f.hacker.ingverb(), 'won'),
    dealClosedLost: act('deal', f.hacker.ingverb(), 'lost'),
    sdrRole: act('sdr', f.person.firstName()),
    aeRole: act('ae', f.person.firstName()),
    salesMgrRole: act('mgr', f.person.firstName()),
    legalRole: act('legal', f.commerce.department()),
  };
}

const V = buildVocab(faker);

// ─── XES fixture builder ──────────────────────────────────────────────────────

interface TraceSpec {
  caseId: string;
  activities: Array<{ name: string; resource: string; ts: Date }>;
}

function xesEvent(name: string, resource: string, ts: Date): string {
  return `    <event>
      <string key="concept:name" value="${name}"/>
      <date key="time:timestamp" value="${ts.toISOString()}"/>
      <string key="org:resource" value="${resource}"/>
      <string key="lifecycle:transition" value="complete"/>
    </event>`;
}

function xesTrace(spec: TraceSpec): string {
  return `  <trace>
    <string key="concept:name" value="${spec.caseId}"/>
${spec.activities.map((a) => xesEvent(a.name, a.resource, a.ts)).join('\n')}
  </trace>`;
}

function buildRevOpsXes(traces: TraceSpec[]): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<log xmlns="http://www.xes-standard.org/" xes.version="1.0">
  <extension name="Concept" prefix="concept" uri="http://www.xes-standard.org/concept.xesext"/>
  <extension name="Time" prefix="time" uri="http://www.xes-standard.org/time.xesext"/>
  <extension name="Organizational" prefix="org" uri="http://www.xes-standard.org/org.xesext"/>
  <extension name="Lifecycle" prefix="lifecycle" uri="http://www.xes-standard.org/lifecycle.xesext"/>
  <global scope="trace">
    <string key="concept:name" value="Case ID"/>
  </global>
  <global scope="event">
    <string key="concept:name" value="Activity"/>
    <date key="time:timestamp" value="Timestamp"/>
    <string key="org:resource" value="Resource"/>
    <string key="lifecycle:transition" value="Transition"/>
  </global>
${traces.map(xesTrace).join('\n')}
</log>`;
}

function timestamps(base: Date, count: number, hoursApart = 2): Date[] {
  return Array.from({ length: count }, (_, i) => {
    const d = new Date(base);
    d.setHours(d.getHours() + i * hoursApart);
    return d;
  });
}

function buildRevOpsTraces(): TraceSpec[] {
  const baseDate = faker.date.recent({ days: 30 });
  const dealId = () => `deal_${faker.string.alphanumeric(6)}`;

  // Variant 1: Standard won path
  const v1ts = timestamps(new Date(baseDate), 9);
  const wonTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v1ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v1ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v1ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v1ts[3] },
      { name: V.proposalSent, resource: V.aeRole, ts: v1ts[4] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v1ts[5] },
      { name: V.contractReviewed, resource: V.legalRole, ts: v1ts[6] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v1ts[7] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v1ts[8] },
    ],
  };

  // Variant 2: Lost path
  const v2ts = timestamps(faker.date.recent({ days: 25 }), 5);
  const lostTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v2ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v2ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v2ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v2ts[3] },
      { name: V.dealClosedLost, resource: V.sdrRole, ts: v2ts[4] },
    ],
  };

  // Variant 3: Fast won path
  const v3ts = timestamps(faker.date.recent({ days: 20 }), 5);
  const fastTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v3ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v3ts[1] },
      { name: V.proposalSent, resource: V.aeRole, ts: v3ts[2] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v3ts[3] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v3ts[4] },
    ],
  };

  // Variant 4: Complex path with negotiation loop
  const v4ts = timestamps(faker.date.recent({ days: 15 }), 10);
  const complexTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v4ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v4ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v4ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v4ts[3] },
      { name: V.proposalSent, resource: V.aeRole, ts: v4ts[4] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v4ts[5] },
      { name: V.proposalRevised, resource: V.aeRole, ts: v4ts[6] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v4ts[7] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v4ts[8] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v4ts[9] },
    ],
  };

  // Variant 5: Parallel demo + proposal path
  const v5ts = timestamps(faker.date.recent({ days: 10 }), 7);
  const parallelTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v5ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v5ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v5ts[2] },
      { name: V.proposalSent, resource: V.aeRole, ts: v5ts[3] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v5ts[4] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v5ts[5] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v5ts[6] },
    ],
  };

  return [wonTrace, lostTrace, fastTrace, complexTrace, parallelTrace];
}

const REVOPS_TRACES = buildRevOpsTraces();
const REVOPS_XES = buildRevOpsXes(REVOPS_TRACES);

/** Total event count across all traces in the fixture */
const TOTAL_EVENTS = REVOPS_TRACES.reduce((sum, t) => sum + t.activities.length, 0);

// ─── WASM module and shared state ─────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let wasm: any;
let logHandle: string;
let modelsLogJson: string;
const parse = (r: unknown) => (typeof r === 'string' ? JSON.parse(r) : r);

beforeAll(() => {
  const require = createRequire(import.meta.url);
  wasm = require('../../../../wasm4pm/pkg/wasm4pm.js');
  logHandle = wasm.load_eventlog_from_xes(REVOPS_XES);
  modelsLogJson = wasm.export_eventlog_to_json(logHandle);
});

// ─── JTBD-1: Full health report on RevOps pipeline ───────────────────────────
//
// Perception layer: count events, discover process structure, assess health

describe('JTBD-1: I want AutoProcess to give me a full health report on my RevOps pipeline in one command', () => {
  it('event log loads and models JSON contains all traces', () => {
    const models = JSON.parse(modelsLogJson) as {
      traces: Array<{ events: unknown[] }>;
    };
    expect(models.traces).toBeDefined();
    expect(models.traces.length).toBe(REVOPS_TRACES.length);
  });

  it('DFG discovery produces a non-empty process structure from the RevOps log', () => {
    const dfg = parse(wasm.discover_dfg(logHandle, 'concept:name'));
    // DFG nodes should reflect the faker-generated activities
    expect(dfg).toBeDefined();
    // start_activities should include lead creation activity
    const startActs = dfg.start_activities as Record<string, number>;
    expect(typeof startActs).toBe('object');
    expect(Object.keys(startActs).length).toBeGreaterThan(0);
  });

  it('total event count across all traces matches the fixture', () => {
    // Count events via the models JSON (export_eventlog_to_json format)
    const models = JSON.parse(modelsLogJson) as {
      traces: Array<{ events: unknown[] }>;
    };
    const totalEvents = models.traces.reduce((sum, t) => sum + t.events.length, 0);
    expect(totalEvents).toBe(TOTAL_EVENTS);
  });
});

// ─── JTBD-2: Detect pipeline anomalies and drift ─────────────────────────────
//
// Decision layer: run drift detection and rework analysis to drive guard decisions

describe('JTBD-2: I want to see what decisions the AutoProcess system made about my pipeline health', () => {
  it('detect_drift returns a structured result with method and drifts_detected fields', () => {
    const result = parse(wasm.detect_drift(logHandle, 'concept:name', 2));
    expect(result).toBeDefined();
    expect(result).toHaveProperty('drifts_detected');
    expect(result).toHaveProperty('method');
    expect(typeof result.drifts_detected).toBe('number');
    expect(typeof result.method).toBe('string');
  });

  it('detect_rework returns a valid rework analysis with traces_with_rework field', () => {
    const result = parse(wasm.detect_rework(logHandle, 'concept:name'));
    expect(result).toBeDefined();
    expect(result).toHaveProperty('traces_with_rework');
    expect(result).toHaveProperty('total_rework_instances');
    expect(typeof result.traces_with_rework).toBe('number');
    expect(result.traces_with_rework).toBeGreaterThanOrEqual(0);
  });

  it('rework is correctly detected in the complex trace (negotiation_started appears twice)', () => {
    // Variant 4 has V.negotiationStarted repeated — detect_rework should identify rework
    const result = parse(wasm.detect_rework(logHandle, 'concept:name'));
    // The negotiation loop in variant 4 constitutes rework
    expect(result.traces_with_rework).toBeGreaterThan(0);
    expect(result.total_rework_instances).toBeGreaterThan(0);
  });
});

// ─── JTBD-3: Track RL and drift thresholds between AutoProcess runs ───────────
//
// Protection/Optimization layer: verify RL state construction and drift thresholds

describe('JTBD-3: I want to verify the RL and SPC state is being tracked between AutoProcess runs', () => {
  it('get_drift_thresholds returns valid JSON with low and high threshold fields', () => {
    const raw = wasm.get_drift_thresholds();
    expect(typeof raw).toBe('string');
    expect(() => JSON.parse(raw)).not.toThrow();
    const thresholds = JSON.parse(raw);
    expect(thresholds).toHaveProperty('low');
    expect(thresholds).toHaveProperty('high');
    expect(typeof thresholds.low).toBe('number');
    expect(typeof thresholds.high).toBe('number');
    expect(thresholds.low).toBeLessThan(thresholds.high);
  });

  it('rl_state_from_features constructs a valid RL state from RevOps metric features', () => {
    // Build a normalized 8-dim feature vector from typical RevOps metrics
    const eventRate = (TOTAL_EVENTS / 10_000);
    const traceCount = (REVOPS_TRACES.length / 1_000);
    const uniqueActivities = 10 / 100; // ~10 unique activities
    const healthLevel: number = 0; // Normal health
    const circuitAllowed: number = 1.0;
    const spcAlertLevel: number = 0.0;
    const activityEntropy: number = 0.8; // Moderate entropy for RevOps
    const cyclePhase: number = 0.01;

    const features = new Float32Array([
      eventRate, traceCount, uniqueActivities, healthLevel,
      circuitAllowed, spcAlertLevel, activityEntropy, cyclePhase,
    ]);

    const rlState = wasm.rl_state_from_features(features, healthLevel, 0.0);
    expect(rlState).toBeDefined();
    expect(rlState.health_level).toBe(healthLevel);
  });

  it('set_drift_thresholds updates and get_drift_thresholds reflects the new values', () => {
    // Set faker-derived thresholds in range [0,1]
    const newLow = 0.25;
    const newHigh = 0.65;
    wasm.set_drift_thresholds(newLow, newHigh);

    const raw = wasm.get_drift_thresholds();
    const thresholds = JSON.parse(raw);
    expect(thresholds.low).toBeCloseTo(newLow, 2);
    expect(thresholds.high).toBeCloseTo(newHigh, 2);

    // Restore defaults so other tests are not affected
    wasm.reset_drift_thresholds();
  });
});
