/**
 * Compare JTBD (Jobs-To-Be-Done) Lifecycle Tests — RevOps Use Case
 *
 * Van der Aalst QA perspective:
 * - Tests the complete user lifecycle for a RevOps analyst comparing discovery algorithms
 * - Each JTBD represents a real task a RevOps analyst would perform
 * - 3 JTBDs, 3 tests each = 9 tests total
 *
 * All test data is generated by a seeded faker instance — no hardcoded strings.
 * Seed 43 is fixed so the suite is deterministic across runs while remaining
 * free of static literals.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { createRequire } from 'module';
import { Faker, en } from '@faker-js/faker';

// ─── Seeded faker ────────────────────────────────────────────────────────────

const faker = new Faker({ locale: [en] });
faker.seed(43);

// ─── RevOps domain vocabulary (faker-generated, stable via seed) ─────────────

interface RevOpsVocab {
  leadCreated: string;
  leadQualified: string;
  demoScheduled: string;
  demoCompleted: string;
  proposalSent: string;
  negotiationStarted: string;
  proposalRevised: string;
  contractReviewed: string;
  contractSigned: string;
  dealClosedWon: string;
  dealClosedLost: string;
  newQualificationStep: string;
  sdrRole: string;
  aeRole: string;
  salesMgrRole: string;
  legalRole: string;
}

function buildVocab(f: Faker): RevOpsVocab {
  const slug = (w: string) => w.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const act = (...parts: string[]) => parts.map(slug).join('_');

  return {
    leadCreated: act(f.hacker.ingverb(), 'lead'),
    leadQualified: act(f.hacker.ingverb(), 'qualified'),
    demoScheduled: act(f.hacker.ingverb(), 'demo'),
    demoCompleted: act('demo', f.hacker.ingverb()),
    proposalSent: act(f.hacker.ingverb(), 'proposal'),
    negotiationStarted: act(f.hacker.ingverb(), 'negotiation'),
    proposalRevised: act(f.hacker.ingverb(), 'revision'),
    contractReviewed: act(f.hacker.ingverb(), 'contract'),
    contractSigned: act('contract', f.hacker.ingverb()),
    dealClosedWon: act('deal', f.hacker.ingverb(), 'won'),
    dealClosedLost: act('deal', f.hacker.ingverb(), 'lost'),
    newQualificationStep: act(f.hacker.ingverb(), 'budget'),
    sdrRole: act('sdr', f.person.firstName()),
    aeRole: act('ae', f.person.firstName()),
    salesMgrRole: act('mgr', f.person.firstName()),
    legalRole: act('legal', f.commerce.department()),
  };
}

const V = buildVocab(faker);

// ─── XES fixture builder ─────────────────────────────────────────────────────

interface TraceSpec {
  caseId: string;
  activities: Array<{ name: string; resource: string; ts: Date }>;
}

function xesEvent(name: string, resource: string, ts: Date): string {
  return `    <event>
      <string key="concept:name" value="${name}"/>
      <date key="time:timestamp" value="${ts.toISOString()}"/>
      <string key="org:resource" value="${resource}"/>
      <string key="lifecycle:transition" value="complete"/>
    </event>`;
}

function xesTrace(spec: TraceSpec): string {
  return `  <trace>
    <string key="concept:name" value="${spec.caseId}"/>
${spec.activities.map((a) => xesEvent(a.name, a.resource, a.ts)).join('\n')}
  </trace>`;
}

function buildRevOpsXes(traces: TraceSpec[]): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<log xmlns="http://www.xes-standard.org/" xes.version="1.0">
  <extension name="Concept" prefix="concept" uri="http://www.xes-standard.org/concept.xesext"/>
  <extension name="Time" prefix="time" uri="http://www.xes-standard.org/time.xesext"/>
  <extension name="Organizational" prefix="org" uri="http://www.xes-standard.org/org.xesext"/>
  <extension name="Lifecycle" prefix="lifecycle" uri="http://www.xes-standard.org/lifecycle.xesext"/>
  <global scope="trace">
    <string key="concept:name" value="Case ID"/>
  </global>
  <global scope="event">
    <string key="concept:name" value="Activity"/>
    <date key="time:timestamp" value="Timestamp"/>
    <string key="org:resource" value="Resource"/>
    <string key="lifecycle:transition" value="Transition"/>
  </global>
${traces.map(xesTrace).join('\n')}
</log>`;
}

function timestamps(base: Date, count: number, hoursApart = 2): Date[] {
  return Array.from({ length: count }, (_, i) => {
    const d = new Date(base);
    d.setHours(d.getHours() + i * hoursApart);
    return d;
  });
}

function buildRevOpsTraces(): TraceSpec[] {
  const baseDate = faker.date.recent({ days: 30 });
  const dealId = () => `deal_${faker.string.alphanumeric(6)}`;

  // Variant 1: Standard won path (with demo + contract review)
  const v1base = new Date(baseDate);
  const v1ts = timestamps(v1base, 9);
  const wonTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v1ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v1ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v1ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v1ts[3] },
      { name: V.proposalSent, resource: V.aeRole, ts: v1ts[4] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v1ts[5] },
      { name: V.contractReviewed, resource: V.legalRole, ts: v1ts[6] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v1ts[7] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v1ts[8] },
    ],
  };

  // Variant 2: Lost path (demo but no proposal)
  const v2base = faker.date.recent({ days: 25 });
  const v2ts = timestamps(v2base, 5);
  const lostTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: faker.helpers.arrayElement([V.sdrRole, V.aeRole]), ts: v2ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v2ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v2ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v2ts[3] },
      { name: V.dealClosedLost, resource: V.sdrRole, ts: v2ts[4] },
    ],
  };

  // Variant 3: Fast won path (skip demo)
  const v3base = faker.date.recent({ days: 20 });
  const v3ts = timestamps(v3base, 5);
  const fastTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v3ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v3ts[1] },
      { name: V.proposalSent, resource: V.aeRole, ts: v3ts[2] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v3ts[3] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v3ts[4] },
    ],
  };

  return [wonTrace, lostTrace, fastTrace];
}

const REVOPS_XES = buildRevOpsXes(buildRevOpsTraces());

// ─── Helpers ─────────────────────────────────────────────────────────────────

const parse = (r: unknown): Record<string, unknown> => {
  if (typeof r === 'string') return JSON.parse(r);
  if (r instanceof Map) return Object.fromEntries(r as Map<string, unknown>);
  return r as Record<string, unknown>;
};

// ─── WASM module and shared state ────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let wasm: Record<string, any>;
let logHandle: string;

beforeAll(() => {
  const require = createRequire(import.meta.url);
  wasm = require('../../../../wasm4pm/pkg/wasm4pm.js');
  logHandle = wasm.load_eventlog_from_xes(REVOPS_XES);
});

// ─── JTBD-1: Compare DFG vs Heuristic Miner ─────────────────────────────────

describe('JTBD-1: Compare DFG vs Heuristic Miner to choose the best algorithm for my RevOps log', () => {
  it('DFG result has edges/nodes, heuristic result also has edges/nodes, neither crashes', () => {
    const dfgResult = parse(wasm.discover_dfg(logHandle, 'concept:name'));
    const heuristicResult = parse(wasm.discover_heuristic_miner(logHandle, 'concept:name', 0.5));

    expect(dfgResult).toBeDefined();
    expect(heuristicResult).toBeDefined();

    // DFG must have edges array
    expect(dfgResult.edges ?? dfgResult.nodes).toBeDefined();
    // Heuristic must also return a non-null result
    expect(heuristicResult.edges ?? heuristicResult.nodes).toBeDefined();
  });

  it('both results are parseable — either plain object or valid JSON string', () => {
    const dfgRaw = wasm.discover_dfg(logHandle, 'concept:name');
    const heuristicRaw = wasm.discover_heuristic_miner(logHandle, 'concept:name', 0.5);

    // Must not throw during parse
    expect(() => parse(dfgRaw)).not.toThrow();
    expect(() => parse(heuristicRaw)).not.toThrow();

    const dfgParsed = parse(dfgRaw);
    const heuristicParsed = parse(heuristicRaw);

    // Both must be non-null objects
    expect(typeof dfgParsed).toBe('object');
    expect(dfgParsed).not.toBeNull();
    expect(typeof heuristicParsed).toBe('object');
    expect(heuristicParsed).not.toBeNull();
  });

  it('the two algorithms produce structurally different outputs (DFG has edges, both have non-zero content)', () => {
    const dfgResult = parse(wasm.discover_dfg(logHandle, 'concept:name'));
    const heuristicResult = parse(wasm.discover_heuristic_miner(logHandle, 'concept:name', 0.5));

    // DFG must have an edges key
    expect(dfgResult).toHaveProperty('edges');
    const dfgEdges = dfgResult.edges as unknown[];
    expect(Array.isArray(dfgEdges)).toBe(true);
    expect(dfgEdges.length).toBeGreaterThan(0);

    // Heuristic must produce a non-empty result (has edges or nodes or some structural content)
    const heuristicHasContent =
      (heuristicResult.edges !== undefined && (heuristicResult.edges as unknown[]).length > 0) ||
      (heuristicResult.nodes !== undefined && (heuristicResult.nodes as unknown[]).length > 0) ||
      Object.keys(heuristicResult).length > 0;
    expect(heuristicHasContent).toBe(true);
  });
});

// ─── JTBD-2: Model complexity metrics ────────────────────────────────────────

describe('JTBD-2: Get model complexity metrics to decide which model to use in production', () => {
  it('num_variants is a positive integer', () => {
    const metrics = parse(wasm.compute_model_metrics(logHandle, 'concept:name'));

    expect(typeof metrics.num_variants).toBe('number');
    expect(Number.isInteger(metrics.num_variants as number)).toBe(true);
    expect(metrics.num_variants as number).toBeGreaterThan(0);
  });

  it('density is a number in [0, 1]', () => {
    const metrics = parse(wasm.compute_model_metrics(logHandle, 'concept:name'));

    expect(typeof metrics.density).toBe('number');
    const density = metrics.density as number;
    expect(density).toBeGreaterThanOrEqual(0);
    expect(density).toBeLessThanOrEqual(1);
  });

  it('complexity_score is a non-negative number', () => {
    const metrics = parse(wasm.compute_model_metrics(logHandle, 'concept:name'));

    expect(typeof metrics.complexity_score).toBe('number');
    const score = metrics.complexity_score as number;
    expect(score).toBeGreaterThanOrEqual(0);
    expect(Number.isFinite(score)).toBe(true);
  });
});

// ─── JTBD-3: Run all algorithms and ensure none crash ────────────────────────

describe('JTBD-3: Run all algorithms and ensure none crash on my RevOps log', () => {
  it('discover_inductive_miner completes without throwing', () => {
    expect(() => {
      const result = wasm.discover_inductive_miner(logHandle, 'concept:name');
      expect(result).toBeDefined();
    }).not.toThrow();
  });

  it('discover_alpha_plus_plus returns non-null result', () => {
    const result = wasm.discover_alpha_plus_plus(logHandle, 'concept:name');
    expect(result).toBeDefined();
    expect(result).not.toBeNull();

    const parsed = parse(result);
    expect(parsed).not.toBeNull();
    expect(typeof parsed).toBe('object');
  });

  it('running DFG twice on the same handle returns identical results (determinism)', () => {
    const result1 = parse(wasm.discover_dfg(logHandle, 'concept:name'));
    const result2 = parse(wasm.discover_dfg(logHandle, 'concept:name'));

    // Determinism: same handle, same activity_key → identical edge and node counts
    const edges1 = result1.edges as Array<Record<string, unknown>>;
    const edges2 = result2.edges as Array<Record<string, unknown>>;
    const nodes1 = result1.nodes as Array<Record<string, unknown>>;
    const nodes2 = result2.nodes as Array<Record<string, unknown>>;

    expect(edges1.length).toBe(edges2.length);
    expect(nodes1.length).toBe(nodes2.length);

    // Compare by sorting — JSON key order in maps can vary between calls
    const sortEdges = (arr: Array<Record<string, unknown>>) =>
      [...arr].sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b)));
    const sortNodes = (arr: Array<Record<string, unknown>>) =>
      [...arr].sort((a, b) => String(a.id).localeCompare(String(b.id)));

    expect(JSON.stringify(sortEdges(edges1))).toBe(JSON.stringify(sortEdges(edges2)));
    expect(JSON.stringify(sortNodes(nodes1))).toBe(JSON.stringify(sortNodes(nodes2)));
  });
});
