/**
 * Drift-Watch JTBD (Jobs-To-Be-Done) Lifecycle Tests — RevOps Use Case
 *
 * Van der Aalst QA perspective:
 * - Tests the complete user lifecycle for a RevOps analyst monitoring process drift
 * - Each JTBD represents a real task a RevOps analyst would perform
 * - 3 JTBDs, 3 tests each = 9 tests total
 *
 * All test data is generated by a seeded faker instance — no hardcoded strings.
 * Seed 44 is fixed so the suite is deterministic across runs while remaining
 * free of static literals.
 *
 * Two XES logs are built:
 * - BASELINE_XES: 3 traces following the standard won path
 * - DRIFT_XES: 3 traces where dealClosedLost dominates (win rate collapsed)
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { createRequire } from 'module';
import { Faker, en } from '@faker-js/faker';

// ─── Seeded faker ────────────────────────────────────────────────────────────

const faker = new Faker({ locale: [en] });
faker.seed(44);

// ─── RevOps domain vocabulary (faker-generated, stable via seed) ─────────────

interface RevOpsVocab {
  leadCreated: string;
  leadQualified: string;
  demoScheduled: string;
  demoCompleted: string;
  proposalSent: string;
  negotiationStarted: string;
  proposalRevised: string;
  contractReviewed: string;
  contractSigned: string;
  dealClosedWon: string;
  dealClosedLost: string;
  newQualificationStep: string;
  sdrRole: string;
  aeRole: string;
  salesMgrRole: string;
  legalRole: string;
}

function buildVocab(f: Faker): RevOpsVocab {
  const slug = (w: string) => w.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const act = (...parts: string[]) => parts.map(slug).join('_');

  return {
    leadCreated: act(f.hacker.ingverb(), 'lead'),
    leadQualified: act(f.hacker.ingverb(), 'qualified'),
    demoScheduled: act(f.hacker.ingverb(), 'demo'),
    demoCompleted: act('demo', f.hacker.ingverb()),
    proposalSent: act(f.hacker.ingverb(), 'proposal'),
    negotiationStarted: act(f.hacker.ingverb(), 'negotiation'),
    proposalRevised: act(f.hacker.ingverb(), 'revision'),
    contractReviewed: act(f.hacker.ingverb(), 'contract'),
    contractSigned: act('contract', f.hacker.ingverb()),
    dealClosedWon: act('deal', f.hacker.ingverb(), 'won'),
    dealClosedLost: act('deal', f.hacker.ingverb(), 'lost'),
    newQualificationStep: act(f.hacker.ingverb(), 'budget'),
    sdrRole: act('sdr', f.person.firstName()),
    aeRole: act('ae', f.person.firstName()),
    salesMgrRole: act('mgr', f.person.firstName()),
    legalRole: act('legal', f.commerce.department()),
  };
}

const V = buildVocab(faker);

// ─── XES fixture builder ─────────────────────────────────────────────────────

interface TraceSpec {
  caseId: string;
  activities: Array<{ name: string; resource: string; ts: Date }>;
}

function xesEvent(name: string, resource: string, ts: Date): string {
  return `    <event>
      <string key="concept:name" value="${name}"/>
      <date key="time:timestamp" value="${ts.toISOString()}"/>
      <string key="org:resource" value="${resource}"/>
      <string key="lifecycle:transition" value="complete"/>
    </event>`;
}

function xesTrace(spec: TraceSpec): string {
  return `  <trace>
    <string key="concept:name" value="${spec.caseId}"/>
${spec.activities.map((a) => xesEvent(a.name, a.resource, a.ts)).join('\n')}
  </trace>`;
}

function buildRevOpsXes(traces: TraceSpec[]): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<log xmlns="http://www.xes-standard.org/" xes.version="1.0">
  <extension name="Concept" prefix="concept" uri="http://www.xes-standard.org/concept.xesext"/>
  <extension name="Time" prefix="time" uri="http://www.xes-standard.org/time.xesext"/>
  <extension name="Organizational" prefix="org" uri="http://www.xes-standard.org/org.xesext"/>
  <extension name="Lifecycle" prefix="lifecycle" uri="http://www.xes-standard.org/lifecycle.xesext"/>
  <global scope="trace">
    <string key="concept:name" value="Case ID"/>
  </global>
  <global scope="event">
    <string key="concept:name" value="Activity"/>
    <date key="time:timestamp" value="Timestamp"/>
    <string key="org:resource" value="Resource"/>
    <string key="lifecycle:transition" value="Transition"/>
  </global>
${traces.map(xesTrace).join('\n')}
</log>`;
}

function timestamps(base: Date, count: number, hoursApart = 2): Date[] {
  return Array.from({ length: count }, (_, i) => {
    const d = new Date(base);
    d.setHours(d.getHours() + i * hoursApart);
    return d;
  });
}

// ─── Build BASELINE_XES: 3 traces following standard won path ────────────────

function buildBaselineTraces(): TraceSpec[] {
  const dealId = () => `deal_${faker.string.alphanumeric(6)}`;

  const b1base = faker.date.recent({ days: 30 });
  const b1ts = timestamps(b1base, 5);
  const baseline1: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: b1ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: b1ts[1] },
      { name: V.proposalSent, resource: V.aeRole, ts: b1ts[2] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: b1ts[3] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: b1ts[4] },
    ],
  };

  const b2base = faker.date.recent({ days: 25 });
  const b2ts = timestamps(b2base, 6);
  const baseline2: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: b2ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: b2ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: b2ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: b2ts[3] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: b2ts[4] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: b2ts[5] },
    ],
  };

  const b3base = faker.date.recent({ days: 20 });
  const b3ts = timestamps(b3base, 5);
  const baseline3: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: b3ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: b3ts[1] },
      { name: V.proposalSent, resource: V.aeRole, ts: b3ts[2] },
      { name: V.contractReviewed, resource: V.legalRole, ts: b3ts[3] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: b3ts[4] },
    ],
  };

  return [baseline1, baseline2, baseline3];
}

// ─── Build DRIFT_XES: 3 traces where dealClosedLost dominates ────────────────

function buildDriftTraces(): TraceSpec[] {
  const dealId = () => `deal_${faker.string.alphanumeric(6)}`;

  const d1base = faker.date.recent({ days: 15 });
  const d1ts = timestamps(d1base, 4);
  const drift1: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: d1ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: d1ts[1] },
      { name: V.dealClosedLost, resource: V.sdrRole, ts: d1ts[2] },
      { name: V.dealClosedLost, resource: V.aeRole, ts: d1ts[3] },
    ],
  };

  const d2base = faker.date.recent({ days: 12 });
  const d2ts = timestamps(d2base, 4);
  const drift2: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: d2ts[0] },
      { name: V.dealClosedLost, resource: V.sdrRole, ts: d2ts[1] },
      { name: V.dealClosedLost, resource: V.aeRole, ts: d2ts[2] },
      { name: V.dealClosedLost, resource: V.salesMgrRole, ts: d2ts[3] },
    ],
  };

  const d3base = faker.date.recent({ days: 10 });
  const d3ts = timestamps(d3base, 5);
  const drift3: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: d3ts[0] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: d3ts[1] },
      { name: V.dealClosedLost, resource: V.aeRole, ts: d3ts[2] },
      { name: V.dealClosedLost, resource: V.salesMgrRole, ts: d3ts[3] },
      { name: V.dealClosedLost, resource: V.sdrRole, ts: d3ts[4] },
    ],
  };

  return [drift1, drift2, drift3];
}

const BASELINE_XES = buildRevOpsXes(buildBaselineTraces());
const DRIFT_XES = buildRevOpsXes(buildDriftTraces());

// ─── Helpers ─────────────────────────────────────────────────────────────────

const parse = (r: unknown): Record<string, unknown> => {
  if (typeof r === 'string') return JSON.parse(r);
  if (r instanceof Map) return Object.fromEntries(r as Map<string, unknown>);
  return r as Record<string, unknown>;
};

// ─── WASM module and shared state ────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let wasm: Record<string, any>;
let baselineHandle: string;
let driftHandle: string;

beforeAll(() => {
  const require = createRequire(import.meta.url);
  wasm = require('../../../../wasm4pm/pkg/wasm4pm.js');
  baselineHandle = wasm.load_eventlog_from_xes(BASELINE_XES);
  driftHandle = wasm.load_eventlog_from_xes(DRIFT_XES);
});

// ─── JTBD-1: Detect when close rate suddenly drops ──────────────────────────

describe('JTBD-1: Detect when our close rate suddenly drops', () => {
  it('detect_drift on the drift log returns a drifts array + drifts_detected field is a non-negative integer + window_size field matches what was passed in', () => {
    const windowSize = 2;
    const result = parse(wasm.detect_drift(driftHandle, 'concept:name', windowSize));

    expect(result).toHaveProperty('drifts');
    expect(Array.isArray(result.drifts as unknown[])).toBe(true);

    expect(typeof result.drifts_detected).toBe('number');
    expect(result.drifts_detected as number).toBeGreaterThanOrEqual(0);
    expect(Number.isInteger(result.drifts_detected as number)).toBe(true);

    expect(result.window_size).toBe(windowSize);
  });
});

// ─── JTBD-2: EWMA trend analysis on activity event rates ────────────────────

describe('JTBD-2: EWMA trend analysis on my activity event rates', () => {
  it('compute_ewma on a rising sequence returns smoothed array of length 5 + smoothed values are all finite numbers', () => {
    const result = parse(wasm.compute_ewma('[1.0, 1.0, 1.0, 5.0, 5.0]', 0.3));

    expect(result).toHaveProperty('smoothed');
    const smoothed = result.smoothed as number[];
    expect(Array.isArray(smoothed)).toBe(true);
    expect(smoothed.length).toBe(5);

    for (const v of smoothed) {
      expect(typeof v).toBe('number');
      expect(Number.isFinite(v)).toBe(true);
    }
  });

  it('for a stable sequence, trend is "stable"', () => {
    const result = parse(wasm.compute_ewma('[2.0,2.0,2.0,2.0,2.0]', 0.3));

    expect(result.trend).toBe('stable');
  });
});

// ─── JTBD-3: Transition probability changes to detect behavioral drift ───────

describe('JTBD-3: Transition probability changes to detect behavioral drift', () => {
  it('transition probabilities on baseline log parse as valid JSON object + the start activity appears in the transitions activities list', () => {
    const raw = wasm.build_transition_probabilities(baselineHandle, 'concept:name');

    expect(() => parse(raw)).not.toThrow();
    const result = parse(raw);
    expect(typeof result).toBe('object');
    expect(result).not.toBeNull();
    expect(result).toHaveProperty('edges');

    const activities = result.activities as string[];
    expect(Array.isArray(activities)).toBe(true);
    expect(activities).toContain(V.leadCreated);
  });

  it('probabilities for a given activity in the drift log sum to approximately 1.0 (within 0.01)', () => {
    const result = parse(wasm.build_transition_probabilities(driftHandle, 'concept:name'));
    const edges = result.edges as Array<Record<string, unknown>>;

    expect(Array.isArray(edges)).toBe(true);
    expect(edges.length).toBeGreaterThan(0);

    // Find an activity that appears as source in multiple edges
    const fromMap = new Map<string, number[]>();
    for (const edge of edges) {
      const from = edge.from as string;
      const prob = edge.probability as number;
      if (!fromMap.has(from)) fromMap.set(from, []);
      fromMap.get(from)!.push(prob);
    }

    // For any activity with outgoing edges, probabilities should sum to ~1.0
    let testedAtLeastOne = false;
    for (const [, probs] of fromMap) {
      if (probs.length > 0) {
        const sum = probs.reduce((a, b) => a + b, 0);
        expect(sum).toBeGreaterThan(0);
        expect(sum).toBeLessThanOrEqual(1.01);
        testedAtLeastOne = true;
        break;
      }
    }
    expect(testedAtLeastOne).toBe(true);
  });
});
