/**
 * Explain JTBD (Jobs-To-Be-Done) Lifecycle Tests — RevOps Use Case
 *
 * Van der Aalst QA perspective:
 * - Tests the complete user lifecycle for a RevOps analyst exploring algorithm metadata
 * - Each JTBD represents a real task a RevOps analyst would perform
 * - 3 JTBDs, 3 tests each = 9 tests total
 *
 * All test data is generated by a seeded faker instance — no hardcoded strings.
 * Seed 51 is fixed so the suite is deterministic across runs.
 *
 * Tests operate at the TypeScript module level using @wasm4pm/kernel registry directly.
 */

import { describe, it, expect } from 'vitest';
import { Faker, en } from '@faker-js/faker';
import { getRegistry } from '@wasm4pm/kernel';

// ─── Seeded faker ─────────────────────────────────────────────────────────────

const faker = new Faker({ locale: [en] });
faker.seed(51);

// ─── Registry singleton ───────────────────────────────────────────────────────

const registry = getRegistry();

// ─── JTBD-1: Understand what DFG does before recommending it ─────────────────

describe('JTBD-1: I want to understand what DFG does before recommending it to my RevOps team', () => {
  it('getRegistry().get("dfg") returns non-null metadata + dfg metadata has name, speedTier, and qualityTier fields + dfg metadata.outputType is "dfg"', () => {
    const meta = registry.get('dfg');
    expect(meta).toBeDefined();
    expect(meta).not.toBeNull();

    expect(typeof meta!.name).toBe('string');
    expect(meta!.name.length).toBeGreaterThan(0);
    expect(typeof meta!.speedTier).toBe('number');
    expect(typeof meta!.qualityTier).toBe('number');
    expect(meta!.speedTier).toBeGreaterThanOrEqual(0);
    expect(meta!.qualityTier).toBeGreaterThanOrEqual(0);

    expect(meta!.outputType).toBe('dfg');
  });
});

// ─── JTBD-2: Compare algorithm quality scores ─────────────────────────────────

describe('JTBD-2: I want to compare algorithm quality scores to pick the best for a quality-focused analysis', () => {
  it('genetic_algorithm quality score is greater than dfg quality score + ilp quality score is >= 80 + all registered algorithms have quality score between 0 and 100', () => {
    const dfg = registry.get('dfg')!;
    const genetic = registry.get('genetic_algorithm')!;
    expect(genetic.qualityTier).toBeGreaterThan(dfg.qualityTier);

    const ilp = registry.get('ilp')!;
    expect(ilp.qualityTier).toBeGreaterThanOrEqual(80);

    const allAlgos = registry.list();
    expect(allAlgos.length).toBeGreaterThan(0);
    for (const algo of allAlgos) {
      expect(algo.qualityTier).toBeGreaterThanOrEqual(0);
      expect(algo.qualityTier).toBeLessThanOrEqual(100);
    }
  });
});

// ─── JTBD-3: Understand deployment profile availability ───────────────────────

describe('JTBD-3: I want to understand which algorithms are available for my deployment profile', () => {
  it('getRegistry().getForDeploymentProfile("browser") returns algorithms + getRegistry().getForDeploymentProfile("iot") returns fewer algorithms than browser + faker-generated algorithm name (not real) returns undefined from getRegistry().get()', () => {
    const browserAlgos = registry.getForDeploymentProfile('browser');
    expect(Array.isArray(browserAlgos)).toBe(true);
    expect(browserAlgos.length).toBeGreaterThan(0);

    const iotAlgos = registry.getForDeploymentProfile('iot');
    expect(iotAlgos.length).toBeLessThan(browserAlgos.length);

    // Generate a name that will never match a real algorithm ID
    const fakeAlgoName = `fake_${faker.hacker.ingverb()}_${faker.hacker.noun()}_algo`.toLowerCase().replace(/[^a-z0-9_]/g, '_');
    const result = registry.get(fakeAlgoName);
    expect(result).toBeUndefined();
  });
});
