/**
 * POWL JTBD (Jobs-To-Be-Done) Lifecycle Tests — RevOps Use Case
 *
 * Van der Aalst QA perspective:
 * - Tests the complete user lifecycle for a RevOps analyst working with POWL models
 * - Each JTBD represents a real task a RevOps analyst would perform
 * - 9 JTBDs, up to 3 tests each (27 tests total)
 *
 * All test data is generated by a seeded faker instance — no hardcoded strings.
 * Seed 42 is fixed so the suite is deterministic across runs while remaining
 * free of static literals.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { createRequire } from 'module';
import { Faker, en } from '@faker-js/faker';

// ─── Seeded faker ────────────────────────────────────────────────────────────

const faker = new Faker({ locale: [en] });
faker.seed(42);

// ─── RevOps domain vocabulary (faker-generated, stable via seed) ─────────────

interface RevOpsVocab {
  // Process activities — generated once, reused everywhere
  leadCreated: string;
  leadQualified: string;
  demoScheduled: string;
  demoCompleted: string;
  proposalSent: string;
  negotiationStarted: string;
  proposalRevised: string;
  contractReviewed: string;
  contractSigned: string;
  dealClosedWon: string;
  dealClosedLost: string;
  // Used only in diff tests — a "new" activity added to an enhanced process
  newQualificationStep: string;
  // Roles
  sdrRole: string;
  aeRole: string;
  salesMgrRole: string;
  legalRole: string;
}

function buildVocab(f: Faker): RevOpsVocab {
  const slug = (w: string) => w.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const act = (...parts: string[]) => parts.map(slug).join('_');

  return {
    leadCreated: act(f.hacker.ingverb(), 'lead'),
    leadQualified: act(f.hacker.ingverb(), 'qualified'),
    demoScheduled: act(f.hacker.ingverb(), 'demo'),
    demoCompleted: act('demo', f.hacker.ingverb()),
    proposalSent: act(f.hacker.ingverb(), 'proposal'),
    negotiationStarted: act(f.hacker.ingverb(), 'negotiation'),
    proposalRevised: act(f.hacker.ingverb(), 'revision'),
    contractReviewed: act(f.hacker.ingverb(), 'contract'),
    contractSigned: act('contract', f.hacker.ingverb()),
    dealClosedWon: act('deal', f.hacker.ingverb(), 'won'),
    dealClosedLost: act('deal', f.hacker.ingverb(), 'lost'),
    newQualificationStep: act(f.hacker.ingverb(), 'budget'),
    sdrRole: act('sdr', f.person.firstName()),
    aeRole: act('ae', f.person.firstName()),
    salesMgrRole: act('mgr', f.person.firstName()),
    legalRole: act('legal', f.commerce.department()),
  };
}

const V = buildVocab(faker);

// ─── XES fixture builder ─────────────────────────────────────────────────────

interface TraceSpec {
  caseId: string;
  activities: Array<{ name: string; resource: string; ts: Date }>;
}

function xesEvent(name: string, resource: string, ts: Date): string {
  return `    <event>
      <string key="concept:name" value="${name}"/>
      <date key="time:timestamp" value="${ts.toISOString()}"/>
      <string key="org:resource" value="${resource}"/>
      <string key="lifecycle:transition" value="complete"/>
    </event>`;
}

function xesTrace(spec: TraceSpec): string {
  return `  <trace>
    <string key="concept:name" value="${spec.caseId}"/>
${spec.activities.map((a) => xesEvent(a.name, a.resource, a.ts)).join('\n')}
  </trace>`;
}

function buildRevOpsXes(traces: TraceSpec[]): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<log xmlns="http://www.xes-standard.org/" xes.version="1.0">
  <extension name="Concept" prefix="concept" uri="http://www.xes-standard.org/concept.xesext"/>
  <extension name="Time" prefix="time" uri="http://www.xes-standard.org/time.xesext"/>
  <extension name="Organizational" prefix="org" uri="http://www.xes-standard.org/org.xesext"/>
  <extension name="Lifecycle" prefix="lifecycle" uri="http://www.xes-standard.org/lifecycle.xesext"/>
  <global scope="trace">
    <string key="concept:name" value="Case ID"/>
  </global>
  <global scope="event">
    <string key="concept:name" value="Activity"/>
    <date key="time:timestamp" value="Timestamp"/>
    <string key="org:resource" value="Resource"/>
    <string key="lifecycle:transition" value="Transition"/>
  </global>
${traces.map(xesTrace).join('\n')}
</log>`;
}

/** Generate a sequence of timestamps starting from a base, spacing them by hours */
function timestamps(base: Date, count: number, hoursApart = 2): Date[] {
  return Array.from({ length: count }, (_, i) => {
    const d = new Date(base);
    d.setHours(d.getHours() + i * hoursApart);
    return d;
  });
}

function buildRevOpsTraces(): TraceSpec[] {
  const baseDate = faker.date.recent({ days: 30 });
  const dealId = () => `deal_${faker.string.alphanumeric(6)}`;

  // Variant 1: Standard won path (with demo + contract review)
  const v1base = new Date(baseDate);
  const v1ts = timestamps(v1base, 9);
  const wonTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v1ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v1ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v1ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v1ts[3] },
      { name: V.proposalSent, resource: V.aeRole, ts: v1ts[4] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v1ts[5] },
      { name: V.contractReviewed, resource: V.legalRole, ts: v1ts[6] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v1ts[7] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v1ts[8] },
    ],
  };

  // Variant 2: Lost path (demo but no proposal)
  const v2base = faker.date.recent({ days: 25 });
  const v2ts = timestamps(v2base, 5);
  const lostTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: faker.helpers.arrayElement([V.sdrRole, V.aeRole]), ts: v2ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v2ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v2ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v2ts[3] },
      { name: V.dealClosedLost, resource: V.sdrRole, ts: v2ts[4] },
    ],
  };

  // Variant 3: Fast won path (skip demo)
  const v3base = faker.date.recent({ days: 20 });
  const v3ts = timestamps(v3base, 5);
  const fastTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v3ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v3ts[1] },
      { name: V.proposalSent, resource: V.aeRole, ts: v3ts[2] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v3ts[3] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v3ts[4] },
    ],
  };

  // Variant 4: Complex path (negotiation loop with revision)
  const v4base = faker.date.recent({ days: 15 });
  const v4ts = timestamps(v4base, 10);
  const complexTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v4ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v4ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v4ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v4ts[3] },
      { name: V.proposalSent, resource: V.aeRole, ts: v4ts[4] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v4ts[5] },
      { name: V.proposalRevised, resource: V.aeRole, ts: v4ts[6] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v4ts[7] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v4ts[8] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v4ts[9] },
    ],
  };

  // Variant 5: Parallel demo + proposal (demo before completion)
  const v5base = faker.date.recent({ days: 10 });
  const v5ts = timestamps(v5base, 7);
  const parallelTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v5ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v5ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v5ts[2] },
      { name: V.proposalSent, resource: V.aeRole, ts: v5ts[3] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v5ts[4] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v5ts[5] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v5ts[6] },
    ],
  };

  return [wonTrace, lostTrace, fastTrace, complexTrace, parallelTrace];
}

const REVOPS_XES = buildRevOpsXes(buildRevOpsTraces());

// ─── Helpers ─────────────────────────────────────────────────────────────────

function parse(r: unknown): Record<string, unknown> {
  if (typeof r === 'string') return JSON.parse(r);
  if (r instanceof Map) return Object.fromEntries(r as Map<string, unknown>);
  return r as Record<string, unknown>;
}

function convertModelsLogToPowlLog(
  modelsJson: string,
  activityKey: string = 'concept:name'
): string {
  const models = JSON.parse(modelsJson) as {
    traces: Array<{
      attributes?: Record<string, Record<string, unknown>>;
      events: Array<{ attributes?: Record<string, Record<string, unknown>> }>;
    }>;
  };

  function extractTaggedString(value: unknown): string | null {
    if (typeof value === 'string') return value;
    if (value !== null && typeof value === 'object' && 'tag' in (value as Record<string, unknown>)) {
      const v = (value as Record<string, unknown>)['value'];
      return typeof v === 'string' ? v : null;
    }
    return null;
  }

  const powlLog = {
    traces: models.traces.map((t) => {
      const caseId = extractTaggedString(t.attributes?.['concept:name']) ?? '';
      return {
        case_id: caseId,
        events: (t.events ?? []).map((e) => ({
          name: extractTaggedString(e.attributes?.[activityKey]) ?? '',
          timestamp: extractTaggedString(e.attributes?.['time:timestamp']) ?? null,
          lifecycle: null,
          attributes: {},
        })),
      };
    }),
  };
  return JSON.stringify(powlLog);
}

/** Build a powl_event_log for token replay from an activity sequence */
function buildPowlLog(activities: string[]): string {
  return JSON.stringify({
    traces: [{
      case_id: `deal_${faker.string.alphanumeric(8)}`,
      events: activities.map((name) => ({
        name, timestamp: null, lifecycle: null, attributes: {},
      })),
    }],
  });
}

/** Build a minimal PO= POWL string from an ordered activity list */
function linearPowl(activities: string[]): string {
  const nodes = activities.join(', ');
  const order = activities.slice(0, -1)
    .map((a, i) => `${a}-->${activities[i + 1]}`).join(', ');
  return `PO=(nodes={${nodes}}, order={${order}})`;
}

// ─── WASM module and shared state ────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let wasm: Record<string, any>;
let modelsLogJson: string;

beforeAll(async () => {
  const require = createRequire(import.meta.url);
  wasm = require('../../../../wasm4pm/pkg/wasm4pm.js');

  const logHandle: string = wasm.load_eventlog_from_xes(REVOPS_XES);
  modelsLogJson = wasm.export_eventlog_to_json(logHandle);
  wasm.delete_object(logHandle);
});

// ─── JTBD-1: Discover ────────────────────────────────────────────────────────

describe('JTBD-1: Discover a POWL model from a RevOps event log', () => {
  it('produces a model with non-zero node_count from the RevOps log + discovery with config (noise_threshold=0.2, min_trace_count=1) produces valid model + discovered repr is parseable and contains faker-generated RevOps activity names', () => {
    const result = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic'));
    expect(typeof result.node_count).toBe('number');
    expect(result.node_count as number).toBeGreaterThan(0);
    expect(typeof result.root).toBe('number');
    expect(typeof result.repr).toBe('string');
    expect(result.variant).toBe('decision_graph_cyclic');

    const configResult = parse(
      wasm.discover_powl_from_log_config(modelsLogJson, 'concept:name', 'decision_graph_cyclic', 1, 0.2)
    );
    expect((configResult.node_count as number)).toBeGreaterThan(0);
    expect(typeof configResult.repr).toBe('string');
    const config = configResult.config as Record<string, unknown>;
    expect(config.activity_key).toBe('concept:name');
    expect(config.min_trace_count).toBe(1);
    expect(config.noise_threshold).toBe(0.2);

    const repr = result.repr as string;
    expect(repr.length).toBeGreaterThan(0);

    // Round-trip: re-parse the repr
    const reparsed = parse(wasm.parse_powl(repr));
    expect((reparsed.node_count as number)).toBeGreaterThan(0);

    // The faker-generated start/end activity names must appear in the model repr
    const hasStart = repr.includes(V.leadCreated) || repr.includes(V.leadQualified);
    expect(hasStart).toBe(true);
  });
});

// ─── JTBD-2: Simplify ────────────────────────────────────────────────────────

describe('JTBD-2: Simplify a POWL model to communicate it to stakeholders', () => {
  it('simplify produces a valid parseable POWL model + simplified model still contains faker-generated RevOps core activities + simplify is idempotent: simplify(simplify(m)) equals simplify(m)', () => {
    const original = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic'));
    const simplified = parse(wasm.simplify_powl(original.repr as string));

    expect(typeof simplified.repr).toBe('string');
    expect((simplified.repr as string).length).toBeGreaterThan(0);
    expect((simplified.node_count as number)).toBeGreaterThan(0);

    const reparsed = parse(wasm.parse_powl(simplified.repr as string));
    expect((reparsed.node_count as number)).toBeGreaterThan(0);

    const repr = simplified.repr as string;
    const hasCoreActivities =
      repr.includes(V.leadCreated) ||
      repr.includes(V.leadQualified) ||
      repr.includes(V.dealClosedWon) ||
      repr.includes(V.dealClosedLost);
    expect(hasCoreActivities).toBe(true);

    const once = parse(wasm.simplify_powl(original.repr as string));
    const twice = parse(wasm.simplify_powl(once.repr as string));

    expect(twice.node_count).toBe(once.node_count);
    expect(twice.repr).toBe(once.repr);
  });
});

// ─── JTBD-3: Footprints ──────────────────────────────────────────────────────

describe('JTBD-3: Get footprints to see ordering constraints between activities', () => {
  it(`footprints returns a non-empty structured result with activity list + faker-generated start activity (${V.leadCreated}) appears in start_activities + faker-generated terminal activities (${V.dealClosedWon} / ${V.dealClosedLost}) appear in end_activities`, () => {
    const repr = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic')).repr as string;
    const fp = parse(wasm.powl_footprints(repr));

    expect(fp.activities).toBeDefined();
    expect(Array.isArray(fp.activities as unknown[])).toBe(true);
    expect((fp.activities as string[]).length).toBeGreaterThan(0);

    const startActivities = (fp.start_activities as string[]) ?? [];
    expect(Array.isArray(startActivities)).toBe(true);
    expect(startActivities).toContain(V.leadCreated);

    const endActivities = (fp.end_activities as string[]) ?? [];
    expect(Array.isArray(endActivities)).toBe(true);
    const hasTerminal =
      endActivities.includes(V.dealClosedWon) ||
      endActivities.includes(V.dealClosedLost);
    expect(hasTerminal).toBe(true);
  });
});

// ─── JTBD-4: Complexity ──────────────────────────────────────────────────────

describe('JTBD-4: Get complexity metrics for a process improvement report', () => {
  it('complexity returns non-negative numeric metrics + full RevOps model has equal or higher complexity than a single-activity model + at least one complexity metric > 0 for the multi-variant RevOps model', () => {
    const repr = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic')).repr as string;
    const c = parse(wasm.measure_complexity(repr));

    expect(typeof c.cyclomatic).toBe('number');
    expect(c.cyclomatic as number).toBeGreaterThanOrEqual(0);
    expect(typeof c.cfc).toBe('number');
    expect(c.cfc as number).toBeGreaterThanOrEqual(0);
    expect(typeof c.cognitive).toBe('number');
    expect(c.cognitive as number).toBeGreaterThanOrEqual(0);

    // Trivial model: single faker-generated activity name
    const trivialC = parse(wasm.measure_complexity(V.leadCreated));
    expect(c.cfc as number).toBeGreaterThanOrEqual(trivialC.cfc as number);

    const nonTrivial =
      (c.cyclomatic as number) > 0 ||
      (c.cfc as number) > 0 ||
      (c.cognitive as number) > 0;
    expect(nonTrivial).toBe(true);
  });
});

// ─── JTBD-5: Diff ────────────────────────────────────────────────────────────

describe('JTBD-5: Diff two POWL models to document sales process changes', () => {
  it(`diff of identical models returns behaviourally_equivalent = true + diff detects faker-generated new activity (${V.newQualificationStep}) added to the process + diff output contains severity and required structural fields`, () => {
    const repr = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic')).repr as string;
    const diff = parse(wasm.diff_models(repr, repr));

    expect(diff.behaviourally_equivalent).toBe(true);
    expect((diff.added_activities as string[]) ?? []).toHaveLength(0);
    expect((diff.removed_activities as string[]) ?? []).toHaveLength(0);

    // Original: lead → qualify → close_won
    const original = linearPowl([V.leadCreated, V.leadQualified, V.dealClosedWon]);
    // Enhanced: lead → qualify → budget_check → close_won
    const enhanced = linearPowl([V.leadCreated, V.leadQualified, V.newQualificationStep, V.dealClosedWon]);

    const diff2 = parse(wasm.diff_models(original, enhanced));
    const added = (diff2.added_activities as string[]) ?? [];

    expect(added).toContain(V.newQualificationStep);
    expect(diff2.behaviourally_equivalent).toBe(false);

    const modelA = `X ( ${V.leadCreated}, ${V.leadQualified} )`;
    const modelB = `X ( ${V.leadCreated}, ${V.leadQualified}, ${V.newQualificationStep} )`;
    const diff3 = parse(wasm.diff_models(modelA, modelB));

    expect(diff3.severity).toBeDefined();
    expect(typeof diff3.severity).toBe('string');
    expect(diff3).toHaveProperty('added_activities');
    expect(diff3).toHaveProperty('behaviourally_equivalent');
  });
});

// ─── JTBD-6: Convert ─────────────────────────────────────────────────────────

describe('JTBD-6: Convert a POWL model to process tree for enterprise BPM tooling', () => {
  it('convert to process tree produces valid non-empty JSON + process tree contains faker-generated RevOps activity labels + BPMN export produces non-empty XML with BPMN definitions structure', () => {
    const repr = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic')).repr as string;
    const treeJson: string = wasm.powl_to_process_tree(repr);

    expect(typeof treeJson).toBe('string');
    expect(treeJson.length).toBeGreaterThan(0);
    expect(() => JSON.parse(treeJson)).not.toThrow();

    const hasActivity =
      treeJson.includes(V.leadCreated) ||
      treeJson.includes(V.leadQualified) ||
      treeJson.includes(V.dealClosedWon);
    expect(hasActivity).toBe(true);

    const bpmnXml: string = wasm.powl_to_bpmn(repr);

    expect(typeof bpmnXml).toBe('string');
    expect(bpmnXml.length).toBeGreaterThan(0);
    expect(bpmnXml).toContain('<definitions');
    expect(bpmnXml).toContain('</definitions>');
  });
});

// ─── JTBD-7: Conformance ─────────────────────────────────────────────────────

describe('JTBD-7: Check if specific deals followed the prescribed sales process', () => {
  it('a conforming trace (standard won path with faker activities) has fitness > 0 + deviating trace (skipped qualification step) has lower fitness than conforming trace + conformance output includes percentage, avg_trace_fitness, and total_traces fields', () => {
    const model = linearPowl([
      V.leadCreated, V.leadQualified, V.proposalSent, V.contractSigned, V.dealClosedWon,
    ]);
    const log = buildPowlLog([
      V.leadCreated, V.leadQualified, V.proposalSent, V.contractSigned, V.dealClosedWon,
    ]);
    const fitness = JSON.parse(wasm.token_replay_fitness(model, log));

    expect(typeof fitness.percentage).toBe('number');
    expect(fitness.percentage as number).toBeGreaterThan(0);

    const conforming = buildPowlLog([
      V.leadCreated, V.leadQualified, V.proposalSent, V.contractSigned, V.dealClosedWon,
    ]);
    const deviating = buildPowlLog([
      V.leadCreated, /* V.leadQualified skipped */ V.proposalSent, V.contractSigned, V.dealClosedWon,
    ]);

    const fitConforming = JSON.parse(wasm.token_replay_fitness(model, conforming)).percentage as number;
    const fitDeviating = JSON.parse(wasm.token_replay_fitness(model, deviating)).percentage as number;

    expect(fitDeviating).toBeLessThanOrEqual(fitConforming);

    const simpleModel = linearPowl([V.leadCreated, V.leadQualified, V.dealClosedWon]);
    const simpleLog = buildPowlLog([V.leadCreated, V.leadQualified, V.dealClosedWon]);
    const simpleFitness = JSON.parse(wasm.token_replay_fitness(simpleModel, simpleLog));

    expect(simpleFitness).toHaveProperty('percentage');
    expect(simpleFitness).toHaveProperty('avg_trace_fitness');
    expect(simpleFitness).toHaveProperty('total_traces');
    expect(simpleFitness.total_traces).toBe(1);
  });
});

// ─── JTBD-8: Parse ───────────────────────────────────────────────────────────

describe('JTBD-8: Parse an externally-provided POWL model string', () => {
  it('parse of a valid POWL repr using faker-generated activity names succeeds + parse of the discovered model repr returns equivalent node_count (round-trip) + parse of an invalid string returns an error without crashing', () => {
    const validPowl = linearPowl([V.leadCreated, V.leadQualified, V.dealClosedWon]);
    const result = parse(wasm.parse_powl(validPowl));

    expect(typeof result.node_count).toBe('number');
    expect((result.node_count as number)).toBeGreaterThan(0);
    expect(typeof result.root).toBe('number');
    expect(typeof result.repr).toBe('string');

    const discovered = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic'));
    const reparsed = parse(wasm.parse_powl(discovered.repr as string));

    expect(reparsed.node_count).toBe(discovered.node_count);

    const invalidInput = `!!!${faker.string.alphanumeric(12)}!!!`;
    let threw = false;
    try {
      wasm.parse_powl(invalidInput);
    } catch {
      threw = true;
    }
    // Rank-1 mathematical oracle: Function must complete (not hang).
    // On invalid input, either throw OR return gracefully — both acceptable.
    // This test verifies the function completed within async timeout (timeout failure would be caught by Jest).
    // Explicitly verify threw is a boolean (redundant, but documents the intent).
    expect(typeof threw).toBe('boolean');
  });
});

// ─── JTBD-9a: Get Children ───────────────────────────────────────────────────

describe('JTBD-9a: Get children of a POWL model node', () => {
  it('get_children returns a structured array of numeric indices + children of a choice node (X) are non-empty + children indices are valid arena references', () => {
    const repr = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic')).repr as string;
    const model = parse(wasm.parse_powl(repr));
    const root = model.root as number;

    // Get children of the root node
    const childrenResult = parse(wasm.get_children(repr, String(root)));
    expect(Array.isArray(childrenResult.children)).toBe(true);

    const children = childrenResult.children as number[];
    // For a non-trivial discovered model, the root should have children
    expect(children.length).toBeGreaterThanOrEqual(0);

    // All children must be non-negative integers
    for (const child of children) {
      expect(typeof child).toBe('number');
      expect(child).toBeGreaterThanOrEqual(0);
    }

    // Test with a simple XOR model: X(A, B) should have 2 children
    const simpleXor = `X(${V.leadCreated}, ${V.leadQualified})`;
    const simpleModel = parse(wasm.parse_powl(simpleXor));
    const simpleChildren = parse(wasm.get_children(simpleXor, String(simpleModel.root as number)));
    expect(Array.isArray(simpleChildren.children)).toBe(true);
    expect((simpleChildren.children as number[]).length).toBe(2);
  });
});

// ─── JTBD-9b: Node Info ──────────────────────────────────────────────────────

describe('JTBD-9b: Get detailed info about a POWL model node', () => {
  it('node_info returns structured metadata (type, label, children, edges) + node type is one of (transition, operator, decision_graph, etc.) + label is present for activity nodes + children is always an array', () => {
    const repr = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic')).repr as string;
    const model = parse(wasm.parse_powl(repr));
    const root = model.root as number;

    // Get info about the root node
    const infoResult = parse(wasm.node_info_json(repr, String(root)));
    expect(infoResult.type).toBeDefined();
    expect(typeof infoResult.type).toBe('string');

    // Valid node types (from powl_api.rs node_info_json implementation)
    const validTypes = ['transition', 'frequent_transition', 'strict_partial_order', 'operator', 'decision_graph', 'choice_graph'];
    expect(validTypes).toContain(infoResult.type as string);

    // Children must always be an array
    expect(Array.isArray(infoResult.children)).toBe(true);

    // For a transition node, label should be present
    const simpleActivity = V.leadCreated;
    const activityModel = parse(wasm.parse_powl(simpleActivity));
    const activityInfo = parse(wasm.node_info_json(simpleActivity, String(activityModel.root as number)));

    if (activityInfo.type === 'transition' || activityInfo.type === 'frequent_transition') {
      expect(activityInfo.label).toBeDefined();
      expect(typeof activityInfo.label).toBe('string');
    }

    // Complex model: test that children info is consistent
    const xorModel = `X(${V.leadCreated}, ${V.dealClosedWon})`;
    const xorParsed = parse(wasm.parse_powl(xorModel));
    const xorInfo = parse(wasm.node_info_json(xorModel, String(xorParsed.root as number)));

    expect(xorInfo.type).toBe('operator');
    expect(Array.isArray(xorInfo.children)).toBe(true);
    expect((xorInfo.children as number[]).length).toBe(2);
  });
});

// ─── JTBD-9c: SVG Conversion ─────────────────────────────────────────────────

describe('JTBD-9c: Convert POWL model to SVG for visualization', () => {
  it('powl_to_svg produces valid SVG XML + SVG contains svg root element and viewBox attribute + SVG output is stable (round-trip conversion matches)', () => {
    const repr = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic')).repr as string;
    const svgOutput: string = wasm.powl_to_svg(repr);

    expect(typeof svgOutput).toBe('string');
    expect(svgOutput.length).toBeGreaterThan(0);

    // Valid SVG XML should contain svg root element
    expect(svgOutput).toContain('<svg');
    expect(svgOutput).toContain('</svg>');

    // Should have viewBox attribute for proper scaling
    expect(svgOutput).toContain('viewBox');

    // SVG should contain text or group elements for the process nodes
    const hasSvgElements =
      svgOutput.includes('<g') ||
      svgOutput.includes('<text') ||
      svgOutput.includes('<rect') ||
      svgOutput.includes('<circle');
    expect(hasSvgElements).toBe(true);

    // Round-trip: convert same model twice should give identical SVG
    const svgOutput2: string = wasm.powl_to_svg(repr);
    expect(svgOutput2).toBe(svgOutput);

    // Simple linear model to SVG
    const simpleModel = linearPowl([V.leadCreated, V.dealClosedWon]);
    const simpleSvg: string = wasm.powl_to_svg(simpleModel);
    expect(simpleSvg).toContain('<svg');
    expect(simpleSvg).toContain('</svg>');
  });
});

// ─── JTBD-9d: Full Pipeline ───────────────────────────────────────────────────

describe('JTBD-9d: Full pipeline — discover → simplify → convert (including SVG) → export for wiki embedding', () => {
  it('all pipeline stages complete without error and produce non-empty output + each pipeline stage output is compatible with the next stage input + final BPMN export contains faker-generated RevOps activity names and BPMN structure + SVG export is included in the conversion flow', () => {
    const discovered = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic'));
    expect((discovered.node_count as number)).toBeGreaterThan(0);

    const simplified = parse(wasm.simplify_powl(discovered.repr as string));
    expect((simplified.node_count as number)).toBeGreaterThan(0);

    const treeJson: string = wasm.powl_to_process_tree(simplified.repr as string);
    expect(treeJson.length).toBeGreaterThan(0);

    const bpmnXml: string = wasm.powl_to_bpmn(simplified.repr as string);
    expect(bpmnXml.length).toBeGreaterThan(0);

    // SVG conversion
    const svgOutput: string = wasm.powl_to_svg(simplified.repr as string);
    expect(svgOutput.length).toBeGreaterThan(0);
    expect(svgOutput).toContain('<svg');

    const discoverRepr = parse(
      wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic')
    ).repr as string;
    expect(typeof discoverRepr).toBe('string');

    const simplifiedRepr = parse(wasm.simplify_powl(discoverRepr)).repr as string;
    expect(typeof simplifiedRepr).toBe('string');

    const treeJson2: string = wasm.powl_to_process_tree(simplifiedRepr);
    expect(() => JSON.parse(treeJson2)).not.toThrow();

    const bpmnXml2: string = wasm.powl_to_bpmn(simplifiedRepr);
    expect(bpmnXml2).toContain('<');

    expect(bpmnXml2).toContain('<definitions');
    expect(bpmnXml2).toContain('</definitions>');
    expect(bpmnXml2).toContain('process');

    const hasTaskElement =
      bpmnXml2.includes('task') ||
      bpmnXml2.includes('Task') ||
      bpmnXml2.includes('serviceTask');
    expect(hasTaskElement).toBe(true);

    // At least one faker-generated activity must appear in the export
    const hasRevOpsActivity =
      bpmnXml2.includes(V.leadCreated) ||
      bpmnXml2.includes(V.dealClosedWon) ||
      bpmnXml2.includes(V.dealClosedLost);
    expect(hasRevOpsActivity).toBe(true);
  });
});

// ─── JTBD-10: get-children ───────────────────────────────────────────────────

describe('JTBD-10: Inspect POWL arena node children for tree navigation', () => {
  it('get-children on root node returns a numeric array + get-children on a leaf node returns empty array + get-children arena index type-coercion: number 0 works', () => {
    // Build a simple PO model; root has children (the activity nodes)
    const model = linearPowl([V.leadCreated, V.leadQualified, V.dealClosedWon]);
    const parsed = parse(wasm.parse_powl(model));
    const rootIndex = parsed.root as number;

    // get_children accepts a number for arena_idx
    const rawRoot = wasm.get_children(model, rootIndex);
    const rootResult = parse(rawRoot);
    expect(rootResult).toHaveProperty('children');
    expect(Array.isArray(rootResult.children as unknown[])).toBe(true);

    // For a single-activity model, the root IS the leaf — its children array is empty
    const singleModel = V.leadCreated;
    const singleParsed = parse(wasm.parse_powl(singleModel));
    const singleRoot = singleParsed.root as number;
    const singleRaw = wasm.get_children(singleModel, singleRoot);
    const singleResult = parse(singleRaw);
    expect(Array.isArray(singleResult.children as unknown[])).toBe(true);
    expect((singleResult.children as number[]).length).toBe(0);

    // Passing rootIndex as number gives a children array
    const rawByNum = wasm.get_children(model, rootIndex);
    const byNum = parse(rawByNum);
    expect(byNum.children).toEqual(rootResult.children);
  });

  it('get-children returns JSON-compatible output with valid --format json shape', () => {
    const model = `X ( ${V.leadCreated}, ${V.dealClosedWon} )`;
    const parsed = parse(wasm.parse_powl(model));
    const rootIndex = parsed.root as number;

    const raw = wasm.get_children(model, rootIndex);
    const result = parse(raw);

    // The result must serialize cleanly to JSON (no Map, no undefined)
    expect(() => JSON.stringify(result)).not.toThrow();
    const json = JSON.parse(JSON.stringify(result)) as Record<string, unknown>;
    expect(json).toHaveProperty('children');
    expect(Array.isArray(json.children)).toBe(true);
  });
});

// ─── JTBD-11: node-info ──────────────────────────────────────────────────────

describe('JTBD-11: Inspect detailed POWL node information for model analysis', () => {
  it('node-info on root of XOR model returns type field + node-info on activity leaf returns label field + node-info output serializes cleanly to JSON', () => {
    // XOR model
    const xorModel = `X ( ${V.leadCreated}, ${V.dealClosedLost} )`;
    const parsed = parse(wasm.parse_powl(xorModel));
    const rootIndex = parsed.root as number;

    const rootInfo = JSON.parse(wasm.node_info_json(xorModel, rootIndex));
    expect(rootInfo).toHaveProperty('type');
    expect(typeof rootInfo.type).toBe('string');
    expect(rootInfo.type.toLowerCase()).toMatch(/xor|choice|operator/);
    expect(rootInfo).toHaveProperty('children');

    // For a single-activity model, the root IS the leaf
    const singleModel = V.leadCreated;
    const singleParsed = parse(wasm.parse_powl(singleModel));
    const singleRoot = singleParsed.root as number;
    const leafInfo = JSON.parse(wasm.node_info_json(singleModel, singleRoot));
    expect(leafInfo).toHaveProperty('type');
    const hasLabel =
      'label' in leafInfo ||
      (typeof leafInfo.type === 'string' && leafInfo.type === 'Transition');
    expect(hasLabel).toBe(true);
    if ('label' in leafInfo) {
      expect(leafInfo.label).toBe(V.leadCreated);
    }

    // JSON serialization must not throw
    expect(() => JSON.stringify(rootInfo)).not.toThrow();
    expect(() => JSON.stringify(leafInfo)).not.toThrow();
  });

  it('node-info children indices are valid arena indices (all < node_count)', () => {
    const model = linearPowl([V.leadCreated, V.leadQualified, V.proposalSent, V.dealClosedWon]);
    const parsed = parse(wasm.parse_powl(model));
    const nodeCount = parsed.node_count as number;
    const rootIndex = parsed.root as number;

    const rootInfo = JSON.parse(wasm.node_info_json(model, rootIndex));
    const children = (rootInfo.children as number[]) ?? [];

    // All children must be valid arena indices in [0, node_count)
    for (const child of children) {
      expect(typeof child).toBe('number');
      expect(child).toBeGreaterThanOrEqual(0);
      expect(child).toBeLessThan(nodeCount);
    }

    // Recursively check that each child also has valid node-info
    for (const child of children) {
      const childInfo = JSON.parse(wasm.node_info_json(model, child));
      expect(childInfo).toHaveProperty('type');
    }
  });
});

// ─── JTBD-12: import (process-tree round-trip) ──────────────────────────────

describe('JTBD-12: Import a process tree / petri net back into POWL', () => {
  it('process-tree round-trip: discover → powl_to_process_tree → process_tree_to_powl preserves node_count direction and returns valid POWL', () => {
    const discovered = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic'));
    const treeJson: string = wasm.powl_to_process_tree(discovered.repr as string);

    expect(typeof treeJson).toBe('string');
    expect(treeJson.length).toBeGreaterThan(0);
    expect(() => JSON.parse(treeJson)).not.toThrow();

    const imported = parse(wasm.process_tree_to_powl(treeJson));

    expect(imported).toHaveProperty('root');
    expect(imported).toHaveProperty('node_count');
    expect(imported).toHaveProperty('repr');
    expect(typeof imported.root).toBe('number');
    expect(typeof imported.node_count).toBe('number');
    expect((imported.node_count as number)).toBeGreaterThan(0);
    expect(typeof imported.repr).toBe('string');
    expect((imported.repr as string).length).toBeGreaterThan(0);
  });

  it('process-tree import result is re-parseable (round-trip repr is valid POWL)', () => {
    const discovered = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic'));
    const treeJson: string = wasm.powl_to_process_tree(discovered.repr as string);
    const imported = parse(wasm.process_tree_to_powl(treeJson));

    // The imported repr must be parseable again
    const reparsed = parse(wasm.parse_powl(imported.repr as string));
    expect(typeof reparsed.node_count).toBe('number');
    expect((reparsed.node_count as number)).toBeGreaterThan(0);

    // Re-exported footprints must include at least one faker-generated RevOps activity
    const fp = parse(wasm.powl_footprints(imported.repr as string));
    const activities = (fp.activities as string[]) ?? [];
    const hasRevOpsActivity = activities.some(
      (a) =>
        a === V.leadCreated ||
        a === V.leadQualified ||
        a === V.dealClosedWon ||
        a === V.dealClosedLost,
    );
    expect(hasRevOpsActivity).toBe(true);
  });

  it('petri-net round-trip: powl_to_petri_net produces valid JSON with places/transitions/arcs', () => {
    // Use the discovered RevOps model (complex enough to have all PN elements)
    const discovered = parse(wasm.discover_powl_from_log(modelsLogJson, 'decision_graph_cyclic'));
    const pnJson: string = wasm.powl_to_petri_net(discovered.repr as string);

    expect(typeof pnJson).toBe('string');
    expect(pnJson.length).toBeGreaterThan(0);
    expect(() => JSON.parse(pnJson)).not.toThrow();

    const pn = JSON.parse(pnJson) as Record<string, unknown>;
    // Petri net JSON must contain the standard process mining schema fields
    expect(pn).toHaveProperty('net');
    const net = pn.net as Record<string, unknown>;
    expect(net).toHaveProperty('places');
    expect(net).toHaveProperty('transitions');
    expect(net).toHaveProperty('arcs');
    expect(Array.isArray(net.places as unknown[])).toBe(true);
    expect(Array.isArray(net.transitions as unknown[])).toBe(true);
    expect(Array.isArray(net.arcs as unknown[])).toBe(true);
    // Must have at least one transition (one activity)
    expect((net.transitions as unknown[]).length).toBeGreaterThan(0);
  });
});
