/**
 * Predict JTBD (Jobs-To-Be-Done) Lifecycle Tests — RevOps Use Case
 *
 * Van der Aalst QA perspective:
 * - Tests the complete user lifecycle for a RevOps analyst working with prediction
 * - Each JTBD represents a real task a sales ops analyst would perform
 * - 6 JTBDs, 3 tests each (18 tests total)
 *
 * All test data is generated by a seeded faker instance — no hardcoded strings.
 * Seed 42 is fixed so the suite is deterministic across runs while remaining
 * free of static literals.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { createRequire } from 'module';
import { Faker, en } from '@faker-js/faker';

// ─── Seeded faker ────────────────────────────────────────────────────────────

const faker = new Faker({ locale: [en] });
faker.seed(42);

// ─── RevOps domain vocabulary (faker-generated, stable via seed) ─────────────

interface RevOpsVocab {
  leadCreated: string;
  leadQualified: string;
  demoScheduled: string;
  demoCompleted: string;
  proposalSent: string;
  negotiationStarted: string;
  proposalRevised: string;
  contractReviewed: string;
  contractSigned: string;
  dealClosedWon: string;
  dealClosedLost: string;
  sdrRole: string;
  aeRole: string;
  salesMgrRole: string;
  legalRole: string;
}

function buildVocab(f: Faker): RevOpsVocab {
  const slug = (w: string) => w.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const act = (...parts: string[]) => parts.map(slug).join('_');

  return {
    leadCreated: act(f.hacker.ingverb(), 'lead'),
    leadQualified: act(f.hacker.ingverb(), 'qualified'),
    demoScheduled: act(f.hacker.ingverb(), 'demo'),
    demoCompleted: act('demo', f.hacker.ingverb()),
    proposalSent: act(f.hacker.ingverb(), 'proposal'),
    negotiationStarted: act(f.hacker.ingverb(), 'negotiation'),
    proposalRevised: act(f.hacker.ingverb(), 'revision'),
    contractReviewed: act(f.hacker.ingverb(), 'contract'),
    contractSigned: act('contract', f.hacker.ingverb()),
    dealClosedWon: act('deal', f.hacker.ingverb(), 'won'),
    dealClosedLost: act('deal', f.hacker.ingverb(), 'lost'),
    sdrRole: act('sdr', f.person.firstName()),
    aeRole: act('ae', f.person.firstName()),
    salesMgrRole: act('mgr', f.person.firstName()),
    legalRole: act('legal', f.commerce.department()),
  };
}

const V = buildVocab(faker);
const ACTIVITY_KEY = 'concept:name';

// ─── XES fixture builder ─────────────────────────────────────────────────────

interface TraceSpec {
  caseId: string;
  activities: Array<{ name: string; resource: string; ts: Date }>;
}

function xesEvent(name: string, resource: string, ts: Date): string {
  return `    <event>
      <string key="concept:name" value="${name}"/>
      <date key="time:timestamp" value="${ts.toISOString()}"/>
      <string key="org:resource" value="${resource}"/>
      <string key="lifecycle:transition" value="complete"/>
    </event>`;
}

function xesTrace(spec: TraceSpec): string {
  return `  <trace>
    <string key="concept:name" value="${spec.caseId}"/>
${spec.activities.map((a) => xesEvent(a.name, a.resource, a.ts)).join('\n')}
  </trace>`;
}

function buildRevOpsXes(traces: TraceSpec[]): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<log xmlns="http://www.xes-standard.org/" xes.version="1.0">
  <extension name="Concept" prefix="concept" uri="http://www.xes-standard.org/concept.xesext"/>
  <extension name="Time" prefix="time" uri="http://www.xes-standard.org/time.xesext"/>
  <extension name="Organizational" prefix="org" uri="http://www.xes-standard.org/org.xesext"/>
  <extension name="Lifecycle" prefix="lifecycle" uri="http://www.xes-standard.org/lifecycle.xesext"/>
  <global scope="trace">
    <string key="concept:name" value="Case ID"/>
  </global>
  <global scope="event">
    <string key="concept:name" value="Activity"/>
    <date key="time:timestamp" value="Timestamp"/>
    <string key="org:resource" value="Resource"/>
    <string key="lifecycle:transition" value="Transition"/>
  </global>
${traces.map(xesTrace).join('\n')}
</log>`;
}

/** Generate a sequence of timestamps starting from a base, spacing them by hours */
function timestamps(base: Date, count: number, hoursApart = 2): Date[] {
  return Array.from({ length: count }, (_, i) => {
    const d = new Date(base);
    d.setHours(d.getHours() + i * hoursApart);
    return d;
  });
}

function buildRevOpsTraces(): TraceSpec[] {
  const baseDate = faker.date.recent({ days: 30 });
  const dealId = () => `deal_${faker.string.alphanumeric(6)}`;

  // Variant 1: Standard won path (9 activities)
  const v1base = new Date(baseDate);
  const v1ts = timestamps(v1base, 9);
  const wonTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v1ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v1ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v1ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v1ts[3] },
      { name: V.proposalSent, resource: V.aeRole, ts: v1ts[4] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v1ts[5] },
      { name: V.contractReviewed, resource: V.legalRole, ts: v1ts[6] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v1ts[7] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v1ts[8] },
    ],
  };

  // Variant 2: Lost path (5 activities)
  const v2base = faker.date.recent({ days: 25 });
  const v2ts = timestamps(v2base, 5);
  const lostTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: faker.helpers.arrayElement([V.sdrRole, V.aeRole]), ts: v2ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v2ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v2ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v2ts[3] },
      { name: V.dealClosedLost, resource: V.sdrRole, ts: v2ts[4] },
    ],
  };

  // Variant 3: Fast track won path (4 activities)
  const v3base = faker.date.recent({ days: 20 });
  const v3ts = timestamps(v3base, 4);
  const fastTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v3ts[0] },
      { name: V.proposalSent, resource: V.aeRole, ts: v3ts[1] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v3ts[2] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v3ts[3] },
    ],
  };

  // Variant 4: Rework path (7 activities with proposalRevised)
  const v4base = faker.date.recent({ days: 15 });
  const v4ts = timestamps(v4base, 7);
  const reworkTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v4ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v4ts[1] },
      { name: V.proposalSent, resource: V.aeRole, ts: v4ts[2] },
      { name: V.proposalRevised, resource: V.aeRole, ts: v4ts[3] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v4ts[4] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v4ts[5] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v4ts[6] },
    ],
  };

  // Variant 5: Negotiation path (8 activities with negotiationStarted)
  const v5base = faker.date.recent({ days: 10 });
  const v5ts = timestamps(v5base, 8);
  const negotiationTrace: TraceSpec = {
    caseId: dealId(),
    activities: [
      { name: V.leadCreated, resource: V.sdrRole, ts: v5ts[0] },
      { name: V.leadQualified, resource: V.sdrRole, ts: v5ts[1] },
      { name: V.demoScheduled, resource: V.aeRole, ts: v5ts[2] },
      { name: V.demoCompleted, resource: V.aeRole, ts: v5ts[3] },
      { name: V.proposalSent, resource: V.aeRole, ts: v5ts[4] },
      { name: V.negotiationStarted, resource: V.salesMgrRole, ts: v5ts[5] },
      { name: V.contractSigned, resource: V.salesMgrRole, ts: v5ts[6] },
      { name: V.dealClosedWon, resource: V.salesMgrRole, ts: v5ts[7] },
    ],
  };

  return [wonTrace, lostTrace, fastTrace, reworkTrace, negotiationTrace];
}

const REVOPS_XES = buildRevOpsXes(buildRevOpsTraces());

// ─── Parse helper ────────────────────────────────────────────────────────────

const parse = (r: unknown): Record<string, unknown> => {
  if (typeof r === 'string') return JSON.parse(r) as Record<string, unknown>;
  return r as Record<string, unknown>;
};

// ─── WASM module and shared state ────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let wasm: Record<string, any>;
let logHandle: string;

beforeAll(async () => {
  const require = createRequire(import.meta.url);
  wasm = require('../../../../wasm4pm/pkg/wasm4pm.js');

  logHandle = wasm.load_eventlog_from_xes(REVOPS_XES);
  wasm.export_eventlog_to_json(logHandle); // ensure log is parseable
  // logHandle is kept alive for all tests; cleaned up at end of suite
});

// ─── JTBD-1: Next Activity ────────────────────────────────────────────────────

describe('JTBD-1: I want to predict the next activity so I can proactively assign the right resource', () => {
  it('build_ngram_predictor + predict_next_activity returns a non-empty array', () => {
    const predictorHandle = wasm.build_ngram_predictor(logHandle, ACTIVITY_KEY, 2) as string;
    const candidates = parse(wasm.predict_next_activity(predictorHandle, JSON.stringify([V.leadCreated])));
    wasm.delete_object(predictorHandle);

    expect(Array.isArray(candidates)).toBe(true);
    expect((candidates as unknown as unknown[]).length).toBeGreaterThan(0);
  });

  it('every candidate prediction has activity (string) and probability (0–1)', () => {
    const predictorHandle = wasm.build_ngram_predictor(logHandle, ACTIVITY_KEY, 2) as string;
    const candidates = parse(wasm.predict_next_activity(predictorHandle, JSON.stringify([V.leadCreated]))) as unknown as Array<{activity: string; probability: number}>;
    wasm.delete_object(predictorHandle);

    expect(Array.isArray(candidates)).toBe(true);
    for (const candidate of candidates) {
      expect(typeof candidate.activity).toBe('string');
      expect(candidate.activity.length).toBeGreaterThan(0);
      expect(typeof candidate.probability).toBe('number');
      expect(candidate.probability).toBeGreaterThanOrEqual(0);
      expect(candidate.probability).toBeLessThanOrEqual(1);
    }
  });

  it('top prediction for the start activity is a valid known activity from the vocab', () => {
    const knownActivities = new Set(Object.values(V).filter((v) => !v.startsWith('sdr') && !v.startsWith('ae') && !v.startsWith('mgr') && !v.startsWith('legal')));
    const predictorHandle = wasm.build_ngram_predictor(logHandle, ACTIVITY_KEY, 2) as string;
    const candidates = parse(wasm.predict_next_activity(predictorHandle, JSON.stringify([V.leadCreated]))) as unknown as Array<{activity: string; probability: number}>;
    wasm.delete_object(predictorHandle);

    expect(candidates.length).toBeGreaterThan(0);
    const topActivity = candidates[0].activity;
    expect(knownActivities.has(topActivity)).toBe(true);
  });
});

// ─── JTBD-2: Remaining Time ───────────────────────────────────────────────────

describe('JTBD-2: I want to estimate remaining time so I can set accurate SLA expectations', () => {
  it('build_remaining_time_model + predict_case_duration returns predicted_remaining_ms >= 0', () => {
    const modelHandle = wasm.build_remaining_time_model(logHandle, ACTIVITY_KEY, 'time:timestamp') as string;
    const result = parse(
      wasm.predict_case_duration(modelHandle, JSON.stringify([V.leadCreated]))
    );
    wasm.delete_object(modelHandle);

    const remaining = result['remaining_ms'] as number;
    expect(typeof remaining).toBe('number');
    expect(remaining).toBeGreaterThanOrEqual(0);
  });

  it('predict_case_duration result has a non-empty method field', () => {
    const modelHandle = wasm.build_remaining_time_model(logHandle, ACTIVITY_KEY, 'time:timestamp') as string;
    const result = parse(
      wasm.predict_case_duration(modelHandle, JSON.stringify([V.leadCreated]))
    );
    wasm.delete_object(modelHandle);

    expect(typeof result['method']).toBe('string');
    expect((result['method'] as string).length).toBeGreaterThan(0);
  });

  it('prediction for a longer prefix (3 activities) has a different or equal remaining_ms vs prefix of 1 activity', () => {
    const modelHandle = wasm.build_remaining_time_model(logHandle, ACTIVITY_KEY, 'time:timestamp') as string;
    const shortPrediction = parse(
      wasm.predict_case_duration(modelHandle, JSON.stringify([V.leadCreated]))
    );
    const longPrediction = parse(
      wasm.predict_case_duration(
        modelHandle,
        JSON.stringify([V.leadCreated, V.leadQualified, V.proposalSent])
      )
    );
    wasm.delete_object(modelHandle);

    // Both must return valid numbers — their values may differ as model uses different buckets
    const shortMs = shortPrediction['remaining_ms'] as number;
    const longMs = longPrediction['remaining_ms'] as number;
    expect(typeof shortMs).toBe('number');
    expect(typeof longMs).toBe('number');
    expect(shortMs).toBeGreaterThanOrEqual(0);
    expect(longMs).toBeGreaterThanOrEqual(0);
  });
});

// ─── JTBD-3: Outcome Prediction ───────────────────────────────────────────────

describe('JTBD-3: I want to predict deal outcome to prioritize sales effort', () => {
  it('score_anomaly returns score in [0, 1]', () => {
    const dfgHandle = wasm.discover_dfg_handle(logHandle, ACTIVITY_KEY) as string;
    const result = parse(
      wasm.score_anomaly(dfgHandle, JSON.stringify([V.leadCreated, V.leadQualified]))
    );
    wasm.delete_object(dfgHandle);

    const score = result['score'] as number;
    expect(typeof score).toBe('number');
    expect(score).toBeGreaterThanOrEqual(0);
    expect(score).toBeLessThanOrEqual(1);
  });

  it('score_anomaly result has an is_anomalous boolean field', () => {
    const dfgHandle = wasm.discover_dfg_handle(logHandle, ACTIVITY_KEY) as string;
    const result = parse(
      wasm.score_anomaly(dfgHandle, JSON.stringify([V.leadCreated, V.leadQualified]))
    );
    wasm.delete_object(dfgHandle);

    expect(typeof result['is_anomalous']).toBe('boolean');
  });

  it('score_log_anomalies returns an array (may be empty if no anomalies detected)', () => {
    const dfgHandle = wasm.discover_dfg_handle(logHandle, ACTIVITY_KEY) as string;
    const result = parse(wasm.score_log_anomalies(logHandle, dfgHandle, ACTIVITY_KEY));
    wasm.delete_object(dfgHandle);

    expect(Array.isArray(result)).toBe(true);
  });
});

// ─── JTBD-4: Drift Detection ──────────────────────────────────────────────────

describe('JTBD-4: I want to detect when our sales process is drifting from the standard', () => {
  it('detect_drift result has a drifts array field', () => {
    const result = parse(wasm.detect_drift(logHandle, ACTIVITY_KEY, 2));

    expect(result).toHaveProperty('drifts');
    expect(Array.isArray(result['drifts'])).toBe(true);
  });

  it('detect_drift drifts array length is >= 0 (non-negative)', () => {
    const result = parse(wasm.detect_drift(logHandle, ACTIVITY_KEY, 2));

    const drifts = result['drifts'] as unknown[];
    expect(drifts.length).toBeGreaterThanOrEqual(0);
  });

  it('detect_drift with a larger window (window=50) still returns valid parseable JSON without crashing', () => {
    let threw = false;
    let result: Record<string, unknown> | null = null;
    try {
      result = parse(wasm.detect_drift(logHandle, ACTIVITY_KEY, 50));
    } catch {
      threw = true;
    }

    expect(threw).toBe(false);
    expect(result).not.toBeNull();
    expect(result).toHaveProperty('drifts');
  });
});

// ─── JTBD-5: Feature Extraction ───────────────────────────────────────────────

describe('JTBD-5: I want to extract features from partial cases to feed into ML models', () => {
  it('extract_prefix_features_wasm returns features with prefix_length (length) field = 2', () => {
    const prefix = [V.leadCreated, V.leadQualified];
    const result = parse(wasm.extract_prefix_features_wasm(JSON.stringify(prefix)));

    // The function returns "length" not "prefix_length"
    expect(typeof result['length']).toBe('number');
    expect(result['length'] as number).toBe(2);
  });

  it('extract_prefix_features_wasm returns distinct_activities (unique_activities) field >= 1', () => {
    const prefix = [V.leadCreated, V.leadQualified];
    const result = parse(wasm.extract_prefix_features_wasm(JSON.stringify(prefix)));

    // The function returns "unique_activities"
    expect(typeof result['unique_activities']).toBe('number');
    expect(result['unique_activities'] as number).toBeGreaterThanOrEqual(1);
  });

  it('build_transition_probabilities returns edges array with at least one entry for the start activity', () => {
    const result = parse(wasm.build_transition_probabilities(logHandle, ACTIVITY_KEY));

    expect(result).toHaveProperty('edges');
    const edges = result['edges'] as Array<{from: string; to: string; probability: number; count: number}>;
    expect(Array.isArray(edges)).toBe(true);
    expect(edges.length).toBeGreaterThan(0);

    const startEdges = edges.filter((e) => e.from === V.leadCreated);
    expect(startEdges.length).toBeGreaterThan(0);
  });
});

// ─── JTBD-6: Resource Recommendation ─────────────────────────────────────────

describe('JTBD-6: I want to recommend the optimal resource for the next case step', () => {
  it('estimate_queue_delay returns wait_time >= 0', () => {
    // arrival_rate=1.0, service_rate=2.0 → stable M/M/1 queue
    const result = parse(wasm.estimate_queue_delay(1.0, 2.0));

    const waitTime = result['wait_time'] as number;
    expect(typeof waitTime).toBe('number');
    expect(waitTime).toBeGreaterThanOrEqual(0);
  });

  it('estimate_queue_delay utilization field (utilization) is between 0 and 1 for stable queue', () => {
    // arrival_rate=1.0, service_rate=2.0 → utilization = 0.5
    const result = parse(wasm.estimate_queue_delay(1.0, 2.0));

    const utilization = result['utilization'] as number;
    expect(typeof utilization).toBe('number');
    expect(utilization).toBeGreaterThanOrEqual(0);
    expect(utilization).toBeLessThanOrEqual(1);
  });

  it('build_transition_probabilities returns valid JSON with at least one outgoing edge from the start activity', () => {
    const result = parse(wasm.build_transition_probabilities(logHandle, ACTIVITY_KEY));

    expect(result).toHaveProperty('activities');
    const activities = result['activities'] as string[];
    expect(Array.isArray(activities)).toBe(true);
    expect(activities.length).toBeGreaterThan(0);

    expect(result).toHaveProperty('edges');
    const edges = result['edges'] as Array<{from: string; to: string}>;
    const hasStartEdge = edges.some((e) => e.from === V.leadCreated);
    expect(hasStartEdge).toBe(true);
  });
});
