/**
 * Validation invariant tests for @wasm4pm/planner.
 *
 * validatePlan() is the post-generation structural guard. These tests verify:
 *   - A well-formed plan from plan() passes validatePlan() with no critical errors
 *   - Structurally malformed plans produce the expected validation errors
 *   - assertPlanValid() throws on critical errors and is silent on clean plans
 *   - validateSourceSinkCompatibility() recognises known and unknown format pairs
 *
 * Oracle rank: 1 (mathematical / structural) for cycle/DAG properties,
 *              2 (domain contract) for step-presence and format requirements.
 */

import { describe, it, expect } from 'vitest';
import { plan } from '../planner.js';
import type { Config, ExecutionPlan } from '../planner.js';
import { PlanStepType } from '../steps.js';
import {
  validatePlan,
  assertPlanValid,
  validateSourceSinkCompatibility,
} from '../validation.js';
import type { DAG } from '../dag.js';

// ---------------------------------------------------------------------------
// Config factory
// ---------------------------------------------------------------------------

function makeConfig(overrides: Partial<Config> = {}): Config {
  return {
    version: '1.0',
    source: { format: 'xes' },
    execution: { profile: 'fast' },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Helper: produce a valid plan and mutate it
// ---------------------------------------------------------------------------

function planWith(overrides: Partial<Config> = {}): ExecutionPlan {
  return plan(makeConfig(overrides));
}

// ---------------------------------------------------------------------------
// Plans generated by plan() pass validatePlan()
// ---------------------------------------------------------------------------

describe('validatePlan() — well-formed plans from plan()', () => {
  it('returns zero errors for a fast-profile plan', () => {
    const errors = validatePlan(planWith());
    const critical = errors.filter((e) => e.severity === 'error');
    expect(critical).toHaveLength(0);
  });

  it('returns zero critical errors for all standard profiles', () => {
    for (const profile of ['fast', 'balanced', 'quality', 'stream']) {
      const errors = validatePlan(planWith({ execution: { profile } }));
      const critical = errors.filter((e) => e.severity === 'error');
      expect(
        critical,
        `profile="${profile}" produced critical validation errors: ${JSON.stringify(critical)}`
      ).toHaveLength(0);
    }
  });

  it('assertPlanValid() does not throw for a well-formed plan', () => {
    expect(() => assertPlanValid(planWith())).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// Plans with structural defects produce expected errors
// ---------------------------------------------------------------------------

describe('validatePlan() — structurally malformed plans', () => {
  it('flags missing id', () => {
    const p = { ...planWith(), id: '' };
    const errors = validatePlan(p);
    const match = errors.find((e) => e.path === 'id');
    expect(match).toBeDefined();
    expect(match?.severity).toBe('error');
  });

  it('flags missing hash', () => {
    const p = { ...planWith(), hash: '' };
    const errors = validatePlan(p);
    const match = errors.find((e) => e.path === 'hash');
    expect(match).toBeDefined();
    expect(match?.severity).toBe('error');
  });

  it('flags null steps array', () => {
    const p = { ...planWith(), steps: null as unknown as ExecutionPlan['steps'] };
    const errors = validatePlan(p);
    const match = errors.find((e) => e.path === 'steps');
    expect(match).toBeDefined();
    expect(match?.severity).toBe('error');
  });

  it('flags malformed graph (missing edges)', () => {
    const p = {
      ...planWith(),
      graph: { nodes: ['bootstrap'], edges: null } as unknown as DAG,
    };
    const errors = validatePlan(p);
    const match = errors.find((e) => e.path === 'graph');
    expect(match).toBeDefined();
    expect(match?.severity).toBe('error');
  });

  it('flags duplicate step IDs', () => {
    const original = planWith();
    // Duplicate the first step to create a collision
    const dupStep = { ...original.steps[0] };
    const p: ExecutionPlan = {
      ...original,
      steps: [...original.steps, dupStep],
      graph: {
        nodes: [...original.graph.nodes, dupStep.id],
        edges: original.graph.edges,
      },
    };
    const errors = validatePlan(p);
    const dup = errors.find((e) => e.message.includes('Duplicate'));
    expect(dup).toBeDefined();
  });

  it('flags absent bootstrap step', () => {
    const original = planWith();
    const p: ExecutionPlan = {
      ...original,
      steps: original.steps.filter((s) => s.type !== PlanStepType.BOOTSTRAP),
      graph: {
        nodes: original.graph.nodes.filter((n) => n !== 'bootstrap'),
        edges: original.graph.edges.filter(([src, tgt]) => src !== 'bootstrap' && tgt !== 'bootstrap'),
      },
    };
    const errors = validatePlan(p);
    const match = errors.find((e) => e.message.includes('bootstrap'));
    expect(match).toBeDefined();
  });

  it('flags absent load_source step', () => {
    const original = planWith();
    const p: ExecutionPlan = {
      ...original,
      steps: original.steps.filter((s) => s.type !== PlanStepType.LOAD_SOURCE),
      graph: {
        nodes: original.graph.nodes.filter((n) => n !== 'load_source'),
        edges: original.graph.edges.filter(([src, tgt]) => src !== 'load_source' && tgt !== 'load_source'),
      },
    };
    const errors = validatePlan(p);
    const match = errors.find((e) => e.message.toLowerCase().includes('load_source'));
    expect(match).toBeDefined();
  });

  it('assertPlanValid() throws when critical errors are present', () => {
    const p = { ...planWith(), id: '' };
    expect(() => assertPlanValid(p)).toThrow(/Invalid execution plan/);
  });
});

// ---------------------------------------------------------------------------
// validateSourceSinkCompatibility()
// ---------------------------------------------------------------------------

describe('validateSourceSinkCompatibility()', () => {
  it('returns no errors for known source + known sink', () => {
    const errors = validateSourceSinkCompatibility('xes', 'json');
    expect(errors.filter((e) => e.severity === 'error')).toHaveLength(0);
  });

  it('returns a warning (not error) for unknown source format', () => {
    const errors = validateSourceSinkCompatibility('parquet_v99', 'json');
    const warnings = errors.filter((e) => e.path === 'source' && e.severity === 'warning');
    expect(warnings.length).toBeGreaterThan(0);
  });

  it('returns a warning (not error) for unknown sink format', () => {
    const errors = validateSourceSinkCompatibility('xes', 'avro');
    const warnings = errors.filter((e) => e.path === 'sink' && e.severity === 'warning');
    expect(warnings.length).toBeGreaterThan(0);
  });

  it('returns an error when source is empty string', () => {
    const errors = validateSourceSinkCompatibility('', 'json');
    const critical = errors.filter((e) => e.severity === 'error' && e.path === 'source');
    expect(critical.length).toBeGreaterThan(0);
  });

  it('returns an error when sink is empty string', () => {
    const errors = validateSourceSinkCompatibility('xes', '');
    const critical = errors.filter((e) => e.severity === 'error' && e.path === 'sink');
    expect(critical.length).toBeGreaterThan(0);
  });

  it('all known source formats pass without error', () => {
    const known = ['xes', 'csv', 'json', 'ocel', 'parquet', 'bpmn'];
    for (const src of known) {
      const errors = validateSourceSinkCompatibility(src, 'json');
      const critical = errors.filter((e) => e.severity === 'error');
      expect(critical, `source="${src}" unexpectedly produced errors`).toHaveLength(0);
    }
  });

  it('all known sink formats pass without error', () => {
    const known = ['json', 'parquet', 'csv', 'html', 'mermaid', 'stdout'];
    for (const sink of known) {
      const errors = validateSourceSinkCompatibility('xes', sink);
      const critical = errors.filter((e) => e.severity === 'error');
      expect(critical, `sink="${sink}" unexpectedly produced errors`).toHaveLength(0);
    }
  });
});
