/**
 * Oracle-ranked tests for regressRemainingTime
 *
 * Van der Aalst "remaining-time" prediction perspective.
 *
 * Oracle ranks:
 *   Rank 1 — Mathematical theorem (properties provable from algebra/statistics)
 *   Rank 2 — Domain contract  (design decisions that must hold for any valid input)
 *   Rank 3 — Metamorphic relation (input perturbation → output relation)
 */

import { describe, it, expect } from 'vitest';
import { regressRemainingTime } from '../classifiers.js';

// ─── Shared fixtures ──────────────────────────────────────────────────────────

/**
 * Perfectly linear dataset: remaining_time = 10000 − 500 * trace_length
 * x = trace_length (first numeric feature column, the independent variable)
 * y = remaining_time (target)
 */
function makePerfectLinear(n = 20) {
  return Array.from({ length: n }, (_, i) => ({
    case_id: `c${i + 1}`,
    trace_length: i + 1,
    remaining_time: 10000 - (i + 1) * 500,
  }));
}

/**
 * Dataset with added Gaussian noise on top of a linear relationship.
 */
function makeNoisyLinear(n = 30, noiseSd = 200) {
  // Seeded-ish noise: use deterministic sequence so the test is repeatable
  return Array.from({ length: n }, (_, i) => {
    const noise = ((i * 7 + 3) % 17) * (noiseSd / 17) - noiseSd / 2;
    return {
      case_id: `c${i + 1}`,
      trace_length: i + 1,
      remaining_time: Math.max(0, 8000 - (i + 1) * 300 + noise),
    };
  });
}

/**
 * Exponential decay: remaining_time = 5000 * e^(−0.1 * trace_length)
 */
function makePerfectExponential(n = 15) {
  return Array.from({ length: n }, (_, i) => ({
    case_id: `e${i + 1}`,
    trace_length: i + 1,
    remaining_time: 5000 * Math.exp(-0.1 * (i + 1)),
  }));
}

/**
 * Quadratic dataset: remaining_time = 1000 − 10*x − 2*x²
 */
function makePerfectQuadratic(n = 10) {
  return Array.from({ length: n }, (_, i) => ({
    case_id: `q${i + 1}`,
    trace_length: i + 1,
    remaining_time: 1000 - 10 * (i + 1) - 2 * (i + 1) * (i + 1),
  }));
}

// ─────────────────────────────────────────────────────────────────────────────
// RANK 1 — Mathematical theorems
// ─────────────────────────────────────────────────────────────────────────────

describe('regressRemainingTime — Rank 1: mathematical theorems', () => {
  it('perfect linear data produces R² = 1.0', async () => {
    // Theorem: OLS on data generated by an exact affine function achieves R² = 1.
    const data = makePerfectLinear(20);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(result.rSquared).toBeCloseTo(1.0, 5);
  });

  it('R² is at most 1.0 for any dataset (mathematical upper bound)', async () => {
    for (const data of [
      makePerfectLinear(10),
      makeNoisyLinear(15),
      makePerfectExponential(10),
    ]) {
      const result = await regressRemainingTime(data, { method: 'linear_regression' });
      expect(result.rSquared).toBeLessThanOrEqual(1.0 + 1e-10);
    }
  });

  it('R² is bounded by implementation guard at minimum −1 for degenerate data', async () => {
    // The source clamps R² to max(-1, 1 - ssRes/ssTot).
    // Any numeric dataset must return a finite, bounded value.
    const data = makeNoisyLinear(20);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(result.rSquared).toBeGreaterThanOrEqual(-1.0 - 1e-10);
    expect(Number.isFinite(result.rSquared)).toBe(true);
  });

  it('RMSE = 0 for perfect linear data (exact fit)', async () => {
    // Theorem: residuals are zero for exact fit → RMSE = sqrt(0/n) = 0.
    const data = makePerfectLinear(20);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(result.rmse).toBeCloseTo(0, 3);
  });

  it('MAE = 0 for perfect linear data (exact fit)', async () => {
    const data = makePerfectLinear(20);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(result.mae).toBeCloseTo(0, 3);
  });

  it('MAE <= RMSE always (Cauchy-Schwarz inequality)', async () => {
    // Theorem: RMSE = sqrt(mean(residuals²)) >= mean(|residuals|) = MAE by C-S.
    for (const data of [makePerfectLinear(10), makeNoisyLinear(20)]) {
      const result = await regressRemainingTime(data, { method: 'linear_regression' });
      expect(result.mae).toBeLessThanOrEqual(result.rmse + 1e-10);
    }
  });

  it('prediction count equals input trace count', async () => {
    // By definition of prediction output: one prediction per input trace.
    const data = makePerfectLinear(15);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(result.predictions).toHaveLength(15);
  });

  it('polynomial degree-1 fit equals linear regression quality', async () => {
    // Theorem: poly(degree=1) is identical to linear_regression in terms of R².
    const data = makePerfectLinear(12);
    const linResult = await regressRemainingTime(data, { method: 'linear_regression' });
    const polyResult = await regressRemainingTime(data, {
      method: 'polynomial_regression',
      degree: 1,
    });
    expect(polyResult.rSquared).toBeCloseTo(linResult.rSquared, 4);
  });

  it('polynomial coefficients length equals degree + 1 (Vandermonde theorem)', async () => {
    // Theorem: a degree-d polynomial has exactly d+1 coefficients [a₀, a₁, ..., aₐ].
    const data = makePerfectQuadratic(10);
    const result = await regressRemainingTime(data, {
      method: 'polynomial_regression',
      degree: 2,
    });
    expect(result.coefficients).toHaveLength(3); // degree 2 → 3 coefficients
  });

  it('polynomial degree=3 produces 4 coefficients', async () => {
    const data = makePerfectLinear(15);
    const result = await regressRemainingTime(data, {
      method: 'polynomial_regression',
      degree: 3,
    });
    expect(result.coefficients).toHaveLength(4);
  });

  it('R² and RMSE and MAE are all finite numbers', async () => {
    const data = makeNoisyLinear(20);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(Number.isFinite(result.rSquared)).toBe(true);
    expect(Number.isFinite(result.rmse)).toBe(true);
    expect(Number.isFinite(result.mae)).toBe(true);
  });

  it('linear model returns non-NaN slope and intercept', async () => {
    const data = makePerfectLinear(10);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(Number.isNaN(result.slope!)).toBe(false);
    expect(Number.isNaN(result.intercept!)).toBe(false);
  });

  it('slope is negative for data where remaining_time decreases as trace_length increases', async () => {
    // Theorem: OLS slope = Cov(x,y)/Var(x). Data is negatively correlated → slope < 0.
    const data = makePerfectLinear(15);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(result.slope!).toBeLessThan(0);
  });

  it('exponential regression produces finite growthRate, amplitude, doublingTime', async () => {
    const data = makePerfectExponential(12);
    const result = await regressRemainingTime(data, { method: 'exponential_regression' });
    expect(Number.isFinite(result.growthRate!)).toBe(true);
    expect(Number.isFinite(result.amplitude!)).toBe(true);
    expect(Number.isFinite(result.doublingTime!) || result.doublingTime === Infinity).toBe(true);
  });

  it('exponential fit on perfect exponential data achieves R² > 0.9', async () => {
    // Theorem: log-linear OLS is exact for data from an affine log model.
    // Use larger dataset to avoid edge effects.
    const data = makePerfectExponential(15);
    const result = await regressRemainingTime(data, { method: 'exponential_regression' });
    expect(result.rSquared).toBeGreaterThan(0.9);
  });

  it('RMSE and MAE are non-negative (definition: sqrt of sum of squares / mean abs)', async () => {
    const data = makeNoisyLinear(20);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(result.rmse).toBeGreaterThanOrEqual(0);
    expect(result.mae).toBeGreaterThanOrEqual(0);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// RANK 2 — Domain contracts
// ─────────────────────────────────────────────────────────────────────────────

describe('regressRemainingTime — Rank 2: domain contracts', () => {
  it('result method field matches requested method (linear)', async () => {
    const data = makePerfectLinear(10);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(result.method).toBe('linear_regression');
  });

  it('result method field matches requested method (polynomial)', async () => {
    const data = makePerfectLinear(10);
    const result = await regressRemainingTime(data, { method: 'polynomial_regression' });
    expect(result.method).toBe('polynomial_regression');
  });

  it('result method field matches requested method (exponential)', async () => {
    const data = makePerfectExponential(10);
    const result = await regressRemainingTime(data, { method: 'exponential_regression' });
    expect(result.method).toBe('exponential_regression');
  });

  it('default method is linear_regression when none specified', async () => {
    const data = makePerfectLinear(10);
    const result = await regressRemainingTime(data);
    expect(result.method).toBe('linear_regression');
  });

  it('predictions array has caseId, actual, and predicted fields per entry', async () => {
    const data = makePerfectLinear(8);
    const result = await regressRemainingTime(data);
    for (const p of result.predictions) {
      expect(typeof p.caseId).toBe('string');
      expect(p.caseId.length).toBeGreaterThan(0);
      expect(typeof p.actual).toBe('number');
      expect(typeof p.predicted).toBe('number');
    }
  });

  it('caseIds in predictions match input case_ids in order', async () => {
    const data = makePerfectLinear(8);
    const result = await regressRemainingTime(data);
    result.predictions.forEach((p, i) => {
      expect(p.caseId).toBe(data[i].case_id);
    });
  });

  it('throws when fewer than 2 traces supplied', async () => {
    const single = [{ case_id: 'c1', trace_length: 5, remaining_time: 1000 }];
    await expect(regressRemainingTime(single)).rejects.toThrow(
      'Not enough traces for regression (need at least 2)'
    );
  });

  it('empty array input throws (< 2 traces)', async () => {
    await expect(regressRemainingTime([])).rejects.toThrow();
  });

  it('linear result has slope and intercept (contract: always present for linear method)', async () => {
    const data = makePerfectLinear(10);
    const result = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(result.slope).toBeDefined();
    expect(result.intercept).toBeDefined();
  });

  it('polynomial result has coefficients array (contract: always present for polynomial method)', async () => {
    const data = makePerfectLinear(10);
    const result = await regressRemainingTime(data, { method: 'polynomial_regression', degree: 2 });
    expect(Array.isArray(result.coefficients)).toBe(true);
    expect(result.coefficients!.length).toBeGreaterThan(0);
  });

  it('exponential result has growthRate and amplitude (contract: always present for exponential)', async () => {
    const data = makePerfectExponential(10);
    const result = await regressRemainingTime(data, { method: 'exponential_regression' });
    expect(result.growthRate).toBeDefined();
    expect(result.amplitude).toBeDefined();
  });

  it('actual values in predictions equal the original remaining_time', async () => {
    const data = makePerfectLinear(8);
    const result = await regressRemainingTime(data);
    result.predictions.forEach((p, i) => {
      expect(p.actual).toBeCloseTo(data[i].remaining_time as number, 5);
    });
  });

  it('R² is in [0, 1] for a well-fitted dataset (no pathological data)', async () => {
    const data = makePerfectLinear(15);
    const result = await regressRemainingTime(data);
    expect(result.rSquared).toBeGreaterThanOrEqual(0);
    expect(result.rSquared).toBeLessThanOrEqual(1.0 + 1e-10);
  });

  it('polynomial regression with large degree does not throw (graceful handling)', async () => {
    // Contract: even with an extreme degree, the function must not throw —
    // it should return a valid RegressionResult (coefficients array, finite metrics).
    const data = makePerfectLinear(5);
    const result = await regressRemainingTime(data, {
      method: 'polynomial_regression',
      degree: 10,
    });
    expect(result.method).toBe('polynomial_regression');
    expect(Array.isArray(result.coefficients)).toBe(true);
    expect(Number.isFinite(result.rSquared)).toBe(true);
    expect(Number.isFinite(result.rmse)).toBe(true);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// RANK 3 — Metamorphic relations
// ─────────────────────────────────────────────────────────────────────────────

describe('regressRemainingTime — Rank 3: metamorphic relations', () => {
  it('deterministic: same input produces identical R², slope, intercept', async () => {
    const data = makeNoisyLinear(20);
    const r1 = await regressRemainingTime(data, { method: 'linear_regression' });
    const r2 = await regressRemainingTime(data, { method: 'linear_regression' });
    expect(r1.rSquared).toBe(r2.rSquared);
    expect(r1.slope).toBe(r2.slope);
    expect(r1.intercept).toBe(r2.intercept);
    expect(r1.rmse).toBe(r2.rmse);
    expect(r1.mae).toBe(r2.mae);
  });

  it('deterministic: same input produces identical predictions array', async () => {
    const data = makeNoisyLinear(15);
    const r1 = await regressRemainingTime(data);
    const r2 = await regressRemainingTime(data);
    expect(r1.predictions).toEqual(r2.predictions);
  });

  it('higher-degree polynomial fits linear data at least as well as linear (R² monotone)', async () => {
    // Metamorphic: poly(d=2) has strictly more capacity than poly(d=1) = linear.
    // For any dataset, a higher-degree polynomial can only increase or match R².
    const data = makeNoisyLinear(20);
    const d1 = await regressRemainingTime(data, { method: 'polynomial_regression', degree: 1 });
    const d2 = await regressRemainingTime(data, { method: 'polynomial_regression', degree: 2 });
    // d2 has more capacity → R² should be >= R²(d1) (within numerical tolerance)
    expect(d2.rSquared).toBeGreaterThanOrEqual(d1.rSquared - 1e-6);
  });

  it('adding more traces from the same linear distribution keeps R² close to 1', async () => {
    // Metamorphic: more observations from the exact linear model → R² does not decrease.
    const small = await regressRemainingTime(makePerfectLinear(5));
    const large = await regressRemainingTime(makePerfectLinear(20));
    // Both should be ~1.0 for perfect data; large sample should not be worse.
    expect(large.rSquared).toBeGreaterThanOrEqual(small.rSquared - 1e-6);
  });

  it('shifting trace_length by constant does not change R² or slope', async () => {
    // Metamorphic: R² and slope are invariant under translation of x (OLS theorem).
    // (slope does not change; intercept adjusts to compensate)
    const base = makePerfectLinear(12);
    const shifted = base.map((r) => ({ ...r, trace_length: (r.trace_length as number) + 100 }));
    const r1 = await regressRemainingTime(base, { method: 'linear_regression' });
    const r2 = await regressRemainingTime(shifted, { method: 'linear_regression' });
    expect(r2.rSquared).toBeCloseTo(r1.rSquared, 5);
    expect(r2.slope!).toBeCloseTo(r1.slope!, 5);
  });

  it('scaling remaining_time by constant scales slope proportionally', async () => {
    // Metamorphic: y* = 2y → slope* = 2*slope (linear homogeneity of OLS).
    const base = makePerfectLinear(12);
    const scaled = base.map((r) => ({
      ...r,
      remaining_time: (r.remaining_time as number) * 2,
    }));
    const r1 = await regressRemainingTime(base);
    const r2 = await regressRemainingTime(scaled);
    expect(r2.slope!).toBeCloseTo(r1.slope! * 2, 4);
  });

  it('scaling remaining_time by constant scales intercept proportionally', async () => {
    const base = makePerfectLinear(12);
    const scaled = base.map((r) => ({
      ...r,
      remaining_time: (r.remaining_time as number) * 3,
    }));
    const r1 = await regressRemainingTime(base);
    const r2 = await regressRemainingTime(scaled);
    expect(r2.intercept!).toBeCloseTo(r1.intercept! * 3, 4);
  });

  it('scaling remaining_time by constant preserves R² (R² is scale-invariant)', async () => {
    // R² = 1 - ssRes/ssTot. Both numerator and denominator scale by k², so R² is invariant.
    const base = makeNoisyLinear(15);
    const scaled = base.map((r) => ({
      ...r,
      remaining_time: (r.remaining_time as number) * 5,
    }));
    const r1 = await regressRemainingTime(base);
    const r2 = await regressRemainingTime(scaled);
    expect(r2.rSquared).toBeCloseTo(r1.rSquared, 5);
  });

  it('adding a perfect outlier only mildly reduces R² on large datasets', async () => {
    // Metamorphic: on 20 good points + 1 outlier, R² should still be > 0.7 for strong signal.
    const base = makePerfectLinear(20);
    const withOutlier = [
      ...base,
      { case_id: 'outlier', trace_length: 10, remaining_time: 99999 },
    ];
    const r1 = await regressRemainingTime(base);
    const r2 = await regressRemainingTime(withOutlier);
    // With one outlier in 21 points, R² should be lower but model direction preserved.
    expect(r1.rSquared).toBeGreaterThan(r2.rSquared - 0.01); // r1 >= r2 (outlier hurts fit)
    expect(r2.slope!).toBeLessThan(0); // Direction still negative
  });
});
