#!/usr/bin/env python3
"""Generate docs/abi/ex4pm-bindings.abi.json from `export_name` attributes in
crates/wasm4pm-ex4pm-bindings/src/*.rs. Deterministic: sorted, no timestamps.

Usage: gen_abi.py [OUT.json]   (default: <repo>/docs/abi/ex4pm-bindings.abi.json)
"""
import json, re, sys
from pathlib import Path

CRATE = Path(__file__).resolve().parent.parent
REPO = CRATE.parent.parent
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "docs/abi/ex4pm-bindings.abi.json"

# wasm32 lowering of the Rust C-ABI types used by these exports.
WASM = {"*const u8": "i32", "*mut u8": "i32", "*mut usize": "i32", "usize": "i32", "u32": "i32"}
ATTR = re.compile(r'#\[unsafe\(export_name\s*=\s*"([^"]+)"\)\]\s*'
                  r'pub\s+(unsafe\s+)?extern\s+"C"\s+fn\s+(\w+)\s*\((.*?)\)\s*(?:->\s*([^{]+?))?\s*\{', re.S)
CORE = {"version_v1", "alloc_v1", "dealloc_v1", "free_v1"}


def params(s):
    out = []
    for p in [x.strip() for x in s.split(",") if x.strip()]:
        n, t = [x.strip() for x in p.split(":", 1)]
        out.append({"name": n, "rust": t, "wasm": WASM[t]})
    return out


exports = []
for f in sorted((CRATE / "src").glob("*.rs")):
    for m in ATTR.finditer(f.read_text()):
        name, uns, fn, ps, ret = m.groups()
        base = name.replace("wasm4pm_ex4pm_bindings_", "").replace("wasm4pm_ex4pm_", "")
        if fn in CORE:
            kind, algo = "core", None
        elif base.endswith("_replay_v1"):
            kind, algo = "replay", base[: -len("_replay_v1")]
        else:
            kind, algo = "request_response", base[: -len("_v1")]
        exports.append({
            "export": name, "kind": kind, "algo": algo, "source": f"src/{f.name}",
            "rust_fn": fn, "unsafe": bool(uns),
            "params": params(ps),
            "result": {"rust": ret, "wasm": WASM[ret]} if ret else None,
        })
exports.sort(key=lambda e: e["export"])
names = [e["export"] for e in exports]
assert len(names) == len(set(names)), "duplicate export names"

doc = {
    "$comment": "GENERATED by crates/wasm4pm-ex4pm-bindings/scripts/gen_abi.py; do not edit.",
    "crate": "wasm4pm-ex4pm-bindings",
    "abi_version": 1,
    "target": "wasm32 (pointers and usize lower to i32)",
    "export_count": len(exports),
    "envelope": {
        "request": "UTF-8 JSON object written into module memory at (ptr,len)",
        "response_ok": {"result": "<algorithm body JSON>", "digest": "<16 lowercase hex chars>"},
        "response_error": {"error": "<message string>"},
        "response_location": "heap buffer at returned ptr; byte length written to *out_len",
    },
    "digest": {
        "algorithm": "FNV-1a 64-bit",
        "offset_basis": "0xcbf29ce484222325",
        "prime": "0x100000001b3",
        "input": "serde_json serialization bytes of the `result` body (not the whole envelope)",
        "format": "{:016x}",
        "non_cryptographic": True,
        "note": "in-WASM replay self-check only; receipt identity hashing is BLAKE3 on the ex4pm side",
    },
    "replay": {
        "export_pattern": "<algo>_replay_v1(ptr, len) -> u32",
        "semantics": "re-executes the computation from the same request bytes and re-wraps via the shared respond(); returns 1 iff the recomputed response is non-empty (replay_ok seam), else 0",
        "caveat": "the u32 does not itself compare against a prior digest; hosts compare the `digest` field of the original and recomputed responses",
    },
    "memory": {
        "alloc": {"export": "wasm4pm_ex4pm_bindings_alloc_v1", "contract": "reserves len zeroed bytes in module linear memory for the host to write a request into"},
        "dealloc": {"export": "wasm4pm_ex4pm_bindings_dealloc_v1", "contract": "release an alloc_v1 buffer; len MUST equal the alloc len"},
        "free": {"export": "wasm4pm_ex4pm_bindings_free_v1", "contract": "release a response buffer returned by an <algo>_v1 export; caller MUST call it with (ptr, *out_len)"},
        "ownership": "reading an input buffer never frees it; the host deallocates input buffers via dealloc_v1 after the call and response buffers via free_v1",
    },
    "exports": exports,
}
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n")
print(f"wrote {OUT} exports={len(exports)}")
