// Compatibility adapter — implementation lives in commands/doctor/index.ts.
export {
  doctorCommand,
  doctor,
  // check arrays
  ENV_CHECKS,
  TPS_CHECKS,
  CLAUDE_CODE_CHECKS,
  ALGO_HEALTH_CHECKS,
  DATA_QUALITY_CHECKS,
  OUTPUT_CONTRACT_CHECKS,
  OBSERVABILITY_CHECKS,
  CONFIG_SYSTEM_CHECKS,
  BRCE_CHECKS,
  ALL_CHECKS,
  // subcommands
  doctorCheck,
  doctorEnv,
  doctorTps,
  doctorFix,
  doctorCapabilities,
  doctorPerf,
  doctorWatch,
  doctorReport,
  doctorPublish,
  doctorHooks,
  // Vision 2030 and BRCE surfaces
  runVision2030Audit,
  VISION_2030_CAPABILITIES,
  resolveVision2030Subject,
  verifyVision2030Report,
  executeRepairPlan,
  verifyRepairReceiptChain,
  planRepairs,
  REPAIR_INTENTS,
  validateRepairRegistry,
} from './doctor/index.js';

export type {
  DoctorOptions,
  Pathology,
  Severity,
  RepairMode,
  Diagnosis,
  ObservationKind,
  DiagnosisProof,
  DoctorReport,
  CapabilityDefinition,
  CapabilityEvidence,
  CapabilityStanding,
  DiagnosisEvidence,
  Vision2030Report,
  Vision2030Subject,
  Vision2030Verification,
  PlannedRepair,
  RepairExecutionReport,
  HardenedRepairExecutionReport,
  RepairReceiptChain,
  RepairReceiptChainVerification,
  RepairIntent,
  RepairIntentId,
  RepairOutcome,
  JtbdProbe,
} from './doctor/index.js';

export { runHook, probeHooks } from './doctor/index.js';
