// Auto-generated by CodeManufactory from wasm4pm ontology
// DO NOT EDIT — regenerate via: ostar manufacture wasm4pm
//
// This module provides the get_capabilities_json() function for the WASM export.
// Feature flags are checked at compile time via cfg!().

/// Generate the capabilities JSON for get_capabilities() WASM export.
pub fn get_capabilities_json() -> String {
    serde_json::json!({
        "version": env!("CARGO_PKG_VERSION"),
        "features": {
            "discovery": true,
            "conformance": cfg!(feature = "conformance_full"),
            "ml": cfg!(feature = "ml"),
            "streaming": cfg!(feature = "streaming_full"),
            "powl": cfg!(feature = "powl"),
            "ocel": cfg!(feature = "ocel"),
            "alignment_fitness": cfg!(feature = "alignment_fitness"),
            "petri_net_playout": cfg!(feature = "petri_net_playout"),
            "extensive_playout": cfg!(feature = "extensive_playout"),
            "align_etconformance": cfg!(feature = "align_etconformance"),
            "montecarlo": cfg!(feature = "montecarlo"),
        }
    })
    .to_string()
}
