// Auto-generated by CodeManufactory from pictl ontology
// DO NOT EDIT — regenerate via: ostar manufacture pictl

use serde::{Deserialize, Serialize};
use std::fmt;

/// Deployment profiles from pictl-core.nt.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DeploymentProfile {
    profile_browser,
    profile_cloud,
    profile_edge,
    profile_fog,
    profile_iot,
}

impl DeploymentProfile {
    pub fn id(&self) -> &'static str {
        match self {
            Self::profile_browser => "profile-browser",
            Self::profile_cloud => "profile-cloud",
            Self::profile_edge => "profile-edge",
            Self::profile_fog => "profile-fog",
            Self::profile_iot => "profile-iot",
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            Self::profile_browser => "Browser",
            Self::profile_cloud => "Cloud",
            Self::profile_edge => "Edge",
            Self::profile_fog => "Fog",
            Self::profile_iot => "IoT",
        }
    }

    /// Maximum binary size target in MB for this profile.
    pub fn size_target_mb(&self) -> f64 {
        match self {
            Self::profile_browser => 4.0,
            Self::profile_cloud => 5.0,
            Self::profile_edge => 4.0,
            Self::profile_fog => 4.0,
            Self::profile_iot => 4.0,
        }
    }

    pub fn all() -> &'static [Self] {
        &[
            Self::profile_browser,
            Self::profile_cloud,
            Self::profile_edge,
            Self::profile_fog,
            Self::profile_iot,
        ]
    }
}

impl fmt::Display for DeploymentProfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.label())
    }
}
