// GENERATED by ggen sync (TICKET-030). Do not hand-edit -- edit the ontology or this template.
import type { Phase } from "../lib/domain/phase";

export interface PhaseIndicatorProps {
  phase: Phase;
}

/** Renders the current session phase. Label text is the Phase union member itself -- no
 * phase-name string literal is introduced here beyond what phase.ts already exports. */
export function PhaseIndicator({ phase }: PhaseIndicatorProps) {
  return (
    <div role="status" aria-live="polite" data-testid="phase-indicator">
      {phase}
    </div>
  );
}
