// GENERATED by ggen sync (TICKET-033). Do not hand-edit -- edit the ontology or this template.
import type { TransitionReceipt } from "../lib/domain/receipt";

export interface SessionSummaryProps {
  receipt: TransitionReceipt;
}

/** Displays the final session receipt, including its checksum in a copyable/verifiable format
 * (acceptance-step/10: "match the final receipt hash"). Renders an explicit incomplete state
 * rather than a blank or fabricated hash when the checksum is missing. */
export function SessionSummary({ receipt }: SessionSummaryProps) {
  const hasChecksum = Boolean(receipt.checksum?.checksumValue);
  return (
    <section aria-label="Session summary" data-testid="session-summary">
      {receipt.label && <p data-testid="session-summary-label">{receipt.label}</p>}
      {hasChecksum ? (
        <code data-testid="session-summary-checksum">
          {receipt.checksum.algorithm}:{receipt.checksum.checksumValue}
        </code>
      ) : (
        <p data-testid="session-summary-incomplete">Receipt incomplete: no checksum recorded.</p>
      )}
    </section>
  );
}
