export const demoEvents = [
  { id: "e1", at: "2026-08-18T08:00:00Z", type: "claim.observed", claim: { id: "delivery", title: "Platform delivery", domain: "PAAS", standing: "VERIFIED", systemStanding: "ALIVE", kind: "KPI", materiality: 80, owner: "Platform", businessImpact: "Launch remains on plan.", evidence: ["receipt:delivery"], metrics: [{ id: "delivery-status", label: "Status", value: "On plan", vocabulary: "delivery" }], actions: [] } },
  { id: "e2", at: "2026-08-18T08:01:00Z", type: "claim.observed", claim: { id: "identity-risk", title: "Customer identity migration", domain: "SAAS", standing: "OBSERVED", systemStanding: "PARTIAL_ALIVE", kind: "Risk", materiality: 95, owner: "Identity", businessImpact: "One dependency needs attention; the UI can manufacture an intent but cannot actuate.", evidence: ["event:identity-17"], metrics: [{ id: "blocked", label: "Blocked dependencies", value: 1, vocabulary: "business" }], actions: [{ id: "inspect", label: "Inspect evidence", consequence: "SELECT" }, { id: "approve", label: "Approve governed remediation", consequence: "DO", requiredAuthority: "brce:identity-remediation", reversible: false }] } },
  { id: "e3", at: "2026-08-18T08:02:00Z", type: "claim.observed", claim: { id: "cloud-cost", title: "Cloud operating cost", domain: "IAAS", standing: "FORECAST", kind: "Variance", materiality: 70, roles: ["CEO", "CFO"], owner: "FinOps", businessImpact: "Forecast is within the admitted operating envelope.", metrics: [{ id: "actual", label: "Actual", value: "$79M", vocabulary: "financial" }, { id: "plan", label: "Plan", value: "$84M", vocabulary: "financial" }, { id: "variance", label: "Variance", value: "-$5M", vocabulary: "financial" }], actions: [] } },
  { id: "e4", at: "2026-08-18T08:03:00Z", type: "claim.observed", claim: { id: "source-drift", title: "Source-model correspondence", domain: "GGEN", standing: "RECEIPTED", systemStanding: "BLOCKED", kind: "Dependency", materiality: 88, roles: ["CTO", "ENGINEER", "AUDITOR"], owner: "Manufacturing", businessImpact: "Source drift is represented as a bounded exception rather than global failure.", evidence: ["receipt:drift", "replay:drift"], metrics: [{ id: "drift", label: "Open drift edges", value: 1, vocabulary: "technology" }], actions: [{ id: "repair", label: "Open repair intent", consequence: "CONSTRUCT", requiredAuthority: "construct:repair" }] } },
  { id: "e5", at: "2026-08-18T08:04:00Z", type: "claim.observed", claim: { id: "receipt-coverage", title: "Governed actuation evidence", domain: "GOVERNANCE", standing: "RECEIPTED", systemStanding: "ALIVE", kind: "Receipt", materiality: 85, roles: ["CTO", "ENGINEER", "AUDITOR"], owner: "Governance", businessImpact: "Decision context and resulting intents are replayable from deterministic receipts.", evidence: ["receipt:ui", "receipt:intent"], metrics: [{ id: "render-do", label: "Direct render actuations", value: 0, vocabulary: "evidence" }], actions: [] } },
  { id: "e6", at: "2026-08-18T08:05:00Z", type: "claim.observed", claim: { id: "ggen-opportunity", title: "Deterministic manufacture opportunity", domain: "GGEN", standing: "DERIVED", kind: "Opportunity", materiality: 65, roles: ["CEO", "CTO"], owner: "Architecture", businessImpact: "A larger portion of synchronization work can move from review to exception handling.", metrics: [{ id: "scope", label: "Scope", value: "Review exceptions", vocabulary: "business" }], actions: [{ id: "explore", label: "Explore frontier", consequence: "SELECT" }] } }
];

export const demoInput = { grammarVersion: "dd-ui/2", avatar: "CEO", context: "normal", authority: [], asOf: "2026-08-18T08:06:00Z", events: demoEvents };
