#!/usr/bin/env python3
"""bench_report.py — Unified Criterion benchmark report generator.

Walks ``wasm4pm/target/criterion/**/new/estimates.json`` (the most recent run
for each benchmark) and emits:

    docs/benchmarks/REPORT.md   — sorted Markdown table: bench | median | ±CI
    docs/benchmarks/report.csv  — same data, machine-readable

Ordering is deterministic (lexicographic by benchmark id) so the output is
reproducible and diff-friendly.

Usage:
    python3 scripts/bench_report.py
    python3 scripts/bench_report.py --criterion-dir <dir>   # parse a fixture
    python3 scripts/bench_report.py --out-dir docs/benchmarks

Exit codes:
    0  report written
    2  no estimates found
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CRITERION_DIR = REPO_ROOT / "wasm4pm" / "target" / "criterion"
DEFAULT_OUT_DIR = REPO_ROOT / "docs" / "benchmarks"


def fmt_time(ns: float) -> str:
    for unit, scale in (("s", 1e9), ("ms", 1e6), ("µs", 1e3), ("ns", 1.0)):
        if ns >= scale:
            return f"{ns / scale:.3f} {unit}"
    return f"{ns:.3f} ns"


def collect(criterion_dir: Path) -> list[dict]:
    rows: list[dict] = []
    for est_path in criterion_dir.rglob("new/estimates.json"):
        try:
            data = json.loads(est_path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        median = data.get("median")
        if not isinstance(median, dict):
            continue
        pe = median.get("point_estimate")
        if not isinstance(pe, (int, float)):
            continue
        ci = median.get("confidence_interval") or {}
        lo = ci.get("lower_bound")
        hi = ci.get("upper_bound")
        bench_id = str(est_path.parent.parent.relative_to(criterion_dir))
        rows.append({
            "bench": bench_id,
            "median_ns": float(pe),
            "ci_lower_ns": float(lo) if isinstance(lo, (int, float)) else None,
            "ci_upper_ns": float(hi) if isinstance(hi, (int, float)) else None,
        })
    rows.sort(key=lambda r: r["bench"])
    return rows


def ci_str(r: dict) -> str:
    if r["ci_lower_ns"] is None or r["ci_upper_ns"] is None:
        return "—"
    half = (r["ci_upper_ns"] - r["ci_lower_ns"]) / 2.0
    return f"±{fmt_time(half)}"


def write_markdown(rows: list[dict], path: Path) -> None:
    lines = [
        "# Benchmark Report",
        "",
        "Generated by `scripts/bench_report.py` from Criterion's most recent runs",
        "(`target/criterion/**/new/estimates.json`). Sorted by benchmark id.",
        "",
        f"Total benchmarks: {len(rows)}",
        "",
        "| Benchmark | Median | ±CI (95%) |",
        "|-----------|--------|-----------|",
    ]
    for r in rows:
        lines.append(f"| {r['bench']} | {fmt_time(r['median_ns'])} | {ci_str(r)} |")
    lines.append("")
    path.write_text("\n".join(lines))


def write_csv(rows: list[dict], path: Path) -> None:
    with path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["bench", "median_ns", "ci_lower_ns", "ci_upper_ns"])
        for r in rows:
            w.writerow([
                r["bench"],
                f"{r['median_ns']:.3f}",
                "" if r["ci_lower_ns"] is None else f"{r['ci_lower_ns']:.3f}",
                "" if r["ci_upper_ns"] is None else f"{r['ci_upper_ns']:.3f}",
            ])


def main() -> int:
    ap = argparse.ArgumentParser(description="Unified Criterion report generator")
    ap.add_argument("--criterion-dir", type=Path, default=DEFAULT_CRITERION_DIR)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = ap.parse_args()

    if not args.criterion_dir.is_dir():
        print(f"ERROR: criterion dir not found: {args.criterion_dir}", file=sys.stderr)
        return 2

    rows = collect(args.criterion_dir)
    if not rows:
        print(f"ERROR: no estimates.json found under {args.criterion_dir}", file=sys.stderr)
        return 2

    args.out_dir.mkdir(parents=True, exist_ok=True)
    md_path = args.out_dir / "REPORT.md"
    csv_path = args.out_dir / "report.csv"
    write_markdown(rows, md_path)
    write_csv(rows, csv_path)
    print(f"Wrote {md_path} and {csv_path} ({len(rows)} benchmarks)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
