// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Attribute value types for event data
 */
export type AttributeValue =
  | { tag: 'String'; value: string }
  | { tag: 'Int'; value: bigint }
  | { tag: 'Float'; value: number }
  | { tag: 'Date'; value: string }
  | { tag: 'Boolean'; value: boolean }
  | { tag: 'List'; value: Array<AttributeValue> }
  | { tag: 'Container'; value: { [key in string]?: AttributeValue } };
