// AUTO-GENERATED by scripts/generate_python_dispatch.py — do not edit.

use crate::invoke::{
    arg_bool, arg_f64, arg_i64, arg_js_value, arg_string, arg_u8, arg_usize, wrap_bool_result,
    wrap_f64_result, wrap_js_result, wrap_js_value, wrap_string_result, wrap_u32_result,
    wrap_u8_result, wrap_usize_result, wrap_void, wrap_void_result, InvokeResult,
};

pub fn dispatch_export(name: &str, args: &[serde_json::Value]) -> Result<InvokeResult, String> {
    match name {
        "rl_orchestrator_reset" => {
            
            wrap_string_result(|| wasm4pm::rl_orchestrator_reset())
        }
        "rl_orchestrator_active_agent" => {
            
            wrap_u8_result(|| wasm4pm::rl_orchestrator_active_agent())
        }
        "circuit_breaker_get_state" => {
            
            wrap_string_result(|| wasm4pm::circuit_breaker_get_state())
        }
        "circuit_breaker_set_state" => {
            let json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::circuit_breaker_set_state(&json))
        }
        "circuit_breaker_configure" => {
            let config_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::circuit_breaker_configure(&config_json))
        }
        "circuit_breaker_get_config" => {
            
            wrap_string_result(|| wasm4pm::circuit_breaker_get_config())
        }
        "circuit_breaker_reset" => {
            
            wrap_string_result(|| wasm4pm::circuit_breaker_reset())
        }
        "run_agentic_pipeline" => {
            let task_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::run_agentic_pipeline(&task_json))
        }
        "validate_agentic_handoff" => {
            let request_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::validate_agentic_handoff(&request_json))
        }
        "evaluate_agentic_counterfactuals" => {
            let task_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::evaluate_agentic_counterfactuals(&task_json))
        }
        "run_agentic_jtbd_suite" => {
            let cases_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::run_agentic_jtbd_suite(&cases_json))
        }
        "rl_orchestrator_switch_agent" => {
            let agent_type = arg_u8(&args, 0)?;
            wrap_string_result(|| wasm4pm::rl_orchestrator_switch_agent(agent_type))
        }
        "rl_orchestrator_set_linucb" => {
            let enabled = arg_bool(&args, 0)?;
            wrap_string_result(|| wasm4pm::rl_orchestrator_set_linucb(enabled))
        }
        "rl_orchestrator_telemetry" => {
            
            wrap_string_result(|| wasm4pm::rl_orchestrator_telemetry())
        }
        "rl_orchestrator_get_telemetry" => {
            
            wrap_js_result(|| wasm4pm::rl_orchestrator_get_telemetry())
        }
        "serialize_rl_state" => {
            
            wrap_string_result(|| wasm4pm::serialize_rl_state())
        }
        "restore_rl_state" => {
            let json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::restore_rl_state(&json))
        }
        "get_spc_history" => {
            
            wrap_string_result(|| wasm4pm::get_spc_history())
        }
        "set_spc_history" => {
            let json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::set_spc_history(&json))
        }
        "truex_verify_receipt" => {
            let envelope_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::truex_verify_receipt(&envelope_json))
        }
        "evaluate_ocpq" => {
            let ocel_json = arg_string(&args, 0)?;
            let query_str = arg_string(&args, 1)?;
            wrap_string_result(|| wasm4pm::evaluate_ocpq(&ocel_json, &query_str))
        }
        "init" => {
            
            wrap_string_result(|| wasm4pm::init())
        }
        "get_version" => {
            
            Ok(InvokeResult::String(wasm4pm::get_version()))
        }
        "get_capabilities" => {
            
            wrap_js_result(|| wasm4pm::get_capabilities())
        }
        "clear_all_caches" => {
            
            wrap_void(|| { wasm4pm::clear_all_caches(); })
        }
        "get_cache_stats" => {
            
            wrap_js_result(|| wasm4pm::get_cache_stats())
        }
        "set_drift_thresholds" => {
            let low = arg_f64(&args, 0)?;
            let high = arg_f64(&args, 1)?;
            wrap_string_result(|| wasm4pm::set_drift_thresholds(low as f32, high as f32))
        }
        "get_drift_thresholds" => {
            
            Ok(InvokeResult::String(wasm4pm::get_drift_thresholds()))
        }
        "reset_drift_thresholds" => {
            
            Ok(InvokeResult::String(wasm4pm::reset_drift_thresholds()))
        }
        "simd_token_replay" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            Ok(InvokeResult::String(wasm4pm::simd_token_replay(&log_handle, &activity_key)))
        }
        "autonomic_execute_cycle" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let config_json = arg_string(&args, 2)?;
            wrap_string_result(|| wasm4pm::autonomic_execute_cycle(&log_handle, &activity_key, &config_json))
        }
        "discover_footprints" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::algorithms::discover_footprints(&eventlog_handle, &activity_key))
        }
        "discover_alpha_plus_plus" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let min_support = arg_f64(&args, 2)?;
            wrap_js_result(|| wasm4pm::algorithms::discover_alpha_plus_plus(&eventlog_handle, &activity_key, min_support))
        }
        "discover_dfg_filtered" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let min_frequency = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::algorithms::discover_dfg_filtered(&eventlog_handle, &activity_key, min_frequency))
        }
        "export_dfg_to_json" => {
            let handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::algorithms::export_dfg_to_json(&handle))
        }
        "export_petri_net_to_json" => {
            let handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::algorithms::export_petri_net_to_json(&handle))
        }
        "compute_optimal_alignments" => {
            let log_handle = arg_string(&args, 0)?;
            let petri_net_handle = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            let cost_config_json = arg_string(&args, 3)?;
            wrap_js_result(|| wasm4pm::alignments::compute_optimal_alignments(&log_handle, &petri_net_handle, &activity_key, &cost_config_json))
        }
        "compute_alignments" => {
            let log_handle = arg_string(&args, 0)?;
            let dfg_handle = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::alignments::compute_alignments(&log_handle, &dfg_handle, &activity_key))
        }
        "monte_carlo_simulation" => {
            let log_handle = arg_string(&args, 0)?;
            let powl_handle = arg_string(&args, 1)?;
            let root_id = arg_string(&args, 2)?;
            let config_json = arg_string(&args, 3)?;
            wrap_js_result(|| wasm4pm::montecarlo::monte_carlo_simulation(&log_handle, &powl_handle, &root_id, &config_json))
        }
        "build_ngram_predictor" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let n = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::prediction::build_ngram_predictor(&log_handle, &activity_key, n))
        }
        "predict_next_activity" => {
            let predictor_handle = arg_string(&args, 0)?;
            let prefix_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction::predict_next_activity(&predictor_handle, &prefix_json))
        }
        "score_trace_likelihood" => {
            let predictor_handle = arg_string(&args, 0)?;
            let activities_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction::score_trace_likelihood(&predictor_handle, &activities_json))
        }
        "cache_stats" => {
            
            wrap_js_result(|| wasm4pm::wasm_utils::cache_stats())
        }
        "hash_xes_content" => {
            let xes_content = arg_string(&args, 0)?;
            Ok(InvokeResult::String(wasm4pm::wasm_utils::hash_xes_content(&xes_content)))
        }
        "jaccard_distance" => {
            let set1_json = arg_string(&args, 0)?;
            let set2_json = arg_string(&args, 1)?;
            wrap_f64_result(|| wasm4pm::wasm_utils::jaccard_distance(&set1_json, &set2_json))
        }
        "ewma_series" => {
            let values_json = arg_string(&args, 0)?;
            let alpha = arg_f64(&args, 1)?;
            wrap_js_result(|| wasm4pm::wasm_utils::ewma_series(&values_json, alpha))
        }
        "identify_high_variance_activities" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let threshold = arg_f64(&args, 2)?;
            wrap_js_result(|| wasm4pm::wasm_utils::identify_high_variance_activities(&eventlog_handle, &activity_key, threshold))
        }
        "wf_net_to_powl" => {
            let petri_net_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::wf_to_powl::wf_net_to_powl(&petri_net_handle))
        }
        "load_eventlog_from_xes" => {
            let content = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::xes_format::load_eventlog_from_xes(&content))
        }
        "load_eventlog_from_xes_cached" => {
            let content = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::xes_format::load_eventlog_from_xes_cached(&content))
        }
        "export_eventlog_to_xes" => {
            let eventlog_handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::xes_format::export_eventlog_to_xes(&eventlog_handle))
        }
        "xes_format_info" => {
            
            Ok(InvokeResult::String(wasm4pm::xes_format::xes_format_info()))
        }
        "read_bpmn" => {
            let bpmn_xml = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::bpmn_import::read_bpmn(&bpmn_xml))
        }
        "check_token_based_replay" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let petri_net_handle = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::conformance::check_token_based_replay(&eventlog_handle, &petri_net_handle, &activity_key))
        }
        "conformance_info" => {
            
            Ok(InvokeResult::String(wasm4pm::conformance::conformance_info()))
        }
        "discover_prefix_tree" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let max_path_length = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::log_to_trie::discover_prefix_tree(&eventlog_handle, &activity_key, max_path_length))
        }
        "load_powl_from_string" => {
            let powl_str = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::powl_parser::load_powl_from_string(&powl_str))
        }
        "load_powl_v2_from_string" => {
            let dsl = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::powl_parser::load_powl_v2_from_string(&dsl))
        }
        "discover_causal_alpha" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::causal_graph::discover_causal_alpha(&eventlog_handle, &activity_key))
        }
        "discover_causal_heuristic" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let threshold = arg_f64(&args, 2)?;
            wrap_js_result(|| wasm4pm::causal_graph::discover_causal_heuristic(&eventlog_handle, &activity_key, threshold))
        }
        "check_data_quality" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::data_quality::check_data_quality(&log_handle, &activity_key, &timestamp_key))
        }
        "check_ocel_data_quality" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::data_quality::check_ocel_data_quality(&ocel_handle))
        }
        "infer_eventlog_schema" => {
            let log_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::data_quality::infer_eventlog_schema(&log_handle))
        }
        "infer_ocel_schema" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::data_quality::infer_ocel_schema(&ocel_handle))
        }
        "discover_dfg_hierarchical" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let num_chunks = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::hierarchical::discover_dfg_hierarchical(&eventlog_handle, &activity_key, num_chunks))
        }
        "discover_dfg_hierarchical_by_events" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let max_chunk_events = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::hierarchical::discover_dfg_hierarchical_by_events(&eventlog_handle, &activity_key, max_chunk_events))
        }
        "discover_oc_petri_net" => {
            let ocel_handle = arg_string(&args, 0)?;
            let algorithm = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::oc_petri_net::discover_oc_petri_net(&ocel_handle, &algorithm))
        }
        "oc_petri_net_info" => {
            
            wrap_js_value(|| wasm4pm::oc_petri_net::oc_petri_net_info())
        }
        "list_ocel_object_types" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::ocel_flatten::list_ocel_object_types(&ocel_handle))
        }
        "get_ocel_type_statistics" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::ocel_flatten::get_ocel_type_statistics(&ocel_handle))
        }
        "flatten_ocel_to_eventlog" => {
            let ocel_handle = arg_string(&args, 0)?;
            let object_type = arg_string(&args, 1)?;
            wrap_string_result(|| wasm4pm::ocel_flatten::flatten_ocel_to_eventlog(&ocel_handle, &object_type))
        }
        "measure_ocel_flattening_loss" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::ocel_flatten::measure_ocel_flattening_loss(&ocel_handle))
        }
        "validate_process_tree" => {
            let tree_json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::process_tree::validate_process_tree(&tree_json))
        }
        "discover_simple_process_tree" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::process_tree::discover_simple_process_tree(&log_handle, &activity_key))
        }
        "smart_engine_create" => {
            
            Ok(InvokeResult::String(wasm4pm::smart_engine::smart_engine_create()))
        }
        "smart_engine_create_with_params" => {
            let cache_capacity = arg_usize(&args, 0)?;
            let convergence_window = arg_usize(&args, 1)?;
            let convergence_threshold = arg_f64(&args, 2)?;
            let max_iterations = arg_usize(&args, 3)?;
            Ok(InvokeResult::String(wasm4pm::smart_engine::smart_engine_create_with_params(cache_capacity, convergence_window, convergence_threshold, max_iterations)))
        }
        "smart_engine_run" => {
            let handle = arg_string(&args, 0)?;
            let algorithm = arg_string(&args, 1)?;
            let traces_json = arg_string(&args, 2)?;
            wrap_string_result(|| wasm4pm::smart_engine::smart_engine_run(&handle, &algorithm, &traces_json))
        }
        "smart_engine_converged" => {
            let handle = arg_string(&args, 0)?;
            wrap_bool_result(|| wasm4pm::smart_engine::smart_engine_converged(&handle))
        }
        "smart_engine_cache_stats" => {
            let handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::smart_engine::smart_engine_cache_stats(&handle))
        }
        "smart_engine_check_convergence" => {
            let handle = arg_string(&args, 0)?;
            let metric = arg_f64(&args, 1)?;
            wrap_bool_result(|| wasm4pm::smart_engine::smart_engine_check_convergence(&handle, metric))
        }
        "smart_engine_reset" => {
            let handle = arg_string(&args, 0)?;
            wrap_void_result(|| wasm4pm::smart_engine::smart_engine_reset(&handle))
        }
        "smart_engine_destroy" => {
            let handle = arg_string(&args, 0)?;
            wrap_void_result(|| wasm4pm::smart_engine::smart_engine_destroy(&handle))
        }
        "wasm_compute_simplicity" => {
            let places = arg_usize(&args, 0)?;
            let transitions = arg_usize(&args, 1)?;
            let arcs = arg_usize(&args, 2)?;
            Ok(InvokeResult::Number(wasm4pm::ilp_discovery::wasm_compute_simplicity(places, transitions, arcs) as f64))
        }
        "discover_ilp_petri_net" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ilp_discovery::discover_ilp_petri_net(&eventlog_handle, &activity_key))
        }
        "discover_optimized_dfg" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let fitness_weight = arg_f64(&args, 2)?;
            let simplicity_weight = arg_f64(&args, 3)?;
            wrap_js_result(|| wasm4pm::ilp_discovery::discover_optimized_dfg(&eventlog_handle, &activity_key, fitness_weight, simplicity_weight))
        }
        "ilp_discovery_info" => {
            
            Ok(InvokeResult::String(wasm4pm::ilp_discovery::ilp_discovery_info()))
        }
        "encode_dfg_as_text" => {
            let dfg_handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_dfg_as_text(&dfg_handle))
        }
        "encode_variants_as_text" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let top_n = arg_usize(&args, 2)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_variants_as_text(&log_handle, &activity_key, top_n))
        }
        "encode_statistics_as_text" => {
            let log_handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_statistics_as_text(&log_handle))
        }
        "encode_conformance_as_text" => {
            let result_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_conformance_as_text(&result_json))
        }
        "encode_bottlenecks_as_text" => {
            let result_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_bottlenecks_as_text(&result_json))
        }
        "encode_petri_net_as_text" => {
            let petri_net_handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_petri_net_as_text(&petri_net_handle))
        }
        "encode_ocel_as_text" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_ocel_as_text(&ocel_handle))
        }
        "encode_oc_petri_net_as_text" => {
            let oc_petri_net_handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_oc_petri_net_as_text(&oc_petri_net_handle))
        }
        "encode_model_comparison_as_text" => {
            let model1_handle = arg_string(&args, 0)?;
            let model2_handle = arg_string(&args, 1)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_model_comparison_as_text(&model1_handle, &model2_handle))
        }
        "encode_ocel_summary_as_text" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::text_encoding::encode_ocel_summary_as_text(&ocel_handle))
        }
        "discover_astar" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let max_iterations = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::fast_discovery::discover_astar(&eventlog_handle, &activity_key, max_iterations))
        }
        "discover_hill_climbing" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::fast_discovery::discover_hill_climbing(&eventlog_handle, &activity_key))
        }
        "analyze_trace_variants" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::fast_discovery::analyze_trace_variants(&eventlog_handle, &activity_key))
        }
        "mine_sequential_patterns" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let min_support = arg_f64(&args, 2)?;
            let pattern_length = arg_usize(&args, 3)?;
            wrap_js_result(|| wasm4pm::fast_discovery::mine_sequential_patterns(&eventlog_handle, &activity_key, min_support, pattern_length))
        }
        "detect_concept_drift" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let window_size = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::fast_discovery::detect_concept_drift(&eventlog_handle, &activity_key, window_size))
        }
        "cluster_traces" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let num_clusters = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::fast_discovery::cluster_traces(&eventlog_handle, &activity_key, num_clusters))
        }
        "analyze_start_end_activities" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::fast_discovery::analyze_start_end_activities(&eventlog_handle, &activity_key))
        }
        "analyze_activity_cooccurrence" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::fast_discovery::analyze_activity_cooccurrence(&eventlog_handle, &activity_key))
        }
        "fast_discovery_info" => {
            
            Ok(InvokeResult::String(wasm4pm::fast_discovery::fast_discovery_info()))
        }
        "generalization" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let petri_net_handle = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::generalization::generalization(&eventlog_handle, &petri_net_handle, &activity_key))
        }
        "register_model" => {
            let envelope_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::model_registry::register_model(&envelope_json))
        }
        "get_model" => {
            let model_id = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::model_registry::get_model(&model_id))
        }
        "discover_inductive_miner" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::more_discovery::discover_inductive_miner(&eventlog_handle, &activity_key))
        }
        "discover_ant_colony" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let num_ants = arg_usize(&args, 2)?;
            let iterations = arg_usize(&args, 3)?;
            wrap_js_result(|| wasm4pm::more_discovery::discover_ant_colony(&eventlog_handle, &activity_key, num_ants, iterations))
        }
        "discover_simulated_annealing" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let temperature = arg_f64(&args, 2)?;
            let cooling_rate = arg_f64(&args, 3)?;
            wrap_js_result(|| wasm4pm::more_discovery::discover_simulated_annealing(&eventlog_handle, &activity_key, temperature, cooling_rate))
        }
        "extract_process_skeleton" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let min_frequency = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::more_discovery::extract_process_skeleton(&eventlog_handle, &activity_key, min_frequency))
        }
        "analyze_activity_dependencies" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::more_discovery::analyze_activity_dependencies(&eventlog_handle, &activity_key))
        }
        "analyze_case_attributes" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::more_discovery::analyze_case_attributes(&eventlog_handle, &activity_key))
        }
        "more_discovery_info" => {
            
            Ok(InvokeResult::String(wasm4pm::more_discovery::more_discovery_info()))
        }
        "oc_conformance_check" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::oc_conformance::oc_conformance_check(&ocel_handle))
        }
        "oc_conformance_info" => {
            
            wrap_js_value(|| wasm4pm::oc_conformance::oc_conformance_info())
        }
        "analyze_oc_performance" => {
            let ocel_handle = arg_string(&args, 0)?;
            let timestamp_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::oc_performance::analyze_oc_performance(&ocel_handle, &timestamp_key))
        }
        "oc_performance_analysis" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::oc_performance::oc_performance_analysis(&ocel_handle))
        }
        "oc_performance_info" => {
            
            wrap_js_value(|| wasm4pm::oc_performance::oc_performance_info())
        }
        "powl_execute" => {
            let powl_str = arg_string(&args, 0)?;
            let config_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::powl_execution::powl_execute(&powl_str, &config_json))
        }
        "discover_handover_network" => {
            let log_handle = arg_string(&args, 0)?;
            let resource_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::social_network::discover_handover_network(&log_handle, &resource_key))
        }
        "discover_working_together_network" => {
            let log_handle = arg_string(&args, 0)?;
            let resource_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::social_network::discover_working_together_network(&log_handle, &resource_key))
        }
        "compute_network_metrics" => {
            let log_handle = arg_string(&args, 0)?;
            let resource_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::social_network::compute_network_metrics(&log_handle, &resource_key))
        }
        "compute_clustering_coefficient" => {
            let log_handle = arg_string(&args, 0)?;
            let resource_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::social_network::compute_clustering_coefficient(&log_handle, &resource_key))
        }
        "detect_communities" => {
            let log_handle = arg_string(&args, 0)?;
            let resource_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::social_network::detect_communities(&log_handle, &resource_key))
        }
        "streaming_dfg_begin" => {
            
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_dfg_begin())
        }
        "streaming_dfg_add_event" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            let activity = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_dfg_add_event(&handle, &case_id, &activity))
        }
        "streaming_dfg_add_batch" => {
            let handle = arg_string(&args, 0)?;
            let events_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_dfg_add_batch(&handle, &events_json))
        }
        "streaming_dfg_close_trace" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_dfg_close_trace(&handle, &case_id))
        }
        "streaming_skeleton_finalize" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_skeleton_finalize(&handle))
        }
        "streaming_heuristic_begin" => {
            let threshold = arg_f64(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_heuristic_begin(threshold))
        }
        "streaming_heuristic_add_event" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            let activity = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_heuristic_add_event(&handle, &case_id, &activity))
        }
        "streaming_heuristic_close_trace" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_heuristic_close_trace(&handle, &case_id))
        }
        "streaming_heuristic_snapshot" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_heuristic_snapshot(&handle))
        }
        "streaming_heuristic_finalize" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_heuristic_finalize(&handle))
        }
        "streaming_info" => {
            
            Ok(InvokeResult::String(wasm4pm::streaming_wasm::streaming_info()))
        }
        "streaming_dfg_flush_open" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_dfg_flush_open(&handle))
        }
        "streaming_dfg_snapshot" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_dfg_snapshot(&handle))
        }
        "streaming_dfg_finalize" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_dfg_finalize(&handle))
        }
        "streaming_dfg_stats" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_dfg_stats(&handle))
        }
        "streaming_skeleton_begin" => {
            let min_frequency = arg_usize(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_skeleton_begin(min_frequency))
        }
        "streaming_skeleton_add_event" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            let activity = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_skeleton_add_event(&handle, &case_id, &activity))
        }
        "streaming_skeleton_close_trace" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_skeleton_close_trace(&handle, &case_id))
        }
        "streaming_skeleton_snapshot" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_wasm::streaming_skeleton_snapshot(&handle))
        }
        "analyze_variant_complexity" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::final_analytics::analyze_variant_complexity(&eventlog_handle, &activity_key))
        }
        "compute_activity_transition_matrix" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::final_analytics::compute_activity_transition_matrix(&eventlog_handle, &activity_key))
        }
        "analyze_process_speedup" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let timestamp_key = arg_string(&args, 1)?;
            let window_size = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::final_analytics::analyze_process_speedup(&eventlog_handle, &timestamp_key, window_size))
        }
        "compute_trace_similarity_matrix" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::final_analytics::compute_trace_similarity_matrix(&eventlog_handle, &activity_key))
        }
        "analyze_temporal_bottlenecks" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::final_analytics::analyze_temporal_bottlenecks(&eventlog_handle, &activity_key, &timestamp_key))
        }
        "extract_activity_ordering" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::final_analytics::extract_activity_ordering(&eventlog_handle, &activity_key))
        }
        "final_analytics_info" => {
            
            Ok(InvokeResult::String(wasm4pm::final_analytics::final_analytics_info()))
        }
        "new_streaming_dfg" => {
            
            wrap_string_result(|| wasm4pm::incremental_dfg::new_streaming_dfg())
        }
        "streaming_dfg_process_event" => {
            let handle = arg_string(&args, 0)?;
            let activity_id = arg_usize(&args, 1)?;
            wrap_void_result(|| wasm4pm::incremental_dfg::streaming_dfg_process_event(&handle, activity_id as u32))
        }
        "streaming_dfg_end_trace" => {
            let handle = arg_string(&args, 0)?;
            wrap_void_result(|| wasm4pm::incremental_dfg::streaming_dfg_end_trace(&handle))
        }
        "incremental_dfg_snapshot" => {
            let handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::incremental_dfg::incremental_dfg_snapshot(&handle))
        }
        "incremental_dfg_stats" => {
            let handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::incremental_dfg::incremental_dfg_stats(&handle))
        }
        "streaming_dfg_string_new" => {
            
            wrap_string_result(|| wasm4pm::incremental_dfg::streaming_dfg_string_new())
        }
        "streaming_dfg_string_event" => {
            let handle = arg_string(&args, 0)?;
            let activity = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::incremental_dfg::streaming_dfg_string_event(&handle, &activity))
        }
        "streaming_dfg_string_end_trace" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::incremental_dfg::streaming_dfg_string_end_trace(&handle))
        }
        "streaming_dfg_string_snapshot" => {
            let handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::incremental_dfg::streaming_dfg_string_snapshot(&handle))
        }
        "discover_performance_dfg" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::performance_dfg::discover_performance_dfg(&log_handle, &activity_key, &timestamp_key))
        }
        "generate_recommendations" => {
            let log_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::recommendations::generate_recommendations(&log_handle))
        }
        "recommendations_info" => {
            
            wrap_js_value(|| wasm4pm::recommendations::recommendations_info())
        }
        "detect_drift" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let window_size = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::prediction_drift::detect_drift(&log_handle, &activity_key, window_size))
        }
        "compute_ewma" => {
            let values_json = arg_string(&args, 0)?;
            let alpha = arg_f64(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction_drift::compute_ewma(&values_json, alpha))
        }
        "discover_temporal_profile" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::temporal_profile::discover_temporal_profile(&log_handle, &activity_key, &timestamp_key))
        }
        "check_temporal_conformance" => {
            let log_handle = arg_string(&args, 0)?;
            let profile_handle = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            let timestamp_key = arg_string(&args, 3)?;
            let zeta = arg_f64(&args, 4)?;
            wrap_js_result(|| wasm4pm::temporal_profile::check_temporal_conformance(&log_handle, &profile_handle, &activity_key, &timestamp_key, zeta))
        }
        "alignment_fitness" => {
            let log_handle = arg_string(&args, 0)?;
            let petri_net_handle = arg_string(&args, 1)?;
            let config_json = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::alignment_fitness::alignment_fitness(&log_handle, &petri_net_handle, &config_json))
        }
        "conformance_cache_new" => {
            
            Ok(InvokeResult::String(wasm4pm::conformance_cache::conformance_cache_new()))
        }
        "conformance_cache_get" => {
            let handle = arg_string(&args, 0)?;
            let log_handle = arg_string(&args, 1)?;
            let model_hash = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::conformance_cache::conformance_cache_get(&handle, &log_handle, model_hash as u64))
        }
        "conformance_cache_insert" => {
            let handle = arg_string(&args, 0)?;
            let log_handle = arg_string(&args, 1)?;
            let model_hash = arg_usize(&args, 2)?;
            let fitness = arg_f64(&args, 3)?;
            let precision = arg_f64(&args, 4)?;
            let generalization = arg_f64(&args, 5)?;
            let trace_count = arg_usize(&args, 6)?;
            wrap_js_result(|| wasm4pm::conformance_cache::conformance_cache_insert(&handle, &log_handle, model_hash as u64, fitness, precision, generalization, trace_count))
        }
        "conformance_cache_stats" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::conformance_cache::conformance_cache_stats(&handle))
        }
        "conformance_cache_clear" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::conformance_cache::conformance_cache_clear(&handle))
        }
        "conformance_cache_hash_model" => {
            let dfg_json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::conformance_cache::conformance_cache_hash_model(&dfg_json))
        }
        "discover_correlation" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            let threshold = arg_f64(&args, 3)?;
            wrap_js_result(|| wasm4pm::correlation_miner::discover_correlation(&eventlog_handle, &activity_key, &timestamp_key, threshold))
        }
        "discover_genetic_algorithm" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let population_size = arg_usize(&args, 2)?;
            let generations = arg_usize(&args, 3)?;
            wrap_js_result(|| wasm4pm::genetic_discovery::discover_genetic_algorithm(&eventlog_handle, &activity_key, population_size, generations))
        }
        "discover_pso_algorithm" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let swarm_size = arg_usize(&args, 2)?;
            let iterations = arg_usize(&args, 3)?;
            wrap_js_result(|| wasm4pm::genetic_discovery::discover_pso_algorithm(&eventlog_handle, &activity_key, swarm_size, iterations))
        }
        "discover_aco_algorithm" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let ant_count = arg_usize(&args, 2)?;
            let iterations = arg_usize(&args, 3)?;
            wrap_js_result(|| wasm4pm::genetic_discovery::discover_aco_algorithm(&eventlog_handle, &activity_key, ant_count, iterations))
        }
        "genetic_discovery_info" => {
            
            Ok(InvokeResult::String(wasm4pm::genetic_discovery::genetic_discovery_info()))
        }
        "parallel_discover_dfg" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            Ok(InvokeResult::String(wasm4pm::parallel_executor::parallel_discover_dfg(&log_handle, &activity_key)))
        }
        "parallel_run_algorithms" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let algo_json = arg_string(&args, 2)?;
            Ok(InvokeResult::String(wasm4pm::parallel_executor::parallel_run_algorithms(&log_handle, &activity_key, &algo_json)))
        }
        "parallel_available" => {
            
            Ok(InvokeResult::Bool(wasm4pm::parallel_executor::parallel_available()))
        }
        "petri_net_playout" => {
            let petri_net_handle = arg_string(&args, 0)?;
            let config_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::petri_net_playout::petri_net_playout(&petri_net_handle, &config_json))
        }
        "analyze_resource_utilization" => {
            let log_handle = arg_string(&args, 0)?;
            let resource_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::resource_analysis::analyze_resource_utilization(&log_handle, &resource_key, &timestamp_key))
        }
        "analyze_resource_activity_matrix" => {
            let log_handle = arg_string(&args, 0)?;
            let resource_key = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::resource_analysis::analyze_resource_activity_matrix(&log_handle, &resource_key, &activity_key))
        }
        "identify_resource_bottlenecks" => {
            let log_handle = arg_string(&args, 0)?;
            let resource_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            let activity_key = arg_string(&args, 3)?;
            wrap_js_result(|| wasm4pm::resource_analysis::identify_resource_bottlenecks(&log_handle, &resource_key, &timestamp_key, &activity_key))
        }
        "discover_transition_system_from_handle" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let window = arg_usize(&args, 2)?;
            let direction = arg_string(&args, 3)?;
            wrap_js_result(|| wasm4pm::transition_system::discover_transition_system_from_handle(&eventlog_handle, &activity_key, window, &direction))
        }
        "extract_case_features" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            let config_json = arg_string(&args, 3)?;
            wrap_js_result(|| wasm4pm::feature_extraction::extract_case_features(&log_handle, &activity_key, &timestamp_key, &config_json))
        }
        "extract_prefix_features" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            let prefix_length = arg_usize(&args, 3)?;
            wrap_js_result(|| wasm4pm::feature_extraction::extract_prefix_features(&log_handle, &activity_key, &timestamp_key, prefix_length))
        }
        "export_features_csv" => {
            let features_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::feature_extraction::export_features_csv(&features_json))
        }
        "export_features_json" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            let config_json = arg_string(&args, 3)?;
            wrap_string_result(|| wasm4pm::feature_extraction::export_features_json(&log_handle, &activity_key, &timestamp_key, &config_json))
        }
        "compute_feature_importance" => {
            let model_handle = arg_string(&args, 0)?;
            let prefix_json = arg_string(&args, 1)?;
            let ngram_order = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::feature_importance::compute_feature_importance(&model_handle, &prefix_json, ngram_order))
        }
        "global_feature_importance" => {
            let model_handle = arg_string(&args, 0)?;
            let log_handle = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            let ngram_order = arg_usize(&args, 3)?;
            wrap_js_result(|| wasm4pm::feature_importance::global_feature_importance(&model_handle, &log_handle, &activity_key, ngram_order))
        }
        "score_anomaly" => {
            let model_handle = arg_string(&args, 0)?;
            let trace_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction_outcome::score_anomaly(&model_handle, &trace_json))
        }
        "compute_boundary_coverage" => {
            let log_handle = arg_string(&args, 0)?;
            let prefix_json = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::prediction_outcome::compute_boundary_coverage(&log_handle, &prefix_json, &activity_key))
        }
        "compute_trace_likelihood" => {
            let model_handle = arg_string(&args, 0)?;
            let trace_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction_outcome::compute_trace_likelihood(&model_handle, &trace_json))
        }
        "predict_outcome_wasm" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let prefix_json = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::prediction_outcome::predict_outcome_wasm(&eventlog_handle, &activity_key, &prefix_json))
        }
        "discover_dfg_simd" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::simd_streaming_dfg::discover_dfg_simd(&eventlog_handle, &activity_key))
        }
        "discover_dfg_simd_handle" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::simd_streaming_dfg::discover_dfg_simd_handle(&eventlog_handle, &activity_key))
        }
        "simd_streaming_dfg_info" => {
            
            wrap_js_value(|| wasm4pm::simd_streaming_dfg::simd_streaming_dfg_info())
        }
        "pipeline_begin" => {
            let config_json = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::streaming_pipeline::pipeline_begin(&config_json))
        }
        "pipeline_add_event" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            let activity = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::streaming_pipeline::pipeline_add_event(&handle, &case_id, &activity))
        }
        "pipeline_close_trace" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::streaming_pipeline::pipeline_close_trace(&handle, &case_id))
        }
        "pipeline_stats" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_pipeline::pipeline_stats(&handle))
        }
        "pipeline_snapshot" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_pipeline::pipeline_snapshot(&handle))
        }
        "pipeline_finalize" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_pipeline::pipeline_finalize(&handle))
        }
        "discover_heuristic_miner" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let dependency_threshold = arg_f64(&args, 2)?;
            wrap_js_result(|| wasm4pm::advanced_algorithms::discover_heuristic_miner(&eventlog_handle, &activity_key, dependency_threshold))
        }
        "analyze_infrequent_paths" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let frequency_threshold = arg_f64(&args, 2)?;
            wrap_js_result(|| wasm4pm::advanced_algorithms::analyze_infrequent_paths(&eventlog_handle, &activity_key, frequency_threshold))
        }
        "detect_rework" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::advanced_algorithms::detect_rework(&eventlog_handle, &activity_key))
        }
        "detect_bottlenecks" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            let duration_threshold_seconds = arg_usize(&args, 3)?;
            wrap_js_result(|| wasm4pm::advanced_algorithms::detect_bottlenecks(&eventlog_handle, &activity_key, &timestamp_key, duration_threshold_seconds as u64))
        }
        "compute_model_metrics" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::advanced_algorithms::compute_model_metrics(&eventlog_handle, &activity_key))
        }
        "advanced_algorithms_info" => {
            
            Ok(InvokeResult::String(wasm4pm::advanced_algorithms::advanced_algorithms_info()))
        }
        "align_etconformance_precision" => {
            let log_handle = arg_string(&args, 0)?;
            let petri_net_handle = arg_string(&args, 1)?;
            let config_json = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::align_etconformance::align_etconformance_precision(&log_handle, &petri_net_handle, &config_json))
        }
        "get_capability_registry" => {
            
            wrap_js_result(|| wasm4pm::capability_registry::get_capability_registry())
        }
        "check_declare_conformance" => {
            let log_handle = arg_string(&args, 0)?;
            let declare_handle = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::declare_conformance::check_declare_conformance(&log_handle, &declare_handle, &activity_key))
        }
        "store_declare_from_json" => {
            let declare_json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::declare_conformance::store_declare_from_json(&declare_json))
        }
        "wasm_reduce_petri_net" => {
            let net_handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::petri_net_reduction::wasm_reduce_petri_net(&net_handle))
        }
        "extract_prefix_features_wasm" => {
            let prefix_json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::prediction_features::extract_prefix_features_wasm(&prefix_json))
        }
        "compute_rework_score" => {
            let trace_json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::prediction_features::compute_rework_score(&trace_json))
        }
        "build_transition_probabilities" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction_features::build_transition_probabilities(&log_handle, &activity_key))
        }
        "estimate_queue_delay" => {
            let arrival_rate = arg_f64(&args, 0)?;
            let service_rate = arg_f64(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction_resource::estimate_queue_delay(arrival_rate, service_rate))
        }
        "rank_interventions" => {
            let interventions_json = arg_string(&args, 0)?;
            let exploitation_weight = arg_f64(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction_resource::rank_interventions(&interventions_json, exploitation_weight))
        }
        "select_intervention" => {
            let bandit_json = arg_string(&args, 0)?;
            let exploration_factor = arg_f64(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction_resource::select_intervention(&bandit_json, exploration_factor))
        }
        "discover_performance_spectrum_wasm" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            let target_activity = arg_string(&args, 3)?;
            wrap_js_result(|| wasm4pm::performance_spectrum::discover_performance_spectrum_wasm(&eventlog_handle, &activity_key, &timestamp_key, &target_activity))
        }
        "store_dfg_from_json" => {
            let dfg_json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_conformance::store_dfg_from_json(&dfg_json))
        }
        "store_petri_net_from_json" => {
            let pn_json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_conformance::store_petri_net_from_json(&pn_json))
        }
        "streaming_conformance_begin" => {
            let model_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_conformance::streaming_conformance_begin(&model_handle))
        }
        "streaming_conformance_add_event" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            let activity = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::streaming_conformance::streaming_conformance_add_event(&handle, &case_id, &activity))
        }
        "streaming_conformance_close_trace" => {
            let handle = arg_string(&args, 0)?;
            let case_id = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::streaming_conformance::streaming_conformance_close_trace(&handle, &case_id))
        }
        "streaming_conformance_stats" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_conformance::streaming_conformance_stats(&handle))
        }
        "streaming_conformance_finalize" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::streaming_conformance::streaming_conformance_finalize(&handle))
        }
        "check_prefix_conformance" => {
            let model_handle = arg_string(&args, 0)?;
            let prefix_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::streaming_conformance::check_prefix_conformance(&model_handle, &prefix_json))
        }
        "wasm_compute_precision" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let petri_net_handle = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_string_result(|| wasm4pm::etconformance_precision::wasm_compute_precision(&eventlog_handle, &petri_net_handle, &activity_key))
        }
        "predict_next_k" => {
            let model_handle = arg_string(&args, 0)?;
            let prefix_json = arg_string(&args, 1)?;
            let k = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::prediction_next_activity::predict_next_k(&model_handle, &prefix_json, k))
        }
        "predict_beam_paths" => {
            let model_handle = arg_string(&args, 0)?;
            let prefix_json = arg_string(&args, 1)?;
            let beam_width = arg_usize(&args, 2)?;
            let max_steps = arg_usize(&args, 3)?;
            wrap_js_result(|| wasm4pm::prediction_next_activity::predict_beam_paths(&model_handle, &prefix_json, beam_width, max_steps))
        }
        "build_remaining_time_model" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::prediction_remaining_time::build_remaining_time_model(&log_handle, &activity_key, &timestamp_key))
        }
        "predict_case_duration" => {
            let model_handle = arg_string(&args, 0)?;
            let prefix_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction_remaining_time::predict_case_duration(&model_handle, &prefix_json))
        }
        "predict_hazard_rate" => {
            let model_handle = arg_string(&args, 0)?;
            let elapsed_ms = arg_f64(&args, 1)?;
            wrap_js_result(|| wasm4pm::prediction_remaining_time::predict_hazard_rate(&model_handle, elapsed_ms))
        }
        "load_eventlog_from_json" => {
            let content = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::io::load_eventlog_from_json(&content))
        }
        "load_ocel_from_json" => {
            let content = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::io::load_ocel_from_json(&content))
        }
        "export_eventlog_to_json" => {
            let handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::io::export_eventlog_to_json(&handle))
        }
        "export_ocel_to_json" => {
            let handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::io::export_ocel_to_json(&handle))
        }
        "load_ocel_from_xml" => {
            let content = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::io::load_ocel_from_xml(&content))
        }
        "get_ocel_event_count" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_usize_result(|| wasm4pm::io::get_ocel_event_count(&ocel_handle))
        }
        "get_ocel_object_count" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_usize_result(|| wasm4pm::io::get_ocel_object_count(&ocel_handle))
        }
        "get_io_info" => {
            
            Ok(InvokeResult::String(wasm4pm::io::get_io_info()))
        }
        "delete_object" => {
            let id = arg_string(&args, 0)?;
            wrap_bool_result(|| wasm4pm::state::delete_object(&id))
        }
        "object_exists" => {
            let id = arg_string(&args, 0)?;
            Ok(InvokeResult::Bool(wasm4pm::state::object_exists(&id)))
        }
        "object_count" => {
            
            wrap_usize_result(|| wasm4pm::state::object_count())
        }
        "clear_all_objects" => {
            
            wrap_void_result(|| wasm4pm::state::clear_all_objects())
        }
        "load_dfg_from_text" => {
            let content = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::dfg_io::load_dfg_from_text(&content))
        }
        "score_trace_anomaly" => {
            let dfg_handle = arg_string(&args, 0)?;
            let activities_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::anomaly::score_trace_anomaly(&dfg_handle, &activities_json))
        }
        "discover_ml_anomaly" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::anomaly::discover_ml_anomaly(&log_handle, &activity_key))
        }
        "score_log_anomalies" => {
            let log_handle = arg_string(&args, 0)?;
            let dfg_handle = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::anomaly::score_log_anomalies(&log_handle, &dfg_handle, &activity_key))
        }
        "discover_batches_wasm" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let timestamp_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::batches::discover_batches_wasm(&eventlog_handle, &activity_key, &timestamp_key))
        }
        "filter_by_start_activity" => {
            let log_handle = arg_string(&args, 0)?;
            let activities_json = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_start_activity(&log_handle, &activities_json, &activity_key))
        }
        "filter_by_end_activity" => {
            let log_handle = arg_string(&args, 0)?;
            let activities_json = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_end_activity(&log_handle, &activities_json, &activity_key))
        }
        "filter_by_case_size" => {
            let log_handle = arg_string(&args, 0)?;
            let min_events = arg_usize(&args, 1)?;
            let max_events = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_case_size(&log_handle, min_events, max_events))
        }
        "filter_by_directly_follows" => {
            let log_handle = arg_string(&args, 0)?;
            let pairs_json = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_directly_follows(&log_handle, &pairs_json, &activity_key))
        }
        "filter_by_event_attribute_value" => {
            let log_handle = arg_string(&args, 0)?;
            let attribute_key = arg_string(&args, 1)?;
            let attribute_value = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_event_attribute_value(&log_handle, &attribute_key, &attribute_value))
        }
        "filter_by_case_ids" => {
            let log_handle = arg_string(&args, 0)?;
            let case_ids_json = arg_string(&args, 1)?;
            let case_id_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_case_ids(&log_handle, &case_ids_json, &case_id_key))
        }
        "filter_traces_starting_with_sequence" => {
            let log_handle = arg_string(&args, 0)?;
            let sequence_json = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_traces_starting_with_sequence(&log_handle, &sequence_json, &activity_key))
        }
        "filter_traces_ending_with_sequence" => {
            let log_handle = arg_string(&args, 0)?;
            let sequence_json = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_traces_ending_with_sequence(&log_handle, &sequence_json, &activity_key))
        }
        "filter_by_variant_coverage" => {
            let log_handle = arg_string(&args, 0)?;
            let coverage_pct = arg_f64(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_variant_coverage(&log_handle, coverage_pct, &activity_key))
        }
        "filter_by_variants_top_k" => {
            let log_handle = arg_string(&args, 0)?;
            let k = arg_usize(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_variants_top_k(&log_handle, k, &activity_key))
        }
        "filter_traces_containing_activities" => {
            let log_handle = arg_string(&args, 0)?;
            let activities_json = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_traces_containing_activities(&log_handle, &activities_json, &activity_key))
        }
        "filter_traces_excluding_activities" => {
            let log_handle = arg_string(&args, 0)?;
            let activities_json = arg_string(&args, 1)?;
            let activity_key = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_traces_excluding_activities(&log_handle, &activities_json, &activity_key))
        }
        "filter_by_time_range" => {
            let log_handle = arg_string(&args, 0)?;
            let min_dt = arg_string(&args, 1)?;
            let max_dt = arg_string(&args, 2)?;
            let timestamp_key = arg_string(&args, 3)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_time_range(&log_handle, &min_dt, &max_dt, &timestamp_key))
        }
        "filter_by_case_performance" => {
            let log_handle = arg_string(&args, 0)?;
            let min_ms = arg_i64(&args, 1)?;
            let max_ms = arg_i64(&args, 2)?;
            let timestamp_key = arg_string(&args, 3)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_case_performance(&log_handle, min_ms, max_ms, &timestamp_key))
        }
        "filter_rework_traces" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::filters::filter_rework_traces(&log_handle, &activity_key))
        }
        "filter_by_trace_attribute" => {
            let log_handle = arg_string(&args, 0)?;
            let attribute_key = arg_string(&args, 1)?;
            let attribute_value = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::filters::filter_by_trace_attribute(&log_handle, &attribute_key, &attribute_value))
        }
        "load_ocel2_from_json" => {
            let content = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::ocel_io::load_ocel2_from_json(&content))
        }
        "export_ocel2_to_json" => {
            let handle = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::ocel_io::export_ocel2_to_json(&handle))
        }
        "validate_ocel" => {
            let handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::ocel_io::validate_ocel(&handle))
        }
        "query_provenance_traversal" => {
            let ocel_handle = arg_string(&args, 0)?;
            let query_json = arg_string(&args, 1)?;
            wrap_string_result(|| wasm4pm::ocel_io::query_provenance_traversal(&ocel_handle, &query_json))
        }
        "load_ocel2_from_ndjson" => {
            let ndjson = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::ocel_io::load_ocel2_from_ndjson(&ndjson))
        }
        "load_ocel_v2" => {
            let json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::ocel_v2::load_ocel_v2(&json))
        }
        "validate_ocel_v2" => {
            let json = arg_string(&args, 0)?;
            let cardinality_json = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ocel_v2::validate_ocel_v2(&json, &cardinality_json))
        }
        "flatten_ocel_v2" => {
            let json = arg_string(&args, 0)?;
            let object_type = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ocel_v2::flatten_ocel_v2(&json, &object_type))
        }
        "play_out_process_tree" => {
            let tree_json = arg_string(&args, 0)?;
            let root_node_idx = arg_usize(&args, 1)?;
            let params = arg_js_value(&args, 2)?;
            wrap_js_result(|| wasm4pm::playout::play_out_process_tree(&tree_json, root_node_idx, &params))
        }
        "play_out_dfg" => {
            let dfg_json = arg_string(&args, 0)?;
            let params = arg_js_value(&args, 1)?;
            wrap_js_result(|| wasm4pm::playout::play_out_dfg(&dfg_json, &params))
        }
        "from_pnml_wasm" => {
            let pnml_string = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::pnml_io::from_pnml_wasm(&pnml_string))
        }
        "to_pnml_wasm" => {
            let petri_net_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::pnml_io::to_pnml_wasm(&petri_net_handle))
        }
        "discover_alpha_ppp_wasm" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let absolute_df_clean_thresh = arg_usize(&args, 2)?;
            let causal_threshold = arg_f64(&args, 3)?;
            wrap_js_result(|| wasm4pm::advanced::discover_alpha_ppp_wasm(&log_handle, &activity_key, absolute_df_clean_thresh, causal_threshold))
        }
        "discover_ocdfg_wasm" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::advanced::discover_ocdfg_wasm(&ocel_handle))
        }
        "discover_ocla_wasm" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::advanced::discover_ocla_wasm(&ocel_handle))
        }
        "discover_oc_declare_wasm" => {
            let ocel_handle = arg_string(&args, 0)?;
            let noise_threshold = arg_f64(&args, 1)?;
            wrap_js_result(|| wasm4pm::advanced::discover_oc_declare_wasm(&ocel_handle, noise_threshold))
        }
        "analyze_dotted_chart" => {
            let eventlog_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::analysis::analyze_dotted_chart(&eventlog_handle))
        }
        "analyze_event_statistics" => {
            let eventlog_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::analysis::analyze_event_statistics(&eventlog_handle))
        }
        "analyze_ocel_statistics" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::analysis::analyze_ocel_statistics(&ocel_handle))
        }
        "analyze_case_duration" => {
            let eventlog_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::analysis::analyze_case_duration(&eventlog_handle))
        }
        "available_analysis_functions" => {
            
            Ok(InvokeResult::String(wasm4pm::analysis::available_analysis_functions()))
        }
        "dfg_threshold_sweep" => {
            let log_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ensemble::dfg_threshold_sweep(&log_handle, &activity_key))
        }
        "load_ocel_from_csv" => {
            let csv_string = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::ocel_csv::load_ocel_from_csv(&csv_string))
        }
        "parse_powl" => {
            let s = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::powl_api::parse_powl(&s))
        }
        "discover_powl_from_log" => {
            let log_json = arg_string(&args, 0)?;
            let variant = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::powl_api::discover_powl_from_log(&log_json, &variant))
        }
        "discover_powl_from_log_config" => {
            let log_json = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let variant = arg_string(&args, 2)?;
            let min_trace_count = arg_usize(&args, 3)?;
            let noise_threshold = arg_f64(&args, 4)?;
            wrap_js_result(|| wasm4pm::powl_api::discover_powl_from_log_config(&log_json, &activity_key, &variant, min_trace_count, noise_threshold))
        }
        "discover_powl_from_partial_orders" => {
            let log_json = arg_string(&args, 0)?;
            let variant = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::powl_api::discover_powl_from_partial_orders(&log_json, &variant))
        }
        "discover_ocel_powl" => {
            let ocel_json = arg_string(&args, 0)?;
            let variant = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::powl_api::discover_ocel_powl(&ocel_json, &variant))
        }
        "powl_to_svg" => {
            let s = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::powl_to_svg(&s))
        }
        "validate_partial_orders" => {
            let s = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::powl_api::validate_partial_orders(&s))
        }
        "powl_to_string" => {
            let s = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::powl_to_string(&s))
        }
        "simplify_powl" => {
            let s = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::powl_api::simplify_powl(&s))
        }
        "powl_to_bpmn" => {
            let s = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::powl_to_bpmn(&s))
        }
        "token_replay_fitness" => {
            let powl_str = arg_string(&args, 0)?;
            let log_json = arg_string(&args, 1)?;
            wrap_string_result(|| wasm4pm::powl_api::token_replay_fitness(&powl_str, &log_json))
        }
        "check_powl_soundness" => {
            let powl_str = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::check_powl_soundness(&powl_str))
        }
        "check_dg_soundness" => {
            let powl_string = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::check_dg_soundness(&powl_string))
        }
        "footprints_conformance" => {
            let powl_str = arg_string(&args, 0)?;
            let log_json = arg_string(&args, 1)?;
            wrap_string_result(|| wasm4pm::powl_api::footprints_conformance(&powl_str, &log_json))
        }
        "measure_complexity" => {
            let s = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::measure_complexity(&s))
        }
        "powl_freq_analysis" => {
            let s = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::powl_freq_analysis(&s))
        }
        "diff_models" => {
            let model_a_str = arg_string(&args, 0)?;
            let model_b_str = arg_string(&args, 1)?;
            wrap_string_result(|| wasm4pm::powl_api::diff_models(&model_a_str, &model_b_str))
        }
        "powl_footprints" => {
            let s = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::powl_footprints(&s))
        }
        "simplify_frequent_transitions" => {
            let s = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::powl_api::simplify_frequent_transitions(&s))
        }
        "node_to_string" => {
            let s = arg_string(&args, 0)?;
            let arena_idx = arg_usize(&args, 1)?;
            wrap_string_result(|| wasm4pm::powl_api::node_to_string(&s, arena_idx as u32))
        }
        "get_children" => {
            let s = arg_string(&args, 0)?;
            let arena_idx = arg_usize(&args, 1)?;
            wrap_js_result(|| wasm4pm::powl_api::get_children(&s, arena_idx as u32))
        }
        "node_info_json" => {
            let s = arg_string(&args, 0)?;
            let arena_idx = arg_usize(&args, 1)?;
            wrap_string_result(|| wasm4pm::powl_api::node_info_json(&s, arena_idx as u32))
        }
        "powl_to_petri_net" => {
            let s = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::powl_to_petri_net(&s))
        }
        "powl_to_process_tree" => {
            let s = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl_api::powl_to_process_tree(&s))
        }
        "process_tree_to_powl" => {
            let tree_json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::powl_api::process_tree_to_powl(&tree_json))
        }
        "petri_net_to_powl" => {
            let pn_json = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::powl_api::petri_net_to_powl(&pn_json))
        }
        "wasm_mint_challenge_nonce" => {
            
            Ok(InvokeResult::String(wasm4pm::admission::wasm_mint_challenge_nonce()))
        }
        "wasm_admit_change" => {
            let candidate_json_str = arg_string(&args, 0)?;
            let ledger_path = arg_string(&args, 1)?;
            let policy_path = arg_string(&args, 2)?;
            let boundary_map_path = arg_string(&args, 3)?;
            let revocation_path = arg_string(&args, 4)?;
            Ok(InvokeResult::String(wasm4pm::admission::wasm_admit_change(&candidate_json_str, &ledger_path, &policy_path, &boundary_map_path, &revocation_path)))
        }
        "wasm_admit_change_inline" => {
            let candidate_json_str = arg_string(&args, 0)?;
            let ledger_contents = arg_string(&args, 1)?;
            let policy_contents = arg_string(&args, 2)?;
            let boundary_contents = arg_string(&args, 3)?;
            let revoked_contents = arg_string(&args, 4)?;
            Ok(InvokeResult::String(wasm4pm::admission::wasm_admit_change_inline(&candidate_json_str, &ledger_contents, &policy_contents, &boundary_contents, &revoked_contents)))
        }
        "discover_dfg" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::discovery::discover_dfg(&eventlog_handle, &activity_key))
        }
        "discover_ocel_dfg" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::discovery::discover_ocel_dfg(&ocel_handle))
        }
        "discover_ocel_dfg_per_type" => {
            let ocel_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::discovery::discover_ocel_dfg_per_type(&ocel_handle))
        }
        "discover_declare" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::discovery::discover_declare(&eventlog_handle, &activity_key))
        }
        "available_discovery_algorithms" => {
            
            wrap_js_value(|| wasm4pm::discovery::available_discovery_algorithms())
        }
        "discovery_info" => {
            
            wrap_js_value(|| wasm4pm::discovery::discovery_info())
        }
        "check_wf_net_soundness" => {
            let petri_net_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::soundness::check_wf_net_soundness(&petri_net_handle))
        }
        "get_trace_count" => {
            let eventlog_handle = arg_string(&args, 0)?;
            wrap_usize_result(|| wasm4pm::utilities::get_trace_count(&eventlog_handle))
        }
        "get_event_count" => {
            let eventlog_handle = arg_string(&args, 0)?;
            wrap_usize_result(|| wasm4pm::utilities::get_event_count(&eventlog_handle))
        }
        "get_activities" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::utilities::get_activities(&eventlog_handle, &activity_key))
        }
        "get_traces" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::utilities::get_traces(&eventlog_handle, &activity_key))
        }
        "get_activity_frequencies" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::utilities::get_activity_frequencies(&eventlog_handle, &activity_key))
        }
        "get_trace_lengths" => {
            let eventlog_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::utilities::get_trace_lengths(&eventlog_handle))
        }
        "get_trace_length_statistics" => {
            let eventlog_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::utilities::get_trace_length_statistics(&eventlog_handle))
        }
        "get_attribute_names" => {
            let eventlog_handle = arg_string(&args, 0)?;
            wrap_js_result(|| wasm4pm::utilities::get_attribute_names(&eventlog_handle))
        }
        "filter_log_by_activity" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            let activity_name = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::utilities::filter_log_by_activity(&eventlog_handle, &activity_key, &activity_name))
        }
        "filter_log_by_trace_length" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let min_length = arg_usize(&args, 1)?;
            let max_length = arg_usize(&args, 2)?;
            wrap_js_result(|| wasm4pm::utilities::filter_log_by_trace_length(&eventlog_handle, min_length, max_length))
        }
        "calculate_trace_durations" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let timestamp_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::utilities::calculate_trace_durations(&eventlog_handle, &timestamp_key))
        }
        "validate_has_timestamps" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let timestamp_key = arg_string(&args, 1)?;
            wrap_bool_result(|| wasm4pm::utilities::validate_has_timestamps(&eventlog_handle, &timestamp_key))
        }
        "validate_has_activities" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_bool_result(|| wasm4pm::utilities::validate_has_activities(&eventlog_handle, &activity_key))
        }
        "discover_ml_cluster" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ml::clustering::discover_ml_cluster(&eventlog_handle, &activity_key))
        }
        "discover_ml_regress" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ml::regression::discover_ml_regress(&eventlog_handle, &activity_key))
        }
        "discover_ml_regress_automl" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let k_folds = arg_usize(&args, 1)?;
            wrap_js_result(|| wasm4pm::ml::regression::discover_ml_regress_automl(&eventlog_handle, k_folds as u32))
        }
        "discover_ml_forecast" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ml::forecasting::discover_ml_forecast(&eventlog_handle, &activity_key))
        }
        "discover_ml_classify" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ml::classification::discover_ml_classify(&eventlog_handle, &activity_key))
        }
        "discover_ml_pca" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ml::pca::discover_ml_pca(&eventlog_handle, &activity_key))
        }
        "discover_automl_forecast" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ml::automl::discover_automl_forecast(&eventlog_handle, &activity_key))
        }
        "discover_automl_classify" => {
            let eventlog_handle = arg_string(&args, 0)?;
            let activity_key = arg_string(&args, 1)?;
            wrap_js_result(|| wasm4pm::ml::automl::discover_automl_classify(&eventlog_handle, &activity_key))
        }
        "powl_extensive_playout" => {
            let powl_model_str = arg_string(&args, 0)?;
            let root_id = arg_string(&args, 1)?;
            let config_json = arg_string(&args, 2)?;
            wrap_js_result(|| wasm4pm::powl::extensive_playout::powl_extensive_playout(&powl_model_str, &root_id, &config_json))
        }
        "powl_to_yawl_string" => {
            let powl_string = arg_string(&args, 0)?;
            wrap_string_result(|| wasm4pm::powl::conversion::to_yawl::powl_to_yawl_string(&powl_string))
        }
        other => Err(format!("unknown export: {other}")),
    }
}

pub fn list_export_names() -> &'static [&'static str] {
    &[
        "rl_orchestrator_reset",
        "rl_orchestrator_active_agent",
        "circuit_breaker_get_state",
        "circuit_breaker_set_state",
        "circuit_breaker_configure",
        "circuit_breaker_get_config",
        "circuit_breaker_reset",
        "run_agentic_pipeline",
        "validate_agentic_handoff",
        "evaluate_agentic_counterfactuals",
        "run_agentic_jtbd_suite",
        "rl_orchestrator_switch_agent",
        "rl_orchestrator_set_linucb",
        "rl_orchestrator_telemetry",
        "rl_orchestrator_get_telemetry",
        "serialize_rl_state",
        "restore_rl_state",
        "get_spc_history",
        "set_spc_history",
        "truex_verify_receipt",
        "evaluate_ocpq",
        "init",
        "get_version",
        "get_capabilities",
        "clear_all_caches",
        "get_cache_stats",
        "set_drift_thresholds",
        "get_drift_thresholds",
        "reset_drift_thresholds",
        "simd_token_replay",
        "autonomic_execute_cycle",
        "discover_footprints",
        "discover_alpha_plus_plus",
        "discover_dfg_filtered",
        "export_dfg_to_json",
        "export_petri_net_to_json",
        "compute_optimal_alignments",
        "compute_alignments",
        "monte_carlo_simulation",
        "build_ngram_predictor",
        "predict_next_activity",
        "score_trace_likelihood",
        "cache_stats",
        "hash_xes_content",
        "jaccard_distance",
        "ewma_series",
        "identify_high_variance_activities",
        "wf_net_to_powl",
        "load_eventlog_from_xes",
        "load_eventlog_from_xes_cached",
        "export_eventlog_to_xes",
        "xes_format_info",
        "read_bpmn",
        "check_token_based_replay",
        "conformance_info",
        "discover_prefix_tree",
        "load_powl_from_string",
        "load_powl_v2_from_string",
        "discover_causal_alpha",
        "discover_causal_heuristic",
        "check_data_quality",
        "check_ocel_data_quality",
        "infer_eventlog_schema",
        "infer_ocel_schema",
        "discover_dfg_hierarchical",
        "discover_dfg_hierarchical_by_events",
        "discover_oc_petri_net",
        "oc_petri_net_info",
        "list_ocel_object_types",
        "get_ocel_type_statistics",
        "flatten_ocel_to_eventlog",
        "measure_ocel_flattening_loss",
        "validate_process_tree",
        "discover_simple_process_tree",
        "smart_engine_create",
        "smart_engine_create_with_params",
        "smart_engine_run",
        "smart_engine_converged",
        "smart_engine_cache_stats",
        "smart_engine_check_convergence",
        "smart_engine_reset",
        "smart_engine_destroy",
        "wasm_compute_simplicity",
        "discover_ilp_petri_net",
        "discover_optimized_dfg",
        "ilp_discovery_info",
        "encode_dfg_as_text",
        "encode_variants_as_text",
        "encode_statistics_as_text",
        "encode_conformance_as_text",
        "encode_bottlenecks_as_text",
        "encode_petri_net_as_text",
        "encode_ocel_as_text",
        "encode_oc_petri_net_as_text",
        "encode_model_comparison_as_text",
        "encode_ocel_summary_as_text",
        "discover_astar",
        "discover_hill_climbing",
        "analyze_trace_variants",
        "mine_sequential_patterns",
        "detect_concept_drift",
        "cluster_traces",
        "analyze_start_end_activities",
        "analyze_activity_cooccurrence",
        "fast_discovery_info",
        "generalization",
        "register_model",
        "get_model",
        "discover_inductive_miner",
        "discover_ant_colony",
        "discover_simulated_annealing",
        "extract_process_skeleton",
        "analyze_activity_dependencies",
        "analyze_case_attributes",
        "more_discovery_info",
        "oc_conformance_check",
        "oc_conformance_info",
        "analyze_oc_performance",
        "oc_performance_analysis",
        "oc_performance_info",
        "powl_execute",
        "discover_handover_network",
        "discover_working_together_network",
        "compute_network_metrics",
        "compute_clustering_coefficient",
        "detect_communities",
        "streaming_dfg_begin",
        "streaming_dfg_add_event",
        "streaming_dfg_add_batch",
        "streaming_dfg_close_trace",
        "streaming_skeleton_finalize",
        "streaming_heuristic_begin",
        "streaming_heuristic_add_event",
        "streaming_heuristic_close_trace",
        "streaming_heuristic_snapshot",
        "streaming_heuristic_finalize",
        "streaming_info",
        "streaming_dfg_flush_open",
        "streaming_dfg_snapshot",
        "streaming_dfg_finalize",
        "streaming_dfg_stats",
        "streaming_skeleton_begin",
        "streaming_skeleton_add_event",
        "streaming_skeleton_close_trace",
        "streaming_skeleton_snapshot",
        "analyze_variant_complexity",
        "compute_activity_transition_matrix",
        "analyze_process_speedup",
        "compute_trace_similarity_matrix",
        "analyze_temporal_bottlenecks",
        "extract_activity_ordering",
        "final_analytics_info",
        "new_streaming_dfg",
        "streaming_dfg_process_event",
        "streaming_dfg_end_trace",
        "incremental_dfg_snapshot",
        "incremental_dfg_stats",
        "streaming_dfg_string_new",
        "streaming_dfg_string_event",
        "streaming_dfg_string_end_trace",
        "streaming_dfg_string_snapshot",
        "discover_performance_dfg",
        "generate_recommendations",
        "recommendations_info",
        "detect_drift",
        "compute_ewma",
        "discover_temporal_profile",
        "check_temporal_conformance",
        "alignment_fitness",
        "conformance_cache_new",
        "conformance_cache_get",
        "conformance_cache_insert",
        "conformance_cache_stats",
        "conformance_cache_clear",
        "conformance_cache_hash_model",
        "discover_correlation",
        "discover_genetic_algorithm",
        "discover_pso_algorithm",
        "discover_aco_algorithm",
        "genetic_discovery_info",
        "parallel_discover_dfg",
        "parallel_run_algorithms",
        "parallel_available",
        "petri_net_playout",
        "analyze_resource_utilization",
        "analyze_resource_activity_matrix",
        "identify_resource_bottlenecks",
        "discover_transition_system_from_handle",
        "extract_case_features",
        "extract_prefix_features",
        "export_features_csv",
        "export_features_json",
        "compute_feature_importance",
        "global_feature_importance",
        "score_anomaly",
        "compute_boundary_coverage",
        "compute_trace_likelihood",
        "predict_outcome_wasm",
        "discover_dfg_simd",
        "discover_dfg_simd_handle",
        "simd_streaming_dfg_info",
        "pipeline_begin",
        "pipeline_add_event",
        "pipeline_close_trace",
        "pipeline_stats",
        "pipeline_snapshot",
        "pipeline_finalize",
        "discover_heuristic_miner",
        "analyze_infrequent_paths",
        "detect_rework",
        "detect_bottlenecks",
        "compute_model_metrics",
        "advanced_algorithms_info",
        "align_etconformance_precision",
        "get_capability_registry",
        "check_declare_conformance",
        "store_declare_from_json",
        "wasm_reduce_petri_net",
        "extract_prefix_features_wasm",
        "compute_rework_score",
        "build_transition_probabilities",
        "estimate_queue_delay",
        "rank_interventions",
        "select_intervention",
        "discover_performance_spectrum_wasm",
        "store_dfg_from_json",
        "store_petri_net_from_json",
        "streaming_conformance_begin",
        "streaming_conformance_add_event",
        "streaming_conformance_close_trace",
        "streaming_conformance_stats",
        "streaming_conformance_finalize",
        "check_prefix_conformance",
        "wasm_compute_precision",
        "predict_next_k",
        "predict_beam_paths",
        "build_remaining_time_model",
        "predict_case_duration",
        "predict_hazard_rate",
        "load_eventlog_from_json",
        "load_ocel_from_json",
        "export_eventlog_to_json",
        "export_ocel_to_json",
        "load_ocel_from_xml",
        "get_ocel_event_count",
        "get_ocel_object_count",
        "get_io_info",
        "delete_object",
        "object_exists",
        "object_count",
        "clear_all_objects",
        "load_dfg_from_text",
        "score_trace_anomaly",
        "discover_ml_anomaly",
        "score_log_anomalies",
        "discover_batches_wasm",
        "filter_by_start_activity",
        "filter_by_end_activity",
        "filter_by_case_size",
        "filter_by_directly_follows",
        "filter_by_event_attribute_value",
        "filter_by_case_ids",
        "filter_traces_starting_with_sequence",
        "filter_traces_ending_with_sequence",
        "filter_by_variant_coverage",
        "filter_by_variants_top_k",
        "filter_traces_containing_activities",
        "filter_traces_excluding_activities",
        "filter_by_time_range",
        "filter_by_case_performance",
        "filter_rework_traces",
        "filter_by_trace_attribute",
        "load_ocel2_from_json",
        "export_ocel2_to_json",
        "validate_ocel",
        "query_provenance_traversal",
        "load_ocel2_from_ndjson",
        "load_ocel_v2",
        "validate_ocel_v2",
        "flatten_ocel_v2",
        "play_out_process_tree",
        "play_out_dfg",
        "from_pnml_wasm",
        "to_pnml_wasm",
        "discover_alpha_ppp_wasm",
        "discover_ocdfg_wasm",
        "discover_ocla_wasm",
        "discover_oc_declare_wasm",
        "analyze_dotted_chart",
        "analyze_event_statistics",
        "analyze_ocel_statistics",
        "analyze_case_duration",
        "available_analysis_functions",
        "dfg_threshold_sweep",
        "load_ocel_from_csv",
        "parse_powl",
        "discover_powl_from_log",
        "discover_powl_from_log_config",
        "discover_powl_from_partial_orders",
        "discover_ocel_powl",
        "powl_to_svg",
        "validate_partial_orders",
        "powl_to_string",
        "simplify_powl",
        "powl_to_bpmn",
        "token_replay_fitness",
        "check_powl_soundness",
        "check_dg_soundness",
        "footprints_conformance",
        "measure_complexity",
        "powl_freq_analysis",
        "diff_models",
        "powl_footprints",
        "simplify_frequent_transitions",
        "node_to_string",
        "get_children",
        "node_info_json",
        "powl_to_petri_net",
        "powl_to_process_tree",
        "process_tree_to_powl",
        "petri_net_to_powl",
        "wasm_mint_challenge_nonce",
        "wasm_admit_change",
        "wasm_admit_change_inline",
        "discover_dfg",
        "discover_ocel_dfg",
        "discover_ocel_dfg_per_type",
        "discover_declare",
        "available_discovery_algorithms",
        "discovery_info",
        "check_wf_net_soundness",
        "get_trace_count",
        "get_event_count",
        "get_activities",
        "get_traces",
        "get_activity_frequencies",
        "get_trace_lengths",
        "get_trace_length_statistics",
        "get_attribute_names",
        "filter_log_by_activity",
        "filter_log_by_trace_length",
        "calculate_trace_durations",
        "validate_has_timestamps",
        "validate_has_activities",
        "discover_ml_cluster",
        "discover_ml_regress",
        "discover_ml_regress_automl",
        "discover_ml_forecast",
        "discover_ml_classify",
        "discover_ml_pca",
        "discover_automl_forecast",
        "discover_automl_classify",
        "powl_extensive_playout",
        "powl_to_yawl_string",
    ]
}
