// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/30-capabilities.ttl
// via queries/accessibility-capabilities.rq (TICKET-019). Do not hand-edit -- edit the ontology.

export interface AccessibilityState {
  "accessibility/augmentative-communication-projection"?: unknown; // augmentative communication projection
  "accessibility/braille-display-output"?: unknown; // Braille-display output
  "accessibility/caption-driven-operation"?: unknown; // caption-driven operation
  "accessibility/configurable-information-density"?: unknown; // configurable information density
  "accessibility/controllable-audio-retention"?: unknown; // controllable audio retention
  "accessibility/controllable-transcript-retention"?: unknown; // controllable transcript retention
  "accessibility/extended-processing-time-mode"?: unknown; // extended processing-time mode
  "accessibility/high-contrast-projection"?: unknown; // high-contrast projection
  "accessibility/keyboard-only-operation"?: unknown; // keyboard-only operation
  "accessibility/magnified-single-cue-projection"?: unknown; // magnified single-cue projection
  "accessibility/non-color-dependent-status"?: unknown; // non-color-dependent status
  "accessibility/reduced-motion-mode"?: unknown; // reduced-motion mode
  "accessibility/screen-reader-semantic-regions"?: unknown; // screen-reader semantic regions
  "accessibility/stable-layout-mode"?: unknown; // stable-layout mode
  "accessibility/text-to-speech-projection"?: unknown; // text-to-speech projection
  "accessibility/zero-motor-input-operation"?: unknown; // zero-motor-input operation
}

export const ACCESSIBILITY_STATE_FIELD_COUNT = 16;
