// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/30-capabilities.ttl
// via queries/hydra-operations.rq (TICKET-027). Do not hand-edit -- edit the ontology.
import type { CapabilityRequest, CapabilityResponse } from "./capability";

/** The hydra:Operation-typed capability ids -- the HTTP-shaped subset. */
export type HttpCapabilityId =
  | "capability/editor/create-file"
  | "capability/editor/modify-file"
  | "capability/editor/open-file"
  | "capability/runtime/compile"
  | "capability/runtime/execute"
  | "capability/session/create-session"
  | "capability/verification/run-complete-test-suite"
  | "capability/verification/run-hidden-test"
  | "capability/verification/run-visible-test"
;

export type CapabilityHandler<C extends HttpCapabilityId = HttpCapabilityId> = (
  req: CapabilityRequest<C>
) => Promise<CapabilityResponse>;

/** One typed slot per hydra:Operation capability. Slots are populated by
 * workstream H's custom adapters at integration time; this file only
 * declares the typed table shape.
 */
export const CAPABILITY_DISPATCH: Record<HttpCapabilityId, CapabilityHandler | undefined> = {
  "capability/editor/create-file": undefined, // POST — create file
  "capability/editor/modify-file": undefined, // POST — modify file
  "capability/editor/open-file": undefined, // GET — open file
  "capability/runtime/compile": undefined, // POST — compile
  "capability/runtime/execute": undefined, // POST — execute
  "capability/session/create-session": undefined, // POST — create session
  "capability/verification/run-complete-test-suite": undefined, // POST — run complete test suite
  "capability/verification/run-hidden-test": undefined, // POST — run hidden test
  "capability/verification/run-visible-test": undefined, // POST — run visible test
};

export const HTTP_CAPABILITY_COUNT = 9;
