// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/40-events-workflow.ttl
// via queries/transition-plans.rq + queries/refusal-wildcard.rq (TICKET-021).
// Do not hand-edit -- edit the ontology.
//
// 13 admitted transition-plan/* edges (schema:object -> schema:result,
// the normal forward path plus the one documented debugging->implementation
// backward edge) plus 12 REFUSAL_WILDCARD_SOURCES (phase/refused's
// skos:related set -- REFUSED is reachable from any non-terminal phase; COMPLETE
// and REFUSED itself are excluded since they are terminal).
import type { Phase } from "./phase";


/** Legal next phases per phase, from the 13 admitted transition-plan
 * edges. Partial: phases with zero outgoing transition-plan edges (COMPLETE,
 * REFUSED -- both terminal) are simply absent, not present with an empty array,
 * and are treated as "no edges" by isLegalTransition() below. Does NOT include
 * the REFUSED wildcard target -- that is handled separately per the
 * reachable-from-any-non-terminal-phase rule documented on phase/refused. */
export const PHASE_TRANSITIONS: Partial<Record<Phase, readonly Phase[]>> = {
  "CLARIFICATION": ["PLANNING"],
  "CREATED": ["PREPARING"],
  "DEBUGGING": ["EXPLANATION", "IMPLEMENTATION"],
  "EXECUTION": ["DEBUGGING"],
  "EXPLANATION": ["FOLLOW_UP"],
  "FOLLOW_UP": ["COMPLETE"],
  "IMPLEMENTATION": ["EXECUTION"],
  "INTRODUCTION": ["PROBLEM_PRESENTATION"],
  "PLANNING": ["IMPLEMENTATION"],
  "PREPARING": ["READY"],
  "PROBLEM_PRESENTATION": ["CLARIFICATION"],
  "READY": ["INTRODUCTION"],
};

/** 12-member wildcard set: non-terminal phases from which
 * REFUSED is always reachable (phase/refused's skos:related, ARD Section 11). */
export const REFUSAL_WILDCARD_SOURCES: readonly Phase[] = [
  "CLARIFICATION",
  "CREATED",
  "DEBUGGING",
  "EXECUTION",
  "EXPLANATION",
  "FOLLOW_UP",
  "IMPLEMENTATION",
  "INTRODUCTION",
  "PLANNING",
  "PREPARING",
  "PROBLEM_PRESENTATION",
  "READY",
] as const;

/**
 * True iff `to` is reachable from `from` via an admitted transition-plan
 * edge, or `to` is REFUSED and `from` is one of the 12
 * REFUSAL_WILDCARD_SOURCES (the documented wildcard-refusal rule). Every
 * other pair -- including `from === to` and any phase not covered above --
 * returns false. This is NOT a permissive any-to-any pass-through.
 */
export function isLegalTransition(from: Phase, to: Phase): boolean {
  if (to === "REFUSED") {
    return REFUSAL_WILDCARD_SOURCES.includes(from);
  }
  const targets = PHASE_TRANSITIONS[from] ?? [];
  return targets.includes(to);
}
