// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/30-capabilities.ttl
// dcterms:requires edges via queries/capability-preconditions.rq (TICKET-028).
// Do not hand-edit -- edit the ontology.
import type { CapabilityId } from "./capability";


/** Direct (non-transitive) dcterms:requires edges per capability, as admitted. */
export const DIRECT_REQUIRES: Partial<Record<CapabilityId, readonly CapabilityId[]>> = {
  "capability/cognition/classify-question-family": ["capability/cognition/detect-speech-act"],
  "capability/cognition/construct-answer-scaffold": ["capability/cognition/rank-solution-families"],
  "capability/cognition/detect-missing-explanation": ["capability/cognition/mark-concept-covered"],
  "capability/cognition/maintain-parallel-hypotheses": ["capability/cognition/classify-question-family"],
  "capability/cognition/predict-likely-follow-up": ["capability/cognition/maintain-parallel-hypotheses"],
  "capability/cognition/rank-solution-families": ["capability/cognition/maintain-parallel-hypotheses"],
  "capability/editor/delete-file": ["capability/editor/create-file"],
  "capability/editor/modify-file": ["capability/editor/create-file"],
  "capability/editor/rename-file": ["capability/editor/create-file"],
  "capability/governance/authorize-recording": ["capability/governance/declare-assistance-policy"],
  "capability/governance/authorize-retention": ["capability/governance/declare-assistance-policy"],
  "capability/governance/declare-allowed-knowledge-sources": ["capability/governance/declare-assistance-policy"],
  "capability/governance/declare-allowed-sensors": ["capability/governance/declare-assistance-policy"],
  "capability/governance/declare-permitted-projections": ["capability/governance/declare-assistance-policy"],
  "capability/governance/declare-prohibited-actions": ["capability/governance/declare-assistance-policy"],
  "capability/governance/produce-policy-receipt": ["capability/governance/declare-assistance-policy"],
  "capability/governance/produce-session-receipt": ["capability/session/end-interview"],
  "capability/problem/apply-requirement-delta": ["capability/problem/load-problem-statement"],
  "capability/problem/extract-constraints": ["capability/problem/load-problem-statement"],
  "capability/problem/parse-examples": ["capability/problem/load-problem-statement"],
  "capability/runtime/capture-exit-status": ["capability/runtime/execute"],
  "capability/runtime/capture-standard-error": ["capability/runtime/execute"],
  "capability/runtime/capture-standard-output": ["capability/runtime/execute"],
  "capability/runtime/compile": ["capability/runtime/select-language"],
  "capability/runtime/enforce-memory-limit": ["capability/runtime/execute"],
  "capability/runtime/enforce-timeout": ["capability/runtime/execute"],
  "capability/runtime/execute": ["capability/runtime/compile"],
  "capability/runtime/provide-standard-input": ["capability/runtime/execute"],
  "capability/runtime/select-language-version": ["capability/runtime/select-language"],
  "capability/runtime/terminate-process": ["capability/runtime/execute"],
  "capability/session/end-interview": ["capability/session/start-interview"],
  "capability/session/join-session": ["capability/session/create-session"],
  "capability/session/pause-interview": ["capability/session/start-interview"],
  "capability/session/replay-session": ["capability/session/record-event-provenance"],
  "capability/session/start-interview": ["capability/session/create-session"],
  "capability/verification/calculate-coverage": ["capability/verification/run-complete-test-suite"],
  "capability/verification/replay-execution": ["capability/session/replay-session"],
  "capability/verification/run-complete-test-suite": ["capability/verification/run-hidden-test", "capability/verification/run-visible-test"],
  "capability/verification/run-example": ["capability/runtime/execute"],
  "capability/verification/run-focused-test": ["capability/runtime/execute"],
  "capability/verification/run-hidden-test": ["capability/runtime/execute"],
  "capability/verification/run-visible-test": ["capability/runtime/execute"],
};

/** Transitive closure of dcterms:requires for a capability, computed at call
 * time (not pre-flattened) so a fixture-added edge is picked up without
 * regenerating this file.
 */
export function transitiveRequires(capabilityId: CapabilityId): CapabilityId[] {
  const seen = new Set<CapabilityId>();
  const stack: CapabilityId[] = [...(DIRECT_REQUIRES[capabilityId] ?? [])];
  while (stack.length > 0) {
    const next = stack.pop() as CapabilityId;
    if (seen.has(next)) continue;
    seen.add(next);
    for (const r of DIRECT_REQUIRES[next] ?? []) stack.push(r);
  }
  return [...seen];
}

/** State = set of capability ids already satisfied/completed in this session. */
export type CapabilityState = ReadonlySet<CapabilityId>;

export interface PreconditionResult {
  met: boolean;
  missing: CapabilityId[];
}

export function checkPreconditions(
  capabilityId: CapabilityId,
  state: CapabilityState
): PreconditionResult {
  const required = transitiveRequires(capabilityId);
  const missing = required.filter((r) => !state.has(r));
  return { met: missing.length === 0, missing };
}
