// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/30-capabilities.ttl
// via queries/problem-capabilities.rq (TICKET-018). Do not hand-edit -- edit the ontology.
//
// One optional field per capability/problem/* resource, keyed by its relative IRI path
// (quoted string key -- avoids inventing a camelCase-derivation heuristic not present in the
// admitted graph). Field VALUE is unknown -- populated at runtime by the capability's handler.

export interface ProblemState {
  "problem/apply-requirement-delta"?: unknown; // apply requirement delta
  "problem/extract-constraints"?: unknown; // extract constraints
  "problem/identify-input-format"?: unknown; // identify input format
  "problem/identify-output-format"?: unknown; // identify output format
  "problem/identify-performance-target"?: unknown; // identify performance target
  "problem/identify-prohibited-operations"?: unknown; // identify prohibited operations
  "problem/identify-required-function-signature"?: unknown; // identify required function signature
  "problem/load-problem-statement"?: unknown; // load problem statement
  "problem/parse-examples"?: unknown; // parse examples
  "problem/reveal-clarification"?: unknown; // reveal clarification
  "problem/reveal-hidden-condition"?: unknown; // reveal hidden condition
}

export const PROBLEM_STATE_FIELD_COUNT = 11;
