// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/60-provenance-receipts.ttl
// (TICKET-020). Interface shape matches the real predicate set observed on the
// 2 receipt/* prov:Entity resources (prov:used, prov:generated,
// prov:wasDerivedFrom, dcterms:relation, spdx:checksum/algorithm/checksumValue) --
// not an idealized PROV-O schema. Do not hand-edit -- edit the ontology.

export interface Checksum {
  algorithm: "BLAKE3";
  checksumValue: string;
}

export interface TransitionReceipt {
  label?: string;
  used: string[];
  generated?: string;
  derivedFrom?: string;
  relation?: string;
  checksum: Checksum;
}

export const RECEIPT_ENTRY_COUNT = 2;
