// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/20-requirements.ttl
// via queries/refusal-codes.rq (TICKET-017). Do not hand-edit -- edit the ontology.

/** 16-member union of ARD Section 11's refusal taxonomy codes. */
export type RefusalCode =
  | "HIDDEN_TEST_INTEGRITY_FAILED"
  | "INACCESSIBLE_PROJECTION"
  | "INSUFFICIENT_CLASSIFICATION_EVIDENCE"
  | "INVALID_PROBLEM_SPEC"
  | "NONDETERMINISTIC_REPLAY"
  | "PACK_VALIDATION_FAILED"
  | "SANDBOX_ESCAPE_DETECTED"
  | "SANDBOX_MEMORY_LIMIT"
  | "SANDBOX_TIMEOUT"
  | "STALE_SESSION_EVENT"
  | "UNAUTHORIZED_EXECUTION"
  | "UNAUTHORIZED_RECORDING"
  | "UNAUTHORIZED_SENSOR"
  | "UNSUPPORTED_LANGUAGE"
  | "UNSUPPORTED_PERSONAL_CLAIM"
  | "UNSUPPORTED_RUNTIME"
;

export const REFUSAL_CODES: readonly RefusalCode[] = [
  "HIDDEN_TEST_INTEGRITY_FAILED",
  "INACCESSIBLE_PROJECTION",
  "INSUFFICIENT_CLASSIFICATION_EVIDENCE",
  "INVALID_PROBLEM_SPEC",
  "NONDETERMINISTIC_REPLAY",
  "PACK_VALIDATION_FAILED",
  "SANDBOX_ESCAPE_DETECTED",
  "SANDBOX_MEMORY_LIMIT",
  "SANDBOX_TIMEOUT",
  "STALE_SESSION_EVENT",
  "UNAUTHORIZED_EXECUTION",
  "UNAUTHORIZED_RECORDING",
  "UNAUTHORIZED_SENSOR",
  "UNSUPPORTED_LANGUAGE",
  "UNSUPPORTED_PERSONAL_CLAIM",
  "UNSUPPORTED_RUNTIME",
] as const;

export const REFUSAL_CODE_COUNT = 16;

/** Refusal is a first-class outcome (Architecture Decision 13) -- never a thrown exception. */
export type AdmissionResult<T> =
  | { status: "admitted"; value: T }
  | { status: "refused"; code: RefusalCode; reason?: string };
