// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/20-requirements.ttl
// ARD §10 performance-target resources via queries/performance-targets.rq (TICKET-029).
// Do not hand-edit -- edit the ontology.
import type { CapabilityId } from "./capability";

export interface PerformanceTarget {
  id: string;
  title: string;
  value: string;
}

/** All 7 ARD §10 performance-target resources, admitted verbatim. */
export const PERFORMANCE_TARGETS: readonly PerformanceTarget[] = [
  { id: "req/ard-perf-compile-dispatch", title: "Compile dispatch < 50ms", value: "compile dispatch < 50 ms" },
  { id: "req/ard-perf-editor-admission", title: "Editor event admission < 25ms", value: "editor event admission < 25 ms" },
  { id: "req/ard-perf-first-projection", title: "First projection after stable event < 250ms", value: "first projection after stable event < 250 ms" },
  { id: "req/ard-perf-hypothesis-update", title: "Hypothesis update < 50ms", value: "hypothesis update < 50 ms" },
  { id: "req/ard-perf-replay-divergence", title: "Zero session replay divergence", value: "session replay divergence 0" },
  { id: "req/ard-perf-rule-evaluation", title: "Rule evaluation < 25ms", value: "rule evaluation < 25 ms" },
  { id: "req/ard-perf-semantic-retrieval", title: "Semantic retrieval < 50ms", value: "semantic retrieval < 50 ms" },
];

/**
 * None of ARD §10's performance-target resources name a per-capability
 * timeout figure directly usable as an execution bound -- they are latency
 * budgets for pipeline stages, not a candidate-code execution wall-clock
 * cap. This documents an explicit, reviewable default pending an ARD
 * addition that specifies one.
 */
export const DEFAULT_CAPABILITY_TIMEOUT_MS = 10_000;

export type TimeoutRefusalCode = "capability/runtime/enforce-timeout";
export const TIMEOUT_REFUSAL_CODE: TimeoutRefusalCode = "capability/runtime/enforce-timeout";

export interface AdmissionResult<R = unknown> {
  status: "ok" | "refused";
  result?: R;
  refusal?: TimeoutRefusalCode;
  elapsedMs: number;
}

/**
 * Wrap a capability handler with a bounded-execution timeout. Genuinely
 * races the handler against a timer; does NOT itself kill underlying work --
 * TICKET-035's subprocess executor owns the actual process-kill side effect.
 */
export async function withTimeout<R>(
  _capabilityId: CapabilityId,
  fn: () => Promise<R>,
  timeoutMs: number = DEFAULT_CAPABILITY_TIMEOUT_MS
): Promise<AdmissionResult<R>> {
  const start = Date.now();
  let timer: ReturnType<typeof setTimeout>;
  const timeout = new Promise<AdmissionResult<R>>((resolve) => {
    timer = setTimeout(() => {
      resolve({ status: "refused", refusal: TIMEOUT_REFUSAL_CODE, elapsedMs: Date.now() - start });
    }, timeoutMs);
  });
  const work = fn().then((result): AdmissionResult<R> => ({
    status: "ok",
    result,
    elapsedMs: Date.now() - start,
  }));
  try {
    return await Promise.race([work, timeout]);
  } finally {
    clearTimeout(timer!);
  }
}
