// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/30-capabilities.ttl
// via queries/cognition-capabilities.rq (TICKET-018). Do not hand-edit -- edit the ontology.

export interface TrackCandidateEvidence {
  "cognition/abstain-under-insufficient-evidence"?: unknown; // abstain under insufficient evidence
  "cognition/classify-question-family"?: unknown; // classify question family
  "cognition/construct-answer-scaffold"?: unknown; // construct answer scaffold
  "cognition/detect-missing-explanation"?: unknown; // detect missing explanation
  "cognition/detect-speech-act"?: unknown; // detect speech act
  "cognition/detect-topic-transition"?: unknown; // detect topic transition
  "cognition/infer-current-debugging-state"?: unknown; // infer current debugging state
  "cognition/maintain-parallel-hypotheses"?: unknown; // maintain parallel hypotheses
  "cognition/mark-concept-covered"?: unknown; // mark concept covered
  "cognition/predict-likely-follow-up"?: unknown; // predict likely follow-up
  "cognition/preserve-unresolved-residue"?: unknown; // preserve unresolved residue
  "cognition/rank-solution-families"?: unknown; // rank solution families
  "cognition/retrieve-candidate-evidence"?: unknown; // retrieve candidate evidence
}

export interface TrackCandidate {
  id: string;
  rank: number;
  evidence: TrackCandidateEvidence;
}

export const TRACK_CANDIDATE_FIELD_COUNT = 13;
