// GENERATED by ggen sync from packs/wasm4pm-interview-assist-pack/ontology/30-capabilities.ttl
// via queries/verification-capabilities.rq (TICKET-019). Do not hand-edit -- edit the ontology.

export interface VerificationState {
  "verification/calculate-complexity-evidence"?: unknown; // calculate complexity evidence
  "verification/calculate-coverage"?: unknown; // calculate coverage
  "verification/compare-implementations"?: unknown; // compare implementations
  "verification/detect-nondeterminism"?: unknown; // detect nondeterminism
  "verification/generate-candidate-test"?: unknown; // generate candidate test
  "verification/generate-property"?: unknown; // generate property
  "verification/mutate-implementation"?: unknown; // mutate implementation
  "verification/replay-execution"?: unknown; // replay execution
  "verification/run-complete-test-suite"?: unknown; // run complete test suite
  "verification/run-example"?: unknown; // run example
  "verification/run-focused-test"?: unknown; // run focused test
  "verification/run-hidden-test"?: unknown; // run hidden test
  "verification/run-visible-test"?: unknown; // run visible test
}

export const VERIFICATION_STATE_FIELD_COUNT = 13;
