
// Generated by ggen from compat:Story hello-world-print (packs/story-pack).
// Runs the story's real program (storyRunCommand) as a real child process
// and asserts its real captured stdout against the story's real
// exampleOutputItem values -- not a stub, not a mock.
//
// Run standalone: node --test stories/hello-world-print.test.mjs
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const runCommand = "sh stories/hello-world-print.sh";
const expectedLines = [
  "hello world.",
];

describe("Hello World Print", () => {
  it("Print the approved observable output", () => {
    const stdout = execSync(runCommand, { cwd: repoRoot, encoding: "utf8" });
    const actualLines = stdout.replace(/\n$/, "").split("\n");
    assert.deepEqual(actualLines, expectedLines);
  });
});
