#![allow(missing_docs)]
//! Breed dispatch. Routing flows through the `breed_instance` static table
//! generated by the `breeds!` macro in `mod.rs` — one greppable entry per
//! breed (variant, string id, module path on a single line; the integrator
//! unions entries across tiers exactly as it did match arms). Unimplemented
//! registry ids return an "unsupported breed" error before the enum match.

use crate::breeds::{breed_instance, BreedId, BreedInput, BreedOutput, CognitionBreed};

/// Run a breed through its full lifecycle: preconditions → run → postconditions.
///
/// Enforces the `CognitionBreed` contract:
/// - `preconditions` must pass before execution begins (TPS fail-fast).
/// - `postconditions` must pass after execution (FM-5 fraud guard: empty
///   inference_trace is rejected as proof that real work did not occur).
pub fn run_breed(b: &dyn CognitionBreed, input: &BreedInput) -> Result<BreedOutput, String> {
    b.preconditions(input)
        .map_err(|e| format!("{}: precondition failed: {}", b.id(), e))?;
    let mut output = b
        .run(input)
        .map_err(|e| format!("{}: {}", e.breed, e.message))?;
    // Framework-level FM-5 gate: a breed cannot claim success without an
    // inference trace, independent of its own postconditions.
    if output.inference_trace.is_empty() {
        return Err(format!(
            "{}: empty inference trace (FM-5 fraud signal, framework gate)",
            b.id()
        ));
    }
    b.postconditions(input, &output)
        .map_err(|e| format!("{}: postcondition failed: {}", b.id(), e))?;

    // Derive OCEL and validate conformance (van der Aalst doctrine)
    let breed_id = format!("{}", b.id());
    let trace_str = serde_json::to_string(&output.inference_trace).unwrap_or_default();
    let tmp_run_id = blake3::hash(trace_str.as_bytes()).to_hex().to_string();
    let ocel_log = crate::ocel::derive_ocel(&breed_id, &tmp_run_id, &output.inference_trace);

    if let Some(model) = crate::ocel::lifecycle_model_for(&breed_id) {
        let conformance = crate::ocel::validate_ocel_alignment(&ocel_log, model);
        if !conformance.is_conforming {
            return Err(format!(
                "{}: OCEL conformance failure (fitness={:.3}): {}",
                breed_id,
                conformance.fitness,
                conformance.refusals.join("; ")
            ));
        }
    }

    output.ocel_log = Some(serde_json::to_value(&ocel_log).unwrap_or(serde_json::Value::Null));

    Ok(output)
}

/// Dispatch to the correct breed's `run()` method.
///
/// Parses the breed string via `BreedId::from_str_id`, then routes through
/// `breed_instance` — the macro-generated match is compiler-checked for
/// exhaustiveness. Unknown/unsupported strings are caught before the match.
pub fn dispatch_breed(breed: &str, input: &BreedInput) -> Result<BreedOutput, String> {
    let id = BreedId::from_str_id(breed).ok_or_else(|| {
        if matches!(breed, "triz" | "ocpm_route_discoverer") {
            format!("unsupported breed: {}", breed)
        } else {
            format!("unknown breed: {}", breed)
        }
    })?;
    dispatch_breed_id(id, input)
}

/// Table dispatch — a new `BreedId` macro entry routes automatically;
/// exhaustiveness lives in the macro-generated `breed_instance` match.
pub fn dispatch_breed_id(id: BreedId, input: &BreedInput) -> Result<BreedOutput, String> {
    run_breed(breed_instance(id), input)
}

/// Test harness: dispatch without OCEL or pre/post checks. Used for raw breed unit tests.
pub fn dispatch_breed_test(breed: &str, input: &BreedInput) -> Result<BreedOutput, String> {
    let id = BreedId::from_str_id(breed).ok_or_else(|| {
        if matches!(breed, "triz" | "ocpm_route_discoverer") {
            format!("unsupported breed: {}", breed)
        } else {
            format!("unknown breed: {}", breed)
        }
    })?;
    dispatch_breed_test_id(id, input)
}

/// Enum-match test dispatch — same exhaustiveness guarantee as `dispatch_breed_id`.
pub fn dispatch_breed_test_id(id: BreedId, input: &BreedInput) -> Result<BreedOutput, String> {
    breed_instance(id)
        .run(input)
        .map_err(|e| format!("{}: {}", e.breed, e.message))
}
